ARG CUDA_VER=12.4
ARG PYTHON_VERSION=3.11.9

FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference:2.5.1-gpu-py311-cu124-ubuntu22.04-sagemaker

# Specify accept-bind-to-port LABEL for inference pipelines to use SAGEMAKER_BIND_TO_PORT
# https://docs.aws.amazon.com/sagemaker/latest/dg/inference-pipeline-real-time.html
LABEL com.amazonaws.sagemaker.capabilities.accept-bind-to-port=true
# Specify multi-models LABEL to indicate container is capable of loading and serving multiple models concurrently
# https://docs.aws.amazon.com/sagemaker/latest/dg/build-multi-model-build-container.html
LABEL com.amazonaws.sagemaker.capabilities.multi-models=true

LABEL maintainer="Amazon AI"
LABEL dlc_major_version="1"

RUN apt-get update \
 && apt-get -y upgrade \
 && apt-get autoremove -y \
 && apt-get install tesseract-ocr -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

ARG AUTOGLUON_VERSION=1.2.0


# Upgrading pip and installing/updating Python dependencies
# Comments are added to explain the reason behind each update
RUN pip install --no-cache-dir -U --trusted-host pypi.org --trusted-host files.pythonhosted.org pip \
 # Update setuptools to a secure version that fixes CVE-2022-40897
 && pip install --no-cache-dir -U wheel \
 && pip uninstall -y dataclasses \
 && pip install --no-cache-dir -U numpy numba \
 && pip install --no-cache-dir -U autogluon==${AUTOGLUON_VERSION} \
 # Update requests to a secure version that fixes CVE-2023-32681
 && pip install --no-cache-dir -U requests>=2.31.0 \  
 # Capping setuptools to 69.5.1 to fix AutoMM tests
 && pip install --no-cache-dir setuptools==69.5.1 \
 # Update pillow to a secure version that fixes CVE-2023-50447
 && pip install --no-cache-dir -U pillow>=10.2.0 \
 # Update Jinja2 to a secure version that fixes vulnerability id 64227
 && pip install --no-cache-dir -U Jinja2>=3.1.3 \
 # Update aiohttp to a secure version that fixes vulnerability id 64642
 && pip install --no-cache-dir -U aiohttp>=3.9.2 \
 # update tqdm to a secure version that fixes CVE-2024-34062
 && pip install --no-cache-dir -U tqdm>=4.66.3 \
 # update urllib3 to fix vulnerability id 71608
 && pip install --no-cache-dir -U urllib3 \
  # Cap pillow & ninja to fix sanity test
 && pip install --no-cache-dir "pillow<11.0.0" \
 && pip install --no-cache-dir "ninja<1.11.1.1"


# add TS entrypoint
COPY config.properties /home/model-server

COPY torchserve-entrypoint.py /usr/local/bin/dockerd-entrypoint.py
RUN chmod +x /usr/local/bin/dockerd-entrypoint.py

RUN HOME_DIR=/root \
 && curl -o ${HOME_DIR}/oss_compliance.zip https://aws-dlinfra-utilities.s3.amazonaws.com/oss_compliance.zip \
 && unzip -o ${HOME_DIR}/oss_compliance.zip -d ${HOME_DIR}/ \
 && cp ${HOME_DIR}/oss_compliance/test/testOSSCompliance /usr/local/bin/testOSSCompliance \
 && chmod +x /usr/local/bin/testOSSCompliance \
 && chmod +x ${HOME_DIR}/oss_compliance/generate_oss_compliance.sh \
 && ${HOME_DIR}/oss_compliance/generate_oss_compliance.sh ${HOME_DIR} python \
 && rm -rf ${HOME_DIR}/oss_compliance*

RUN curl -o /licenses-autogluon.txt https://autogluon.s3.us-west-2.amazonaws.com/licenses/THIRD-PARTY-LICENSES.txt

EXPOSE 8080 8081
ENTRYPOINT ["python", "/usr/local/bin/dockerd-entrypoint.py"]
CMD ["torchserve", "--start", "--ts-config", "/home/model-server/config.properties", "--model-store", "/home/model-server/"]