# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.
"""EC2 telemetry integration tests.

Spawns a dedicated EC2 instance, pulls the DLC image, and verifies:
1. S3 query bucket URL is correctly constructed
2. EC2 instance tagging works under IMDSv2
3. Telemetry degrades gracefully when IMDS is unreachable
4. OPT_OUT_TRACKING disables telemetry
5. Entrypoint and bashrc triggers fire independently

Usage:
    PYTHONPATH=$(pwd)/test:$(pwd)/scripts/telemetry:$PYTHONPATH \
        pytest test/telemetry/test_telemetry.py -v \
        --image-uri <uri> --framework <fw> --framework-version <ver> \
        --container-type <type> \
        [--region us-west-2]

Fixtures from test/conftest.py: image_uri, region, aws_session
Fixtures from test/telemetry/conftest.py: framework, framework_version, container_type,
    ec2_instance, conn, pull_image
"""

import logging
from urllib.parse import parse_qs, urlparse

import pytest
from deep_learning_container import REGION_MAPPING as TELEMETRY_REGION_MAPPING

LOGGER = logging.getLogger(__name__)
LOGGER.setLevel(logging.INFO)

TELEMETRY_TAG_KEY = "aws-dlc-autogenerated-tag-do-not-delete"
DOCKER_RUN = "docker run -d -it --rm"
DOCKER_EXEC = "docker exec"
DOCKER_RM = "docker rm -f"


@pytest.fixture(scope="function")
def container_test_mode(conn, image_uri, pull_image):
    """Container with TEST_MODE=1 and default entrypoint."""
    container_name = "telemetry-test-mode"
    try:
        conn.run(f"{DOCKER_RUN} -e TEST_MODE=1 --name {container_name} {image_uri}")
        conn.run("sleep 10")
        yield container_name
    finally:
        conn.run(f"{DOCKER_RM} {container_name}", warn=True, hide=True)


@pytest.fixture(scope="function")
def container_default(conn, image_uri, pull_image):
    """Container with default entrypoint, no test mode."""
    container_name = "telemetry-default"
    try:
        conn.run(f"{DOCKER_RUN} --name {container_name} {image_uri}")
        conn.run("sleep 10")
        yield container_name
    finally:
        conn.run(f"{DOCKER_RM} {container_name}", warn=True, hide=True)


@pytest.fixture(scope="function")
def container_opt_out(conn, image_uri, pull_image):
    """Container with TEST_MODE=1 and OPT_OUT_TRACKING=true."""
    container_name = "telemetry-opt-out"
    try:
        conn.run(
            f"{DOCKER_RUN} -e TEST_MODE=1 -e OPT_OUT_TRACKING=true --name {container_name} {image_uri}"
        )
        conn.run("sleep 10")
        yield container_name
    finally:
        conn.run(f"{DOCKER_RM} {container_name}", warn=True, hide=True)


@pytest.fixture(scope="function")
def container_entrypoint(conn, image_uri, pull_image):
    """Container with default entrypoint + bash --norc (suppresses bashrc)."""
    container_name = "telemetry-entrypoint"
    try:
        conn.run(f"{DOCKER_RUN} -e TEST_MODE=1 --name {container_name} {image_uri} bash --norc")
        conn.run("sleep 10")
        yield container_name
    finally:
        conn.run(f"{DOCKER_RM} {container_name}", warn=True, hide=True)


@pytest.fixture(scope="function")
def container_bashrc(conn, image_uri, pull_image):
    """Container with entrypoint overridden (suppresses entrypoint telemetry)."""
    container_name = "telemetry-bashrc"
    try:
        conn.run(
            f"{DOCKER_RUN} -e TEST_MODE=1 --entrypoint /bin/bash --name {container_name} {image_uri}"
        )
        conn.run(f"{DOCKER_EXEC} {container_name} bash -i -c 'sleep 1'")
        conn.run("sleep 10")
        yield container_name
    finally:
        conn.run(f"{DOCKER_RM} {container_name}", warn=True, hide=True)


def test_s3_query_bucket_url(
    conn, container_test_mode, framework, framework_version, container_type, region, ec2_instance
):
    """Verify the telemetry S3 URL is correctly constructed."""
    LOGGER.info("Verifying S3 telemetry URL")
    instance_id, _ = ec2_instance
    result = conn.run(f"{DOCKER_EXEC} {container_test_mode} cat /tmp/test_request.txt")
    url = result.stdout.strip()

    parsed = urlparse(url)
    params = parse_qs(parsed.query)

    expected_host = (
        f"aws-deep-learning-containers-{TELEMETRY_REGION_MAPPING[region]}.s3.{region}.amazonaws.com"
    )
    assert parsed.hostname == expected_host, f"Host mismatch: {parsed.hostname} != {expected_host}"
    assert params["x-instance-id"][0] == instance_id
    assert params["x-framework"][0] == framework
    assert params["x-framework_version"][0] == framework_version
    assert params["x-container_type"][0] == container_type
    assert f"/dlc-containers-{instance_id}.txt" in parsed.path


def test_instance_tagging(aws_session, container_default, ec2_instance):
    """Verify telemetry creates the expected EC2 instance tag under IMDSv2."""
    LOGGER.info("Verifying EC2 instance tagging under IMDSv2")
    instance_id, _ = ec2_instance
    tags = aws_session.get_instance_tags(instance_id)
    assert TELEMETRY_TAG_KEY in tags, f"Tag '{TELEMETRY_TAG_KEY}' not found. Tags: {tags}"


def test_imds_unreachable(conn, aws_session, image_uri, ec2_instance, pull_image):
    """Verify telemetry degrades gracefully when IMDS is unreachable."""
    LOGGER.info("Blocking IMDS and verifying graceful degradation")
    instance_id, _ = ec2_instance
    aws_session.ec2.delete_tags(Resources=[instance_id], Tags=[{"Key": TELEMETRY_TAG_KEY}])

    container_name = "telemetry-imds-fail"
    try:
        conn.run("sudo iptables -A OUTPUT -d 169.254.169.254 -j REJECT")
        conn.run(f"{DOCKER_RUN} --name {container_name} {image_uri}")
        conn.run("sleep 15")

        result = conn.run(f"docker inspect -f '{{{{.State.Running}}}}' {container_name}")
        assert result.stdout.strip() == "true", "Container crashed when IMDS unreachable"

        tags = aws_session.get_instance_tags(instance_id)
        assert TELEMETRY_TAG_KEY not in tags, "Tag should not exist when IMDS is blocked"
    finally:
        conn.run("sudo iptables -D OUTPUT -d 169.254.169.254 -j REJECT", warn=True)
        conn.run(f"{DOCKER_RM} {container_name}", warn=True, hide=True)


def test_opt_out(conn, container_opt_out):
    """Verify OPT_OUT_TRACKING=true disables telemetry."""
    LOGGER.info("Verifying OPT_OUT_TRACKING=true disables telemetry")
    result = conn.run(f"{DOCKER_EXEC} {container_opt_out} test -f /tmp/test_request.txt", warn=True)
    assert result.return_code != 0, "Telemetry fired despite OPT_OUT_TRACKING=true"


def test_opt_in(conn, container_test_mode):
    """Verify telemetry fires when OPT_OUT_TRACKING is not set."""
    LOGGER.info("Verifying telemetry fires by default")
    result = conn.run(
        f"{DOCKER_EXEC} {container_test_mode} test -f /tmp/test_request.txt", warn=True
    )
    assert result.return_code == 0, "Telemetry did not fire when OPT_OUT_TRACKING is unset"


def test_entrypoint_trigger(conn, container_entrypoint):
    """Verify entrypoint triggers telemetry (bashrc suppressed via --norc)."""
    LOGGER.info("Verifying entrypoint triggers telemetry (bashrc suppressed)")
    result = conn.run(
        f"{DOCKER_EXEC} {container_entrypoint} test -f /tmp/test_request.txt", warn=True
    )
    assert result.return_code == 0, "Entrypoint did not trigger telemetry"


def test_bashrc_trigger(conn, container_bashrc):
    """Verify bashrc triggers telemetry (entrypoint suppressed via --entrypoint)."""
    LOGGER.info("Verifying bashrc triggers telemetry (entrypoint suppressed)")
    result = conn.run(f"{DOCKER_EXEC} {container_bashrc} test -f /tmp/test_request.txt", warn=True)
    assert result.return_code == 0, "Bashrc did not trigger telemetry"
