"""EC2 telemetry integration tests.

Spawns a dedicated EC2 instance, pulls the DLC image, and verifies:
1. S3 query bucket URL is correctly constructed
2. EC2 instance tagging works under IMDSv2
3. Telemetry degrades gracefully when IMDS is unreachable
4. IMDSv2 hop_limit=1 blocks container telemetry, hop_limit=2 allows it
5. OPT_OUT_TRACKING disables telemetry

NOTE: Tests must run sequentially (no pytest-xdist). They share a single EC2
instance and modify host-level state (iptables rules, IMDS hop limit, instance tags)
that would conflict under parallel execution.

Usage:
    PYTHONPATH=$(pwd)/test:$(pwd)/scripts/telemetry:$PYTHONPATH \
        pytest test/telemetry/test_telemetry.py -v \
        --image-uri <uri> --framework <fw> --framework-version <ver> \
        --container-type <type> \
        [--region us-west-2]

Fixtures from test/conftest.py: image_uri, region, aws_session
Fixtures from test/telemetry/conftest.py: framework, framework_version, container_type,
    ec2_instance, conn, pull_image
"""

import logging
from urllib.parse import parse_qs, urlparse

import pytest
from deep_learning_container import REGION_MAPPING as TELEMETRY_REGION_MAPPING

LOGGER = logging.getLogger(__name__)
LOGGER.setLevel(logging.INFO)

TELEMETRY_TAG_KEY = "aws-dlc-autogenerated-tag-do-not-delete"
SLEEP_SECONDS = 10


def delete_telemetry_tag(aws_session, instance_id):
    aws_session.ec2.delete_tags(Resources=[instance_id], Tags=[{"Key": TELEMETRY_TAG_KEY}])


def telemetry_file_exists(conn, container):
    result = conn.run(f"docker exec {container} test -f /tmp/test_request.txt", warn=True)
    return result.return_code == 0


@pytest.fixture(scope="function")
def telemetry_container(conn, image_uri, pull_image):
    """Factory fixture: call with (name, env) to start a container. Cleans up all after test."""
    containers = []

    def _start(name, env=None):
        env_flags = " ".join(f"-e {k}={v}" for k, v in (env or {}).items())
        conn.run(
            f"docker run -d -it --rm {env_flags} --entrypoint /bin/bash --name {name} {image_uri} -ic 'sleep 60'"
        )
        conn.run(f"sleep {SLEEP_SECONDS}")
        containers.append(name)
        return name

    yield _start

    for name in containers:
        conn.run(f"docker rm -f {name}", warn=True)


def test_s3_query_bucket_url(
    conn, telemetry_container, framework, framework_version, container_type, region, ec2_instance
):
    """Verify the telemetry S3 URL is correctly constructed."""
    instance_id, _ = ec2_instance
    container_name = telemetry_container("telemetry-s3-url", env={"TEST_MODE": "1"})
    result = conn.run(f"docker exec {container_name} cat /tmp/test_request.txt")
    url = result.stdout.strip()

    parsed = urlparse(url)
    params = parse_qs(parsed.query)

    expected_host = (
        f"aws-deep-learning-containers-{TELEMETRY_REGION_MAPPING[region]}.s3.{region}.amazonaws.com"
    )
    assert parsed.hostname == expected_host, f"Host mismatch: {parsed.hostname} != {expected_host}"
    assert params["x-instance-id"][0] == instance_id
    assert params["x-framework"][0] == framework
    assert params["x-framework_version"][0] == framework_version
    assert params["x-container_type"][0] == container_type
    assert f"/dlc-containers-{instance_id}.txt" in parsed.path


def test_instance_tagging(conn, aws_session, telemetry_container, ec2_instance):
    """Verify telemetry creates the expected EC2 instance tag under IMDSv2."""
    instance_id, _ = ec2_instance
    delete_telemetry_tag(aws_session, instance_id)
    telemetry_container("telemetry-tagging")
    tags = aws_session.get_instance_tags(instance_id)
    assert TELEMETRY_TAG_KEY in tags, f"Tag '{TELEMETRY_TAG_KEY}' not found. Tags: {tags}"


def test_imds_unreachable(conn, aws_session, telemetry_container, ec2_instance):
    """Verify telemetry degrades gracefully when IMDS is unreachable."""
    instance_id, _ = ec2_instance
    delete_telemetry_tag(aws_session, instance_id)
    try:
        conn.run("sudo iptables -I DOCKER-USER -d 169.254.169.254 -j REJECT")
        container_name = telemetry_container("telemetry-imds-fail")

        assert not telemetry_file_exists(conn, container_name), (
            "Telemetry should not write file when IMDS is blocked"
        )

        tags = aws_session.get_instance_tags(instance_id)
        assert TELEMETRY_TAG_KEY not in tags, "Tag should not exist when IMDS is blocked"
    finally:
        conn.run("sudo iptables -D DOCKER-USER -d 169.254.169.254 -j REJECT", warn=True)


def test_imds_hop_limit(conn, aws_session, telemetry_container, ec2_instance):
    """Verify telemetry fails with hop_limit=1 and succeeds with hop_limit=2."""
    instance_id, _ = ec2_instance

    # hop_limit=1: container can't get IMDSv2 token through Docker bridge
    delete_telemetry_tag(aws_session, instance_id)
    aws_session.ec2.modify_instance_metadata_options(
        InstanceId=instance_id, HttpPutResponseHopLimit=1
    )
    container_name = telemetry_container("telemetry-hop1", env={"TEST_MODE": "1"})

    assert not telemetry_file_exists(conn, container_name), (
        "Telemetry should not fire with hop_limit=1"
    )

    tags = aws_session.get_instance_tags(instance_id)
    assert TELEMETRY_TAG_KEY not in tags, "Tag should not exist with hop_limit=1"

    # hop_limit=2: container can get IMDSv2 token
    aws_session.ec2.modify_instance_metadata_options(
        InstanceId=instance_id, HttpPutResponseHopLimit=2
    )
    container_name = telemetry_container("telemetry-hop2", env={"TEST_MODE": "1"})

    assert telemetry_file_exists(conn, container_name), "Telemetry should fire with hop_limit=2"

    tags = aws_session.get_instance_tags(instance_id)
    assert TELEMETRY_TAG_KEY in tags, f"Tag should exist with hop_limit=2. Tags: {tags}"


def test_opt_out(conn, telemetry_container):
    """Verify OPT_OUT_TRACKING=true disables telemetry."""
    container_name = telemetry_container(
        "telemetry-opt-out", env={"TEST_MODE": "1", "OPT_OUT_TRACKING": "true"}
    )
    assert not telemetry_file_exists(conn, container_name), (
        "Telemetry fired despite OPT_OUT_TRACKING=true"
    )


def test_opt_in(conn, telemetry_container):
    """Verify telemetry fires automatically via bashrc when OPT_OUT_TRACKING is not set."""
    container_name = telemetry_container("telemetry-opt-in", env={"TEST_MODE": "1"})
    assert telemetry_file_exists(conn, container_name), (
        "Telemetry did not fire when OPT_OUT_TRACKING is unset"
    )
