#### First image: sha256:b3903e4c2c31d90014abcefde41926085f1f23228acaa3882e5c7568aeed9505 ####
#### Current Patch contents ####
pip install requests==2.32.2 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade python3-idna
