#### First image: sha256:c277954376db527ac5f50d65bd5bfd26f99bace1784b63f159de3843d438a4b4 ####
#### Patch contents for patch-1: sha256:1448b1d51199cbe71323990d2add178b8663789ec9671ec5460cf5c11b5ecfea ####
echo N/A
echo N/A
#### Patch contents for patch-2: sha256:fd39b9d871e4f1231817cec8d3abf8e64ea2e96be99b912516d2148002ca9b0a ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git
#### Patch contents for patch-3: sha256:ab9d922cbd8a7264e829e502fb1d43305637cf4ce598bf9559650b1ac936127c ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2
#### Patch contents for patch-4: sha256:517cbe643898d5ec7046f6991befadcd5adcf7c89d1fff0f57e55503e18eebd8 ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 linux-libc-dev
#### Patch contents for patch-5: sha256:15f16c0888f4a552edce870b7d2dfd37d6882305b49cb7d139c3d5962c2d65e2 ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 linux-libc-dev wget
#### Current Patch contents ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 linux-libc-dev wget
