name: Container Cleanup
description: Remove container and clean up image caches.

runs:
  using: composite
  steps:
    - name: Cleanup container and images
      shell: bash
      run: |
        docker rm -f ${CONTAINER_ID} || true
        docker image prune -a --force --filter "until=24h"
        docker system df
