name: Disk Cleanup
description: Disk cleanup

runs:
  using: composite
  steps:
    - name: Cleanup container and images
      shell: bash
      run: |
        echo "echo \$\{\{ github.workspace \}\} / \$\}GITHUB_WORKSPACE\}: ${GITHUB_WORKSPACE}"
        echo "echo \$\}RUNNER_TEMP\}: ${RUNNER_TEMP}"
        df -h
        du -sh /tmp/*
        du -sh /* --exclude /tmp/*
        sleep 60s
