version: 0.2

phases:
  install:
    commands:
      - echo "Setting up CodeBuild fleet runner infrastructure ..."
      - ls -la /tmp

      # Install uv and other common dependencies across all runner fleets
      - echo "Installing runner dependencies ..."
      - ls -la ${CODEBUILD_SRC_DIR}
      - ls -la ${CODEBUILD_SRC_DIR}/.github
      - ls -la ${CODEBUILD_SRC_DIR}/.github/scripts
      # - bash ${CODEBUILD_SRC_DIR}/.github/scripts/runner_setup.sh

      # Install and setup clean up daemon
      - echo "Installing runner systemd services ..."

      - CURRENT_CODEBUILD_DIR=$(echo "$CODEBUILD_SRC_DIR" | grep -o '/tmp/codebuild-[^/]*')
      - find /tmp -maxdepth 1 -type d -name 'codebuild-*' ! -path "$CURRENT_CODEBUILD_DIR" -exec rm -rf {} +
      - ls -la /tmp

  pre_build:
    commands:
      - echo "Creating lock file GHA runtime environment ..."

  build:
    commands:
      - echo "BuildSpec will be overloaded for GHA self-hosted runner builds."

  post_build:
    commands:
      - echo "Deleting GHA runtime environment lock file ..."
      - echo "Build completed on $(date)"
