version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - start-dockerd
      - for i in {1..3}; do pip install -r src/requirements.txt && break || sleep 30; done
      - python src/send_status.py --status 2
  build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - export PYTHONPATH=$PYTHONPATH:$(pwd)/src
      - pip install -r src/requirements.txt
      - pip install -r test/requirements.txt
      - pip install scheduler/.
      - echo Running $TEST_TYPE tests on $DLC_IMAGES...
      - python src/autopr_caller.py
  post_build:
    commands:
      - python src/send_status.py --status $CODEBUILD_BUILD_SUCCEEDING
reports:
  test_reports:
    files:
      - test/*.xml
    file-format: JunitXml