version: 0.2

#TODO: Move all constatns to environment variables
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - pip install -r src/requirements.txt
      - cd $FRAMEWORK/$IMAGE_TYPE
      - python setup.py sdist
      - cd ../../
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - python src/build.py --buildspec $FRAMEWORK/$IMAGE_TYPE/buildspec.yml
