version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - bash eks_infra/env_setup.sh
  build:
    commands:
      - bash eks_infra/build.sh
      - echo "build succeeded"

