version: 0.2

phases:
  pre_build:
    commands:
      - start-dockerd
      - pip install -r src/requirements.txt
  build:
    commands:
      - export PYTHONPATH=$PYTHONPATH:$(pwd)/src
      - publish_dlc_images --release-spec $(pwd)/$RELEASE_IMAGE_FILE
      - generate_release_information
