account_id: &ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>
region: &REGION <set-$REGION-in-environment>
base_framework: &BASE_FRAMEWORK tensorflow
framework: &FRAMEWORK !join [ "huggingface_", *BASE_FRAMEWORK, "_trcomp"]
version: &VERSION 2.6.3
short_version: &SHORT_VERSION 2.6

repository_info:
  training_repository: &TRAINING_REPOSITORY
    image_type: &TRAINING_IMAGE_TYPE training
    root: !join [ "huggingface/", *BASE_FRAMEWORK, "/", *TRAINING_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join ["pr", "-", "huggingface", "-", *BASE_FRAMEWORK, "-", "trcomp", "-", *TRAINING_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]

images:
  BuildHFTensorflowTrCompGpuPy38Cu112TrainingDockerImage:
    <<: *TRAINING_REPOSITORY
    build: &HUGGINGFACE_TENSORFLOW_TRCOMP_GPU_TRAINING_PY3 false
    image_size_baseline: &IMAGE_SIZE_BASELINE 12500
    device_type: &DEVICE_TYPE gpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py38
    cuda_version: &CUDA_VERSION cu112
    os_version: &OS_VERSION ubuntu20.04
    transformers_version: &TRANSFORMERS_VERSION 4.17.0
    datasets_version: &DATASETS_VERSION 1.18.2
    tag: !join [ *VERSION, '-', 'transformers', *TRANSFORMERS_VERSION, '-', *DEVICE_TYPE, '-', *TAG_PYTHON_VERSION, '-',
                 *CUDA_VERSION, '-', *OS_VERSION ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /,
                         *CUDA_VERSION, /Dockerfile.trcomp., *DEVICE_TYPE ]
    download_artifacts:
      tensorflow_whl:
        type: s3
        URI: s3://framework-binaries/tensorflow/trcomp/r2.6_aws/gpu/2022-03-20-05-33/tensorflow_gpu-2.6.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
        VAR_IN_DOCKERFILE: TF_URL
      sagemaker_pysdk_whl:
        type: s3
        URI: s3://sagemaker-python-sdk-524001406597/dist/sagemaker.tar.gz 
        VAR_IN_DOCKERFILE: SAGEMAKER_BINARY
