#### First image: sha256:75ed08d5b07b8f27b441c41d017d12aa327a7466f18e4c9b25b388e929fbdc0f ####
#### Current Patch contents ####
pip install aiohttp==3.9.3 cryptography==42.0.5 jinja2==3.1.3 paramiko==3.4.0 pillow==10.2.0 pyopenssl==24.0.0 transformers==4.38.2
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils curl libbinutils libc-bin libc6 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libgnutls30 libpam-modules libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsqlite3-0 libssh-4 libssl1.1 libtiff5 libuv1 libxml2 linux-libc-dev login openssh-client openssh-server passwd vim-common vim-runtime vim xxd
