#### First image: sha256:30d90833a63531a4df388775b0d7a1689f5da4522f1aed589ad2c7af249e384b ####
#### Patch contents for patch-1: sha256:150d68c86b74a1ea68a9f49b110995b760cee753c7a5206fc62e1cd4c3c694fd ####
echo N/A
echo N/A
#### Patch contents for patch-2: sha256:568474f51e4ba96ed7a8bb39c493237a4e716d03ea7b62cb0a91edb97f98eaed ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git
#### Patch contents for patch-3: sha256:22b53621ec87a38d1b05c0b5634f06168dbbb9f035ed6669446d3591be125ef7 ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2
#### Patch contents for patch-4: sha256:e888f78506128c6612931b37d06ce06bf5cf6ed570d1c96c6770989e5558a74b ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 linux-libc-dev
#### Patch contents for patch-5: sha256:987a2358a757b066f72b9b40d1cc77bb7865207d47dc14887caddbbe4fa9d2ed ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 linux-libc-dev wget
#### Patch contents for patch-6: sha256:9654d06c0d885225d9da26fd28c25d08efe53cd220808194ff7cbffd9a768daf ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 linux-libc-dev wget
#### Current Patch contents ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 linux-libc-dev wget
