#### First image: sha256:4e2bd083e10da23c246995551ae9f5f419ef3244c12f9883a7c207aa1d346f0e ####
#### Patch contents for patch-1: sha256:b6cf495a112f3e1ecaef932dfad98818b43badb3dff5d0c374199e524f6264f2 ####
echo N/A
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils libbinutils libctf-nobfd0 libctf0 libgnutls30 libssh-4 linux-libc-dev
#### Patch contents for patch-2: sha256:a383648a9699073ec8956d99ae547395f586b6123f881298c51c1a49f1c59e4b ####
pip install cryptography==42.0.5 pyopenssl==24.0.0
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils libbinutils libctf-nobfd0 libctf0 libgnutls30 libpam-modules libssh-4 libssl1.1 libtiff5 libuv1 libxml2 linux-libc-dev login openjdk-11-jdk-headless openjdk-11-jdk openjdk-11-jre-headless openjdk-11-jre passwd
#### Patch contents for patch-3: sha256:cbaba0362167ee0c5da197bbb2928812a0027cee656c87da35ff034bbbb5ddff ####
pip install cryptography==42.0.5 pyopenssl==24.0.0
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils libbinutils libctf-nobfd0 libctf0 libgnutls30 libpam-modules libssh-4 libssl1.1 libtiff5 libuv1 libxml2 linux-libc-dev login openjdk-11-jdk-headless openjdk-11-jdk openjdk-11-jre-headless openjdk-11-jre passwd
#### Patch contents for patch-4: sha256:d5b1aa96f2056fd65e7aafc34f414371e959fa023b9b1edf0aba924e7a8c2478 ####
pip install cryptography==42.0.5 pyopenssl==24.1.0
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils libbinutils libctf-nobfd0 libctf0 libgnutls30 libpam-modules libssh-4 libssl-dev libssl1.1 libtiff5 libuv1 libxml2 linux-libc-dev login openjdk-11-jdk-headless openjdk-11-jdk openjdk-11-jre-headless openjdk-11-jre openssl passwd
#### Current Patch contents ####
pip install cryptography==42.0.5 pyopenssl==24.1.0
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils libbinutils libctf-nobfd0 libctf0 libgnutls30 libpam-modules libssh-4 libssl-dev libssl1.1 libtiff5 libuv1 libxml2 linux-libc-dev login openjdk-11-jdk-headless openjdk-11-jdk openjdk-11-jre-headless openjdk-11-jre openssl passwd vim-common vim-runtime vim xxd
