#### First image: sha256:4e2bd083e10da23c246995551ae9f5f419ef3244c12f9883a7c207aa1d346f0e ####
#### Patch contents for patch-1: sha256:b6cf495a112f3e1ecaef932dfad98818b43badb3dff5d0c374199e524f6264f2 ####
echo N/A
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils libbinutils libctf-nobfd0 libctf0 libgnutls30 libssh-4 linux-libc-dev
#### Patch contents for patch-2: sha256:a383648a9699073ec8956d99ae547395f586b6123f881298c51c1a49f1c59e4b ####
pip install cryptography==42.0.5 pyopenssl==24.0.0
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils libbinutils libctf-nobfd0 libctf0 libgnutls30 libpam-modules libssh-4 libssl1.1 libtiff5 libuv1 libxml2 linux-libc-dev login openjdk-11-jdk-headless openjdk-11-jdk openjdk-11-jre-headless openjdk-11-jre passwd
#### Patch contents for patch-3: sha256:cbaba0362167ee0c5da197bbb2928812a0027cee656c87da35ff034bbbb5ddff ####
pip install cryptography==42.0.5 pyopenssl==24.0.0
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils libbinutils libctf-nobfd0 libctf0 libgnutls30 libpam-modules libssh-4 libssl1.1 libtiff5 libuv1 libxml2 linux-libc-dev login openjdk-11-jdk-headless openjdk-11-jdk openjdk-11-jre-headless openjdk-11-jre passwd
#### Patch contents for patch-4: sha256:d5b1aa96f2056fd65e7aafc34f414371e959fa023b9b1edf0aba924e7a8c2478 ####
pip install cryptography==42.0.5 pyopenssl==24.1.0
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils libbinutils libctf-nobfd0 libctf0 libgnutls30 libpam-modules libssh-4 libssl-dev libssl1.1 libtiff5 libuv1 libxml2 linux-libc-dev login openjdk-11-jdk-headless openjdk-11-jdk openjdk-11-jre-headless openjdk-11-jre openssl passwd
#### Patch contents for patch-5: sha256:a29e0eed6c7d60fc5f799cd4165f38c516471e91bf66c67ad8003a69f9a2a600 ####
pip install cryptography==42.0.5 pyopenssl==24.1.0
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils libbinutils libctf-nobfd0 libctf0 libgnutls30 libpam-modules libssh-4 libssl-dev libssl1.1 libtiff5 libuv1 libxml2 linux-libc-dev login openjdk-11-jdk-headless openjdk-11-jdk openjdk-11-jre-headless openjdk-11-jre openssl passwd vim-common vim-runtime vim xxd
#### Patch contents for patch-6: sha256:1f896000a86ab3266037095d2ae8c7637b697d7857b206910a0dee44a7ed0bc4 ####
pip install cryptography==42.0.5 pillow==10.3.0 pyopenssl==24.1.0
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils bsdutils curl fdisk libbinutils libblkid1 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgnutls30 libmount1 libpam-modules libsmartcols1 libssh-4 libssl-dev libssl1.1 libtiff5 libuuid1 libuv1 libxml2 linux-libc-dev login mount openjdk-11-jdk-headless openjdk-11-jdk openjdk-11-jre-headless openjdk-11-jre openssl passwd util-linux vim-common vim-runtime vim xxd
#### Patch contents for patch-7: sha256:c40a8f2e588ab9d377c72f329d6a762f1ab701642f30ed6eea2f277c78e53aa5 ####
pip install cryptography==42.0.5 pillow==10.3.0 pyopenssl==24.1.0
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils bsdutils curl fdisk libbinutils libblkid1 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgnutls30 libmount1 libpam-modules libsmartcols1 libssh-4 libssl-dev libssl1.1 libtiff5 libuuid1 libuv1 libxml2 linux-libc-dev login mount openjdk-11-jdk-headless openjdk-11-jdk openjdk-11-jre-headless openjdk-11-jre openssl passwd util-linux vim-common vim-runtime vim xxd
#### Patch contents for patch-8: sha256:111b4f0a706183152f698a1f0ce4621760af2bebfc3eaacb593fbceab31d337f ####
pip install cryptography==42.0.5 pillow==10.3.0 pyopenssl==24.1.0 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils bsdutils curl fdisk libbinutils libblkid1 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgnutls30 libmount1 libnss3 libpam-modules libsmartcols1 libssh-4 libssl-dev libssl1.1 libtiff5 libuuid1 libuv1 libxml2 linux-libc-dev login mount openjdk-11-jdk-headless openjdk-11-jdk openjdk-11-jre-headless openjdk-11-jre openssl passwd util-linux vim-common vim-runtime vim xxd
#### Patch contents for patch-9: sha256:6648eb24a592190026bc703c2c0540e9559a9acdef6197b86d327f9cbd56bcef ####
pip install cryptography==42.0.5 idna==3.7 pillow==10.3.0 pyopenssl==24.1.0 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils bsdutils curl fdisk libbinutils libblkid1 libc6 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgnutls30 libmount1 libnss3 libpam-modules libsmartcols1 libssh-4 libssl-dev libssl1.1 libtiff5 libuuid1 libuv1 libxml2 linux-libc-dev login mount openjdk-11-jdk-headless openjdk-11-jdk openjdk-11-jre-headless openjdk-11-jre openssl passwd util-linux vim-common vim-runtime vim xxd
#### Current Patch contents ####
pip install cryptography==42.0.5 idna==3.7 pillow==10.3.0 pyopenssl==24.1.0 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils bsdutils curl fdisk libbinutils libblkid1 libc6 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgnutls30 libmount1 libnghttp2-14 libnss3 libpam-modules libsmartcols1 libssh-4 libssl-dev libssl1.1 libtiff5 libuuid1 libuv1 libxml2 linux-libc-dev login mount openjdk-11-jdk-headless openjdk-11-jdk openjdk-11-jre-headless openjdk-11-jre openssl passwd util-linux vim-common vim-runtime vim xxd
