#### First image: sha256:77759d7e295b3a8b19e86c6425a55739474d9eaa8a3e163afd40c4263a341eae ####
#### Current Patch contents ####
pip install requests==2.32.2 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade python3-idna
