  # Enforced constraints:
  # All anchors must be upper case version of the key name
  # All anchors can be overriden by environment variables
  # All references to anchors must only be used after declaration
  # All keys can be overriden by environment variables
  account_id: &ACCOUNT_ID '669063966089'
  region: &REGION us-west-2
  framework: &FRAMEWORK tensorflow
  version: &VERSION 1.15.0
  image_type: &IMAGE_TYPE training
  root: !join [ *FRAMEWORK, "/", *IMAGE_TYPE ]
  repository_name: &REPOSITORY_NAME !join [beta, "-", *FRAMEWORK, "-", *IMAGE_TYPE]
  repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ] 

  # The context specifies the artifacts necessary for the
  # docker build. Each artifact needs to be specified as follows:
  # source: target
  # Both source and target can be complete paths relative to the root path
  # specified above. 
  context:
      dist/sagemaker_tensorflow_container-2.0.8.dev0.tar.gz: sagemaker_tensorflow_container-2.0.8.dev0.tar.gz
      docker/build_artifacts/dockerd-entrypoint.py: dockerd-entrypoint.py
      docker/build_artifacts/deep_learning_container.py: deep_learning_container.py

  images:
    BuildTensorflowCPUTrainPy3DockerImage:
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &PYTHON_VERSION py3
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
    BuildTensorflowGPUTrainPy3DockerImage:
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &PYTHON_VERSION py3
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
    BuildTensorflowCPUTrainPy2DockerImage:
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &PYTHON_VERSION py2
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
    BuildTensorflowGPUTrainPy2DockerImage:
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &PYTHON_VERSION py2
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
