account_id: &ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>
region: &REGION <set-$REGION-in-environment>
framework: &FRAMEWORK tensorflow
version: &VERSION 2.12.0
short_version: &SHORT_VERSION "2.12"
arch_type: x86

repository_info:
  training_repository: &TRAINING_REPOSITORY
    image_type: &TRAINING_IMAGE_TYPE training
    root: !join [ *FRAMEWORK, "/", *TRAINING_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *TRAINING_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/,
      *REPOSITORY_NAME ]
context:
  training_context: &TRAINING_CONTEXT
    dockerd-entrypoint:
      source: docker/build_artifacts/dockerd-entrypoint.py
      target: dockerd-entrypoint.py
    deep_learning_container:
      source: ../../src/deep_learning_container.py
      target: deep_learning_container.py
images:
#  BuildTensorflowEC2CpuPy39TrainingDockerImage:
#    <<: *TRAINING_REPOSITORY
#    build: &TENSORFLOW_CPU_TRAINING_PY3 false
#    image_size_baseline: &IMAGE_SIZE_BASELINE 4489
#    device_type: &DEVICE_TYPE cpu
#    python_version: &DOCKER_PYTHON_VERSION py3
#    tag_python_version: &TAG_PYTHON_VERSION py310
#    os_version: &OS_VERSION ubuntu20.04
#    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION, "-ec2"
#      ]
#    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile.,
#      *DEVICE_TYPE ]
#    target: ec2
#    enable_test_promotion: true
#    context:
#      <<: *TRAINING_CONTEXT
#  BuildTensorflowEC2GpuCu112Py39TrainingDockerImage:
#    <<: *TRAINING_REPOSITORY
#    build: &TENSORFLOW_GPU_TRAINING_PY3 false
#    image_size_baseline: &IMAGE_SIZE_BASELINE 9307
#    device_type: &DEVICE_TYPE gpu
#    python_version: &DOCKER_PYTHON_VERSION py3
#    tag_python_version: &TAG_PYTHON_VERSION py310
#    cuda_version: &CUDA_VERSION cu118
#    os_version: &OS_VERSION ubuntu20.04
#    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION,
#      "-", *OS_VERSION, "-ec2" ]
#    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION,
#      /Dockerfile., *DEVICE_TYPE ]
#    target: ec2
#    enable_test_promotion: true
#    context:
#      <<: *TRAINING_CONTEXT
#  BuildTensorflowExampleGpuCu118Py310TrainingDockerImage:
#    <<: *TRAINING_REPOSITORY
#    build: &TENSORFLOW_GPU_TRAINING_PY3 false
#    image_size_baseline: &IMAGE_SIZE_BASELINE 9295
#    base_image_name: BuildTensorflowEC2GpuCu112Py39TrainingDockerImage
#    device_type: &DEVICE_TYPE gpu
#    python_version: &DOCKER_PYTHON_VERSION py3
#    tag_python_version: &TAG_PYTHON_VERSION py310
#    cuda_version: &CUDA_VERSION cu118
#    os_version: &OS_VERSION ubuntu20.04
#    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION,
#      "-", *OS_VERSION, "-ec2-example" ]
#    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /example,
#      /Dockerfile., *DEVICE_TYPE ]
#    enable_test_promotion: true
#    context:
#      <<: *TRAINING_CONTEXT
  BuildTensorflowSageMakerCpuPy310TrainingDockerImage:
    <<: *TRAINING_REPOSITORY
    build: &TENSORFLOW_CPU_TRAINING_PY3 false
    image_size_baseline: &IMAGE_SIZE_BASELINE 7500
    device_type: &DEVICE_TYPE cpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py310
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION, "-sagemaker"
    ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile.,
                         *DEVICE_TYPE ]
    target: sagemaker
    enable_test_promotion: true
    context:
      <<: *TRAINING_CONTEXT
  BuildTensorflowSageMakerGpuPy310Cu118TrainingDockerImage:
    <<: *TRAINING_REPOSITORY
    build: &TENSORFLOW_GPU_TRAINING_PY3 false
    image_size_baseline: &IMAGE_SIZE_BASELINE 11998
    device_type: &DEVICE_TYPE gpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py310
    cuda_version: &CUDA_VERSION cu118
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION,
                 "-", *OS_VERSION, "-sagemaker" ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION,
                         /Dockerfile., *DEVICE_TYPE ]
    target: sagemaker
    enable_test_promotion: true
    context:
      <<: *TRAINING_CONTEXT
