#### First image: sha256:9836cf70a5cd30b928bf697527a2521d5889b165265e2b366c2d90771e7b9450 ####
#### Patch contents for patch-1: sha256:07d7f259806316d99c5c817b22cf31891edf6ff88c81a8c69b9af66768c4a73d ####
echo N/A
apt-get update && apt-get install -y --only-upgrade libgtk-3-0 linux-libc-dev
#### Patch contents for patch-2: sha256:47967615ce7dac153b408965e01abddd353ac5f129e1cfcaf3d2acf35ff65d9b ####
echo N/A
apt-get update && apt-get install -y --only-upgrade libgtk-3-0 linux-libc-dev
#### Patch contents for patch-3: sha256:4838599e73ac40148e4b03e2583b833cbf3726325624a844d3f2cf5968a2004d ####
echo N/A
apt-get update && apt-get install -y --only-upgrade libgtk-3-0 linux-libc-dev
#### Patch contents for patch-4: sha256:003ada64cb9e04828913f564ae74ad2efb2913c8f3fd482c50e013a3212ecdbb ####
echo N/A
apt-get update && apt-get install -y --only-upgrade curl imagemagick-6-common libcurl3-gnutls libcurl4 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 linux-libc-dev
#### Patch contents for patch-5: sha256:40f5f02c5ca345cef15c3c41a38246bdb795b523ff2bd69e9bf861b103137791 ####
echo N/A
apt-get update && apt-get install -y --only-upgrade curl imagemagick-6-common libcurl3-gnutls libcurl4 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 linux-libc-dev
#### Patch contents for patch-6: sha256:33560f2d3eaaffd33e312f1cdeb18f169771ce21673d15ba2b8f41b352f870d7 ####
echo N/A
apt-get update && apt-get install -y --only-upgrade curl imagemagick-6-common libcurl3-gnutls libcurl4 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 linux-libc-dev
#### Patch contents for patch-7: sha256:c24f7bc2775b13ea09931d8bc6dddac2ceaf55302a83b7fe7d36a6c58a6731ee ####
echo N/A
apt-get update && apt-get install -y --only-upgrade curl imagemagick-6-common libcurl3-gnutls libcurl4 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 linux-libc-dev
#### Current Patch contents ####
echo N/A
apt-get update && apt-get install -y --only-upgrade curl imagemagick-6-common libcurl3-gnutls libcurl4 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 linux-libc-dev
