  account_id: &ACCOUNT_ID '669063966089'
  region: &REGION us-west-2
  framework: &FRAMEWORK pytorch
  version: &VERSION 1.3.1
  

  repository_info:
    training_repository: &TRAINING_REPOSITORY
        image_type: &IMAGE_TYPE training
        root: !join [ *FRAMEWORK, "/", *IMAGE_TYPE ]
        repository_name: &REPOSITORY_NAME !join [beta, "-", *FRAMEWORK, "-", *IMAGE_TYPE]
        repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ] 
    inference_repository: &INFERENCE_REPOSITORY
        image_type: &IMAGE_TYPE inference
        root: !join [ *FRAMEWORK, "/", *IMAGE_TYPE ]
        repository_name: &REPOSITORY_NAME !join [beta, "-", *FRAMEWORK, "-", *IMAGE_TYPE]
        repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]

  context:
    training_context: &TRAINING_CONTEXT
      docker/build_artifacts/changehostname.c: changehostname.c
      docker/build_artifacts/start_with_right_hostname.sh: start_with_right_hostname.sh 
      dist/sagemaker_pytorch_container-1.3.1-py2.py3-none-any.whl: sagemaker_pytorch_container-1.3.1-py2.py3-none-any.whl
    inference_context: &INFERENCE_CONTEXT
      docker/build_artifacts/mms-entrypoint.py: mms-entrypoint.py
      docker/build_artifacts/config.properties: config.properties
      docker/build_artifacts/deep_learning_container.py: deep_learning_container.py
      dist/sagemaker_pytorch_serving_container-1.3-py2.py3-none-any.whl: sagemaker_pytorch_serving_container-1.3-py2.py3-none-any.whl

  images:
    BuildCPUPTTrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &PYTHON_VERSION py3
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildGPUPTTrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      build: true
      image_size_baseline: 9228
      device_type: &DEVICE_TYPE gpu
      python_version: &PYTHON_VERSION py3
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildCPUPTTrainPy2DockerImage:
      <<: *TRAINING_REPOSITORY
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &PYTHON_VERSION py2
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildGPUPTTrainPy2DockerImage:
      <<: *TRAINING_REPOSITORY
      build: true
      image_size_baseline: 9028
      device_type: &DEVICE_TYPE gpu
      python_version: &PYTHON_VERSION py2
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildCPUPTInferencePy3DockerImage:
      <<: *INFERENCE_REPOSITORY
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &PYTHON_VERSION py3
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
    BuildGPUPTInferencePy3DockerImage:
      <<: *INFERENCE_REPOSITORY
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &PYTHON_VERSION py3
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
    BuildCPUPTInferencePy2DockerImage:
      <<: *INFERENCE_REPOSITORY
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &PYTHON_VERSION py2
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
    BuildGPUPTInferencePy2DockerImage:
      <<: *INFERENCE_REPOSITORY
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &PYTHON_VERSION py2
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
