image:
  name: "pytorch-sagemaker-cuda"
  description: "PyTorch CUDA training for SageMaker"
common:
  framework: "pytorch_runtime"
  framework_version: "2.11.0"
  job_type: "training"
  python_version: "py312"
  cuda_version: "cu130"
  os_version: "amzn2023"
  customer_type: "sagemaker"
  platform: "sagemaker"
  arch_type: "x86"
  prod_image: "pytorch:2.11-cu130-amzn2023-sagemaker"
  device_type: "gpu"
  contributor: "None"
release:
  release: true
  force_release: false
  public_registry: false
  private_registry: true
  enable_soci: false
  environment: production
