image:
  name: "pytorch-ec2-cuda"
  description: "PyTorch CUDA training for EC2 instances"
common:
  framework: "pytorch_runtime"
  framework_version: "2.11.0"
  job_type: "training"
  python_version: "py312"
  cuda_version: "cu130"
  os_version: "amzn2023"
  customer_type: "ec2"
  arch_type: "x86"
  prod_image: "pytorch:2.11-cu130-amzn2023"
  device_type: "gpu"
  contributor: "None"
release:
  release: true
  force_release: false
  public_registry: true
  private_registry: true
  enable_soci: true
  environment: production
