# Take the base MXNet Container
ARG BASE_IMAGE=""

FROM $BASE_IMAGE

# Add Custom stack of code
RUN git clone -b v1.8.x https://github.com/apache/incubator-mxnet.git

# Repository to run EKS test case
RUN git clone -b v0.20.2 https://github.com/horovod/horovod.git

ENTRYPOINT ["python", "/incubator-mxnet/example/image-classification/train_mnist.py"]
