#### First image: sha256:2d628847d623e0ccc8746fc82207fb226d77b813ba791ec450cf9389ebf366e3 ####
#### Patch contents for patch-1: sha256:c18e398075245e5ebe6de9f89f5c17e6a9700684602ff5797d84d99f791e0fd5 ####
pip install requests==2.32.3 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade git-man git libc-bin libc-dev-bin libc6-dev libc6 python3-idna
#### Patch contents for patch-2: sha256:4509371ebbcc7f940f189107a045214406c12a6268c9d76f4c52150142db3450 ####
pip install requests==2.32.3 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade git-man git libc-bin libc-dev-bin libc6-dev libc6 libgdk-pixbuf2.0-0 python3-idna
#### Patch contents for patch-3: sha256:c971d043beff7b6d25637ee4b2ada1afea4abe425fc7c18f901c26802389ff39 ####
pip install requests==2.32.3 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade git-man git libc-bin libc-dev-bin libc6-dev libc6 libgdk-pixbuf2.0-0 libtiff5 python3-idna
#### Patch contents for patch-4: sha256:e0cff72b4151ea70262bafbac0c115814179b626f714f0d3b99201fb33c01e5f ####
pip install cryptography==42.0.8 requests==2.32.3 scikit-learn==1.5.0 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade git-man git libc-bin libc-dev-bin libc6-dev libc6 libgdk-pixbuf2.0-0 libtiff5 linux-libc-dev python3-idna
#### Patch contents for patch-5: sha256:16d6a63aabfc1fb4556df0dbb1866025808ba807833cebe7032b3e3202cd3bb8 ####
pip install cryptography==42.0.8 requests==2.32.3 scikit-learn==1.5.0 urllib3==1.26.19 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade git-man git libc-bin libc-dev-bin libc6-dev libc6 libcups2 libgdk-pixbuf2.0-0 libtiff5 linux-libc-dev python3-idna
#### Patch contents for patch-6: sha256:4d573de4ef2f2380fbf8b6fd2936cc1b70d19a2f1865da123a8c5b277c84a827 ####
pip install cryptography==42.0.8 requests==2.32.3 scikit-learn==1.5.0 urllib3==1.26.19 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade git-man git libc-bin libc-dev-bin libc6-dev libc6 libcups2 libgdk-pixbuf2.0-0 libtiff5 linux-libc-dev python3-idna wget
#### Patch contents for patch-7: sha256:99d705b40fb756f64c4d85bcb5366ae6281b23024d83f937a32fc83033b96cba ####
pip install cryptography==42.0.8 requests==2.32.3 scikit-learn==1.5.0 urllib3==1.26.19 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade git-man git libc-bin libc-dev-bin libc6-dev libc6 libcups2 libgdk-pixbuf2.0-0 libtiff5 linux-libc-dev python3-idna wget
#### Current Patch contents ####
pip install cryptography==42.0.8 requests==2.32.3 scikit-learn==1.5.1 tornado==6.4.1 urllib3==1.26.19 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade git-man git libc-bin libc-dev-bin libc6-dev libc6 libcups2 libgdk-pixbuf2.0-0 libtiff5 linux-libc-dev python3-idna wget
