[project]
name = "dlc-ray"
version = "1.1.0"
requires-python = "==3.13.*"
dependencies = [
    "awscli==1.46.0",
    "pip==26.2.1",
    "boto3==1.43.68",
    "fastapi==0.133.1",
    "httpx==0.28.1",
    "numpy==2.5.2",
    "opencv-python==4.13.0.92",
    "pandas==3.0.5",
    "pillow==12.3.0",
    "pyyaml==6.0.3",
    "msgpack>=1.2.1",
    "aiohttp>=3.14.3",
    "ray[serve]==2.57.0",
    "scikit-learn==1.9.0",
    "soundfile==0.14.0",
    "torch==2.10.0",
    "torchaudio==2.10.0",
    "torchcodec==0.10.0",
    "torchvision==0.25.0",
    "transformers==5.8.0",
    "uvicorn[standard]==0.41.0",
]
