image:
  name: "pytorch-2.11-ec2-cpu"
  description: "PyTorch 2.11 CPU training for EC2 instances"

metadata:
  framework: "pytorch_runtime"
  framework_version: "2.11.0"
  os_version: "amzn2023"
  customer_type: "ec2"
  arch_type: "x86"
  device_type: "cpu"
  job_type: "training"

build:
  dockerfile: "docker/pytorch/2.11/Dockerfile.cpu"
  target: "runtime"
  python_version: "3.12"
  torch_version: "2.11.0"
  torchvision_version: "0.26.0"
  torchaudio_version: "2.11.0"
  max_jobs: "8"
  dlc_major_version: "1"
  dlc_minor_version: "0"

build_options:
  runner_fleet: "x86-build-runner"

tests:
  unit:
    workflow: "./.github/workflows/reusable-pytorch-unit-test.yml"

release:
  release: true
  prod_image: "pytorch:2.11-cpu-amzn2023"
  force_release: false
  public_registry: true
  private_registry: true
  enable_soci: true
  environment: "production"
