ARG TF_URL=https://storage.googleapis.com/tensorflow/versions/2.19.0/tensorflow-2.19.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

FROM nvidia/cuda:12.5.1-base-ubuntu22.04 AS base_image

ENV DEBIAN_FRONTEND=noninteractive \
    LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib"

RUN apt-get update \
 && apt-get upgrade -y \
 && apt-get autoremove -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

FROM base_image AS common

LABEL maintainer="Amazon AI"
LABEL dlc_major_version="1"

# Declaring ARG values
ARG TF_VERSION=2.19
ARG PYTHON=python3.12
ARG PIP=pip3
ARG PYTHON_VERSION=3.12.11
ARG EFA_VERSION=1.40.0
ARG OMPI_VERSION=4.1.8
ARG CUDA=12.5
ARG CUDA_DASH=12-5
ARG CUDNN=9.3.0.75

# To be passed to ec2 and sagemaker stages
ENV PYTHON=${PYTHON}
ENV PYTHON_VERSION=${PYTHON_VERSION}

ENV PIP=${PIP}

ENV OPEN_MPI_PATH=/opt/amazon/openmpi
ENV EFA_PATH=/opt/amazon/efa

# Prevent stopping by user interaction
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=UTF-8
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# Set environment variables for MKL
# For more about MKL with TensorFlow see:
# https://www.tensorflow.org/performance/performance_guide#tensorflow_with_intel%C2%AE_mkl_dnn
ENV KMP_AFFINITY=granularity=fine,compact,1,0
ENV KMP_BLOCKTIME=1
ENV KMP_SETTINGS=0
ENV RDMAV_FORK_SAFE=1

RUN apt-get update \
 && apt-get install -y --no-install-recommends --allow-unauthenticated --allow-downgrades  --allow-change-held-packages \
   build-essential \
   ca-certificates \
   cuda-cudart-dev-${CUDA_DASH} \
   cuda-command-line-tools-${CUDA_DASH} \
   cuda-nvcc-${CUDA_DASH} \
   cuda-cupti-${CUDA_DASH} \
   cuda-nvprune-${CUDA_DASH} \
   cuda-libraries-${CUDA_DASH} \
   cuda-nvrtc-${CUDA_DASH} \
   curl \
   emacs \
   git \
   hwloc \
   libcudnn9-cuda-12=${CUDNN}-1 \
   libcudnn9-dev-cuda-12=${CUDNN}-1 \
   libcufft-${CUDA_DASH} \
   libcufft-dev-${CUDA_DASH} \
   libcurand-${CUDA_DASH} \
   libcurand-dev-${CUDA_DASH} \
   libcusolver-${CUDA_DASH} \
   libcusolver-dev-${CUDA_DASH} \
   libcusparse-${CUDA_DASH} \
   libcusparse-dev-${CUDA_DASH} \
   libgomp1 \
   libfreetype6-dev \
   libhdf5-serial-dev \
   liblzma-dev \
   libpng-dev \
   libtemplate-perl \
   libtool \
   libzmq3-dev \
   openssh-client \
   openssh-server \
   openssl \
   protobuf-compiler \
   unzip \
   vim \
   wget \
   zlib1g-dev \
   # Install dependent library for OpenCV
   libgtk2.0-dev \
   jq \
 && apt-get update \
 && apt-get install -y --no-install-recommends --allow-unauthenticated --allow-change-held-packages \
   libcublas-dev-${CUDA_DASH} \
   libcublas-${CUDA_DASH} \
   libnccl2 \
   libnccl-dev \
 && rm -rf /var/lib/apt/lists/* \
 && apt-get clean \
 && mkdir -p /var/run/sshd

# Install EFA without AWS OPEN_MPI
RUN apt-get update \
  && mkdir /tmp/efa \
  && cd /tmp/efa \
  && curl -O https://s3-us-west-2.amazonaws.com/aws-efa-installer/aws-efa-installer-${EFA_VERSION}.tar.gz \
  && tar -xf aws-efa-installer-${EFA_VERSION}.tar.gz \
  && cd aws-efa-installer \
  && ./efa_installer.sh -y --skip-kmod -g \
  && rm -rf $OPEN_MPI_PATH \
  && rm -rf /tmp/efa \
  && rm -rf /tmp/aws-efa-installer-${EFA_VERSION}.tar.gz \
  && rm -rf /var/lib/apt/lists/*

# Install OpenMPI without libfabric support
RUN mkdir /tmp/openmpi \
 && cd /tmp/openmpi \
 && wget --quiet https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-${OMPI_VERSION}.tar.gz \
 && tar zxf openmpi-${OMPI_VERSION}.tar.gz \
 && cd openmpi-${OMPI_VERSION} \
 && ./configure --enable-orterun-prefix-by-default --prefix=$OPEN_MPI_PATH \
 && make -j $(nproc) all \
 && make install \
 && ldconfig \
 && rm -rf /tmp/openmpi

# Create a wrapper for OpenMPI to allow running as root by default
RUN mv $OPEN_MPI_PATH/bin/mpirun $OPEN_MPI_PATH/bin/mpirun.real \
 && echo '#!/bin/bash' > $OPEN_MPI_PATH/bin/mpirun \
 && echo 'mpirun.real --allow-run-as-root "$@"' >> $OPEN_MPI_PATH/bin/mpirun \
 && chmod a+x $OPEN_MPI_PATH/bin/mpirun

# Configure OpenMPI to run good defaults:
#   --bind-to none --map-by slot --mca btl_tcp_if_exclude lo,docker0
RUN echo "hwloc_base_binding_policy = none" >> $OPEN_MPI_PATH/etc/openmpi-mca-params.conf \
 && echo "rmaps_base_mapping_policy = slot" >> $OPEN_MPI_PATH/etc/openmpi-mca-params.conf

# Set default NCCL parameters
RUN echo NCCL_DEBUG=INFO >> /etc/nccl.conf
ENV LD_LIBRARY_PATH=$OPEN_MPI_PATH/lib/:$EFA_PATH/lib/:$LD_LIBRARY_PATH
# /usr/local/lib/libpython* needs to be accessible for dynamic linking
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
ENV PATH=$OPEN_MPI_PATH/bin/:$PATH
ENV PATH=$OPEN_MPI_PATH/nvidia/bin:$PATH

# SSH login fix. Otherwise user is kicked off after login
RUN mkdir -p /var/run/sshd \
   && sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

# Create SSH key.
RUN mkdir -p /root/.ssh/ \
   && ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa \
   && cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys \
   && printf "Host *\n  StrictHostKeyChecking no\n" >> /root/.ssh/config

WORKDIR /

RUN apt-get update \
   && apt-get install -y --no-install-recommends \
   libbz2-dev \
   libc6-dev \
   libcurl4-openssl-dev \
   libffi-dev \
   libgdbm-dev \
   libncursesw5-dev \
   libsqlite3-dev \
   libssl-dev \
   tk-dev \
   ffmpeg \
   libsm6 \
   libxext6 \
   # remove libsasl2-2 after Nvidia docker upstream fix CVE-2022-24407
   && rm -rf /var/lib/apt/lists/* \
   && apt-get clean

RUN wget https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz \
   && tar -xvf Python-$PYTHON_VERSION.tgz \
   && cd Python-$PYTHON_VERSION \
   && ./configure --enable-shared \
   && make -j $(nproc) \
   && make install \
   && rm -rf ../Python-$PYTHON_VERSION*

RUN ${PIP} --no-cache-dir install --upgrade \
   pip \
   setuptools \
   wheel

# Some TF tools expect a "python" binary
RUN ln -s $(which ${PYTHON}) /usr/local/bin/python \
   && ln -s $(which ${PIP}) /usr/bin/pip

RUN ${PIP} install --no-cache-dir -U \
   pybind11 \
   cmake \
   scipy \
   Pillow \
   python-dateutil \
   requests \
   "awscli<2" \
   mpi4py \
   h5py \
   absl-py \
   opencv-python \
   werkzeug \
   urllib3 \
   protobuf

# Allow OpenSSH to talk to containers without asking for confirmation
RUN cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new \
   && echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new \
   && mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config

# Add NGC vars
ENV TF_AUTOTUNE_THRESHOLD=2

ADD https://raw.githubusercontent.com/aws/deep-learning-containers/master/src/deep_learning_container.py /usr/local/bin/deep_learning_container.py
RUN chmod +x /usr/local/bin/deep_learning_container.py

COPY bash_telemetry.sh /usr/local/bin/bash_telemetry.sh
RUN chmod +x /usr/local/bin/bash_telemetry.sh
RUN echo 'source /usr/local/bin/bash_telemetry.sh' >> /etc/bash.bashrc

COPY dockerd_ec2_entrypoint.sh /usr/local/bin/dockerd_entrypoint.sh
RUN chmod +x /usr/local/bin/dockerd_entrypoint.sh

RUN curl https://aws-dlc-licenses.s3.amazonaws.com/tensorflow-${TF_VERSION}/license.txt -o /license.txt

########################################################
#  _____ ____ ____    ___
# | ____/ ___|___ \  |_ _|_ __ ___   __ _  __ _  ___
# |  _|| |     __) |  | || '_ ` _ \ / _` |/ _` |/ _ \
# | |__| |___ / __/   | || | | | | | (_| | (_| |  __/
# |_____\____|_____| |___|_| |_| |_|\__,_|\__, |\___|
#                                         |___/
#  ____           _
# |  _ \ ___  ___(_)_ __   ___
# | |_) / _ \/ __| | '_ \ / _ \
# |  _ <  __/ (__| | |_) |  __/
# |_| \_\___|\___|_| .__/ \___|
#                  |_|
########################################################

FROM common AS ec2

ARG TF_URL

RUN ${PIP} install --no-cache-dir -U \
   ${TF_URL} \
   "tensorflow-io==0.37.*" \
   tensorflow-datasets

RUN HOME_DIR=/root \
   && curl -o ${HOME_DIR}/oss_compliance.zip https://aws-dlinfra-utilities.s3.amazonaws.com/oss_compliance.zip \
   && unzip ${HOME_DIR}/oss_compliance.zip -d ${HOME_DIR}/ \
   && cp ${HOME_DIR}/oss_compliance/test/testOSSCompliance /usr/local/bin/testOSSCompliance \
   && chmod +x /usr/local/bin/testOSSCompliance \
   && chmod +x ${HOME_DIR}/oss_compliance/generate_oss_compliance.sh \
   && ${HOME_DIR}/oss_compliance/generate_oss_compliance.sh ${HOME_DIR} ${PYTHON} \
   && rm -rf ${HOME_DIR}/oss_compliance*

# remove tmp files
RUN rm -rf /tmp/*

ENTRYPOINT ["bash", "-m", "/usr/local/bin/dockerd_entrypoint.sh"]

CMD ["/bin/bash"]

#################################################################
#  ____                   __  __       _
# / ___|  __ _  __ _  ___|  \/  | __ _| | _____ _ __
# \___ \ / _` |/ _` |/ _ \ |\/| |/ _` | |/ / _ \ '__|
#  ___) | (_| | (_| |  __/ |  | | (_| |   <  __/ |
# |____/ \__,_|\__, |\___|_|  |_|\__,_|_|\_\___|_|
#              |___/
#  ___                              ____           _
# |_ _|_ __ ___   __ _  __ _  ___  |  _ \ ___  ___(_)_ __   ___
#  | || '_ ` _ \ / _` |/ _` |/ _ \ | |_) / _ \/ __| | '_ \ / _ \
#  | || | | | | | (_| | (_| |  __/ |  _ <  __/ (__| | |_) |  __/
# |___|_| |_| |_|\__,_|\__, |\___| |_| \_\___|\___|_| .__/ \___|
#                      |___/                        |_|
#################################################################

FROM common AS sagemaker

LABEL maintainer="Amazon AI"
LABEL dlc_major_version="1"

ARG TF_URL
ARG TF_VERSION

# sagemaker-specific environment variable
ENV SAGEMAKER_TRAINING_MODULE sagemaker_tensorflow_container.training:main

# https://github.com/yaml/pyyaml/issues/601
# PyYaml less than 6.0.1 failes to build with cython v3 and above.
# tf-models-official uses older versions, breaking the install.
# going to install the older pyyaml and cython to get tfd-models-official
# the sagemaker package will revert pyyaml back to 6 for its requirement
# and this is fine since sagemaker is more important than the models and
# the models still work on pyyaml 6 in this context.
# Need to install wheel before we can fix the pyyaml issue below
RUN pip install --no-cache-dir -U \
    wheel \
    "cython<3" \
    "pyyaml<6" \
    --no-build-isolation


# https://github.com/tensorflow/models/issues/9267
# tf-models does not respect existing installations of TF and always installs open source TF
RUN ${PIP} install \
    --default-timeout=300 \ 
    --retries 5 \
    \
    --default-timeout=300 \ 
    --retries 5 \
    --no-cache-dir -U \
    tf-models-official==${TF_VERISON}.1 \
    tensorflow-text==${TF_VERISON}.0 \
 && ${PIP} uninstall -y tensorflow tensorflow-gpu \
 && ${PIP} install --no-cache-dir -U \
    ${TF_URL} \
    "tensorflow-io==0.37.*" \
    tensorflow-datasets 
    
# Install rust and cargo
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN $PYTHON -m pip install --no-cache-dir -U \
    numba \
    bokeh \
    imageio \
    opencv-python \
    plotly \
    seaborn \
    shap

RUN $PYTHON -m pip install --no-cache-dir -U \
    sagemaker \
    sagemaker-experiments==0.* \
    sagemaker-tensorflow-training \
    sagemaker-training \
    y-py \
    sagemaker-studio-analytics-extension \
    "sparkmagic<1" \
    sagemaker-studio-sparkmagic-lib \
    smclarify

# install boost
# tensorflow is compiled with --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=1"
RUN wget https://sourceforge.net/projects/boost/files/boost/1.82.0/boost_1_82_0.tar.gz/download -O boost_1_82_0.tar.gz \
   && tar -xzf boost_1_82_0.tar.gz \
   && cd boost_1_82_0 \
   && ./bootstrap.sh \
   && ./b2 define=_GLIBCXX_USE_CXX11_ABI=1 threading=multi --prefix=/usr -j 64 cxxflags=-fPIC cflags=-fPIC install || true \
   && cd .. \
   && rm -rf boost_1_82_0.tar.gz \
   && rm -rf boost_1_82_0 \
   && cd /usr/include/boost

# Add NGC vars
ENV TF_AUTOTUNE_THRESHOLD=2

# Remove python kernel installed by sparkmagic
RUN /usr/local/bin/jupyter-kernelspec remove -f python3

# remove tmp files
RUN rm -rf /tmp/*

COPY start_cuda_compat.sh /usr/local/bin/start_cuda_compat.sh
COPY dockerd-entrypoint.py /usr/local/bin/dockerd-entrypoint.py
RUN chmod +x /usr/local/bin/start_cuda_compat.sh
RUN chmod +x /usr/local/bin/dockerd-entrypoint.py

RUN HOME_DIR=/root \
   && curl -o ${HOME_DIR}/oss_compliance.zip https://aws-dlinfra-utilities.s3.amazonaws.com/oss_compliance.zip \
   && unzip ${HOME_DIR}/oss_compliance.zip -d ${HOME_DIR}/ \
   && cp ${HOME_DIR}/oss_compliance/test/testOSSCompliance /usr/local/bin/testOSSCompliance \
   && chmod +x /usr/local/bin/testOSSCompliance \
   && chmod +x ${HOME_DIR}/oss_compliance/generate_oss_compliance.sh \
   && ${HOME_DIR}/oss_compliance/generate_oss_compliance.sh ${HOME_DIR} ${PYTHON} \
   && rm -rf ${HOME_DIR}/oss_compliance*

ENTRYPOINT ["python", "/usr/local/bin/dockerd-entrypoint.py"]

CMD ["/bin/bash"]
