image:
  name: "tensorflow-2.21-sagemaker-cpu"
  description: "TensorFlow 2.21 CPU training for SageMaker"

metadata:
  framework: "tensorflow"
  framework_version: "2.21.0"
  os_version: "amzn2023"
  customer_type: "sagemaker"
  arch_type: "x86"
  device_type: "cpu"
  job_type: "training"
  prod_image: "tensorflow-training:2.21-cpu-py312-amzn2023-sagemaker-v1"

build:
  dockerfile: "docker/tensorflow/2.21/Dockerfile.cpu"
  target: "sagemaker"
  python_version: "3.12"
  tf_version: "2.21.0"
  open_mpi_version: "4.1.8"
  dlc_major_version: "1"

release:
  release: true
  force_release: false
  public_registry: true
  private_registry: true
  enable_soci: true
  environment: "production"
