image:
  name: "tensorflow-2.21-sagemaker-cuda"
  description: "TensorFlow 2.21 CUDA training for SageMaker"

metadata:
  framework: "tensorflow"
  framework_version: "2.21.0"
  os_version: "amzn2023"
  customer_type: "sagemaker"
  arch_type: "x86"
  device_type: "gpu"
  job_type: "training"
  prod_image: "tensorflow-training:2.21-gpu-py312-cu129-amzn2023-sagemaker-v1"

build:
  dockerfile: "docker/tensorflow/2.21/Dockerfile.cuda"
  target: "sagemaker"
  python_version: "3.12"
  cuda_version: "12.9.1"
  tf_version: "2.21.0"
  open_mpi_version: "4.1.8"
  efa_version: "1.49.0"
  dlc_major_version: "1"
  dlc_minor_version: "0"

release:
  release: false
  force_release: false
  public_registry: false
  private_registry: false
  enable_soci: false
  environment: "production"
