image:
  name: "lambda-pytorch"
  description: "Lambda PyTorch GPU image with CUDA and Python"

metadata:
  framework: "lambda"
  framework_version: "12.9.1"
  os_version: "amzn2023"
  arch_type: "x86"
  device_type: "gpu"
  job_type: "general"
  container_type: "pytorch-cuda"
  prod_image: "lambda:pytorch-gpu-py313-cu129"

build:
  dockerfile: "docker/lambda/Dockerfile"
  target: "pytorch-py3"
  python_version: "3.13"
  cuda_version: "12.9.1"
  dlc_major_version: "1"
  dlc_minor_version: "0"

release:
  release: true
  force_release: false
  public_registry: false
  private_registry: true
  enable_soci: false
  environment: "gamma"
