#### First image: sha256:ab86c1a52886df4b3f16c320e2115e6da188ac6278ce43dbfd21f2a7b41176d0 ####
#### Patch contents for patch-1: sha256:23837fef09853c512277d2eb1c71397d972c80f50c64fa1576a8e9fcae194c31 ####
pip install cryptography==42.0.5 pillow==10.3.0 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bind9-host bind9-libs binutils-common binutils-x86-64-linux-gnu binutils bsdutils curl fdisk libbinutils libblkid-dev libblkid1 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libmount-dev libmount1 libsmartcols1 libssl-dev libssl1.1 libtiff5 libuuid1 libuv1 libxml2-utils libxml2 login mount openssl passwd util-linux uuid-dev vim-common vim-runtime vim xxd
#### Patch contents for patch-2: sha256:207af543d74038ae8af4988c8f378c4462c79ffd18db9f48ec3e87c79deeca0d ####
pip install cryptography==42.0.5 idna==3.7 pillow==10.3.0 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bind9-host bind9-libs binutils-common binutils-x86-64-linux-gnu binutils bsdutils curl fdisk libbinutils libblkid-dev libblkid1 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgnutls30 libmount-dev libmount1 libsmartcols1 libssl-dev libssl1.1 libtiff5 libuuid1 libuv1 libxml2-utils libxml2 login mount openssl passwd util-linux uuid-dev vim-common vim-runtime vim xxd
#### Patch contents for patch-3: sha256:7d01f883bc631c2b1650e95d1baba8d12701c9aab0a9c602babf5cfeb0e90049 ####
pip install cryptography==42.0.5 idna==3.7 pillow==10.3.0 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bind9-host bind9-libs binutils-common binutils-x86-64-linux-gnu binutils bsdutils curl fdisk libbinutils libblkid-dev libblkid1 libc6 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgnutls30 libmount-dev libmount1 libnghttp2-14 libsmartcols1 libssl-dev libssl1.1 libtiff5 libuuid1 libuv1 libxml2-utils libxml2 linux-libc-dev login mount openssl passwd util-linux uuid-dev vim-common vim-runtime vim xxd
#### Patch contents for patch-4: sha256:32b5c6316592a8aca49d80a5afd5505f3bd5752c2f048c1651a36dfe6030ec58 ####
pip install cryptography==42.0.7 idna==3.7 pillow==10.3.0 tqdm==4.66.4 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bind9-host bind9-libs binutils-common binutils-x86-64-linux-gnu binutils bsdutils curl fdisk libbinutils libblkid-dev libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgnutls30 libmount-dev libmount1 libnghttp2-14 libsmartcols1 libssl-dev libssl1.1 libtiff5 libuuid1 libuv1 libxml2-utils libxml2 linux-libc-dev login mount openssl passwd util-linux uuid-dev vim-common vim-runtime vim xxd
#### Patch contents for patch-5: sha256:330ea70eb1d1184dea18a7cf15bbd5028152f019d7a3cf037da55babb7b61d7b ####
pip install cryptography==42.0.7 idna==3.7 pillow==10.3.0 tqdm==4.66.4 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bind9-host bind9-libs binutils-common binutils-x86-64-linux-gnu binutils bsdutils curl fdisk libbinutils libblkid-dev libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libglib2.0-0 libglib2.0-bin libgnutls30 libmount-dev libmount1 libnghttp2-14 libsmartcols1 libssl-dev libssl1.1 libtiff5 libuuid1 libuv1 libxml2-utils libxml2 linux-libc-dev login mount openssl passwd util-linux uuid-dev vim-common vim-runtime vim xxd
#### Patch contents for patch-6: sha256:3516b7d2d0093d600715f7a8fd6189b08b4cb972239169286875f202661b745f ####
pip install cryptography==42.0.7 idna==3.7 pillow==10.3.0 tqdm==4.66.4 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bind9-host bind9-libs binutils-common binutils-x86-64-linux-gnu binutils bsdutils curl fdisk libbinutils libblkid-dev libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libglib2.0-0 libglib2.0-bin libgnutls30 libmount-dev libmount1 libnghttp2-14 libsmartcols1 libssl-dev libssl1.1 libtiff5 libuuid1 libuv1 libxml2-utils libxml2 linux-libc-dev login mount openssl passwd util-linux uuid-dev vim-common vim-runtime vim xxd
#### Patch contents for patch-7: sha256:136a9e464dddaab46e2a753e8883aa7f9a13ea86d7b7d7da0c95150763ebb35f ####
pip install cryptography==42.0.7 idna==3.7 pillow==10.3.0 sagemaker==2.221.0 tqdm==4.66.4 werkzeug==3.0.3 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bind9-host bind9-libs binutils-common binutils-x86-64-linux-gnu binutils bsdutils curl fdisk libbinutils libblkid-dev libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libglib2.0-0 libglib2.0-bin libgnutls30 libmount-dev libmount1 libnghttp2-14 libsmartcols1 libssl-dev libssl1.1 libtiff5 libuuid1 libuv1 libxml2-utils libxml2 linux-libc-dev login mount openssl passwd util-linux uuid-dev vim-common vim-runtime vim xxd
#### Current Patch contents ####
pip install cryptography==42.0.7 idna==3.7 pillow==10.3.0 requests==2.32.2 sagemaker==2.221.1 tqdm==4.66.4 werkzeug==3.0.3 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bind9-host bind9-libs binutils-common binutils-x86-64-linux-gnu binutils bsdutils curl fdisk libbinutils libblkid-dev libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libglib2.0-0 libglib2.0-bin libgnutls30 libmount-dev libmount1 libnghttp2-14 libsmartcols1 libssl-dev libssl1.1 libtiff5 libuuid1 libuv1 libxml2-utils libxml2 linux-libc-dev login mount openssl passwd util-linux uuid-dev vim-common vim-runtime vim xxd
