ARG PYTHON_VERSION=3.10.8

FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:2.0.1-cpu-py310-ubuntu20.04-sagemaker

# PYTORCH_SKIP_CUDNN_COMPATIBILITY_CHECK - see https://github.com/autogluon/autogluon/issues/2534
# ENV PYTORCH_SKIP_CUDNN_COMPATIBILITY_CHECK=1

LABEL maintainer="Amazon AI"
LABEL dlc_major_version="1"

# Install dependencies
RUN apt-get update \
 && apt-get -y upgrade \
 && apt-get install -y --no-install-recommends \
 && apt-get autoremove -y \
 # Install tesseract-ocr to support automm document classification
 && apt-get install tesseract-ocr -y \
 # Install rsync to support ray distributed training
 && apt-get install rsync -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

ARG AUTOGLUON_VERSION=1.0.0

# Upgrading pip and installing/updating Python dependencies
# Comments are added to explain the reason behind each update
RUN pip install --no-cache-dir -U --trusted-host pypi.org --trusted-host files.pythonhosted.org pip \
 && pip install --no-cache-dir -U setuptools wheel \
 && pip install --no-cache-dir -U numpy numba \
 && pip install --no-cache-dir -U autogluon==${AUTOGLUON_VERSION} \
 && mim install -q mmcv \
 && pip install --no-cache-dir -U mmdet>=3.0.0 \
 && pip install --no-cache-dir -U "pymupdf" \
 && pip install --no-cache-dir -U "mmengine" \
# Update requests to a secure version that fixes CVE-2023-32681
 && pip install --no-cache-dir -U requests>=2.31.0 \
#  && pip install --no-cache-dir -U pyOpenSSL>=23.2.0 \
# Update ray to a secure version that fixes CVE-2023-6019, CVE-2023-6020, CVE-2023-6021, and CVE-2023-48023
 && pip install --no-cache-dir -U ray>=2.8.1 \
 # Update transformers to secure versions that fixes CVE-2023-7018
 && pip install --no-cache-dir -U transformers>=4.36.0 \
 && pip install --no-cache-dir -U setuptools>=65.5.1 \
 && pip install --no-cache-dir -U cryptography>=41.0.7 \
 # Update pillow to a secure version that fixes CVE-2023-50447
 && pip install --no-cache-dir -U pillow>=10.2.0 \
  # Update Jinja2 to a secure version that fixes vulnerability id 64227
 && pip install --no-cache-dir -U Jinja2>=3.1.3 \
 # Update aiohttp to a secure version that fixes vulnerability id 64642
 && pip install --no-cache-dir -U aiohttp>=3.9.2 \
 # update paramiko to a secure version that fixes vulnerability id 65193
 && pip install --no-cache-dir -U --no-cache-dir -U paramiko>=3.4.0


RUN HOME_DIR=/root \
 && curl -o ${HOME_DIR}/oss_compliance.zip https://aws-dlinfra-utilities.s3.amazonaws.com/oss_compliance.zip \
 && unzip ${HOME_DIR}/oss_compliance.zip -d ${HOME_DIR}/ \
 && cp ${HOME_DIR}/oss_compliance/test/testOSSCompliance /usr/local/bin/testOSSCompliance \
 && chmod +x /usr/local/bin/testOSSCompliance \
 && chmod +x ${HOME_DIR}/oss_compliance/generate_oss_compliance.sh \
 && ${HOME_DIR}/oss_compliance/generate_oss_compliance.sh ${HOME_DIR} python \
 && rm -rf ${HOME_DIR}/oss_compliance*

RUN curl -o /licenses-autogluon.txt https://autogluon.s3.us-west-2.amazonaws.com/licenses/THIRD-PARTY-LICENSES.txt

CMD ["/bin/bash"]
