FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference:1.13.1-gpu-py39-cu117-ubuntu20.04-sagemaker as sagemaker
ARG SGM_VERSION=0.0.1

# Install Stability Generative Models
RUN cd /tmp \
 && git clone https://github.com/stability-ai/generative-models -b palp/model-tests \
 && cd generative-models \
 && pip install -r requirements_pt13.txt \
 && pip install . \
 && rm -rf /tmp/generative-models