#!/usr/bin/env bash
# check-upstream-releases.sh — Main logic for the upstream release tracker.
# Called by the GitHub Actions workflow check-upstream-releases.yml.
#
# Environment variables (set by the workflow):
#   GITHUB_TOKEN       — GitHub token required for PR creation
#   SLACK_WEBHOOK_URL  — Slack Workflow webhook URL (optional)
#   DRY_RUN            — "true" to skip branch/PR creation (optional)
#   FRAMEWORK_FILTER   — Specific framework to check (optional)

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/utils.sh"
source "${SCRIPT_DIR}/update-configs.sh"

TRACKER_FILE=".github/config/autocurrency-tracker.yml"
DRY_RUN="${DRY_RUN:-false}"
FRAMEWORK_FILTER="${FRAMEWORK_FILTER:-}"

###############################################################################
# build_pr_body()
#   Constructs the PR description markdown.
#
#   Arguments:
#     $1 — framework
#     $2 — new_version
#     $3 — current_version
#     $4 — github_repo (owner/repo)
#     $5 — tag_name
#     $6 — html_url (release page URL)
#     $7 — changed_files_list (newline-separated file paths)
###############################################################################
build_pr_body() {
  local framework="$1"
  local new_version="$2"
  local current_version="$3"
  local github_repo="$4"
  local tag_name="$5"
  local html_url="$6"
  local changed_files_list="$7"

  # Build changed files list as markdown bullets
  local changed_files_md=""
  while IFS= read -r file; do
    if [[ -n "${file}" ]]; then
      changed_files_md="${changed_files_md}- \`${file}\`
"
    fi
  done <<< "${changed_files_list}"

  cat <<PRBODY
## Auto-Update: ${framework} ${new_version}

**Upstream Release**: [${github_repo} ${tag_name}](${html_url})
**Previous Version**: ${current_version}
**New Version**: ${new_version}

### Changed Files
${changed_files_md}

### What to Review
- Verify the upstream base image exists on Docker Hub
- Review auto-detected CUDA/Python/OS version updates if present
- Confirm no breaking changes were made in the upstream release notes

### Auto-generated by
- [check-upstream-releases.yml](https://github.com/aws/deep-learning-containers/blob/main/.github/workflows/check-upstream-releases.yml) — PR creation and config updates
- [detect-versions.yml](https://github.com/aws/deep-learning-containers/blob/main/.github/workflows/detect-versions.yml) — CUDA/Python/OS version detection
PRBODY
}

###############################################################################
# Main logic
###############################################################################

# Validate tracker registry exists
if [[ ! -f "${TRACKER_FILE}" ]]; then
  echo "::error::Tracker registry not found: ${TRACKER_FILE}"
  exit 1
fi

# Extract framework keys
FRAMEWORKS=$(yq eval '.frameworks | keys | .[]' "${TRACKER_FILE}")

if [[ -z "${FRAMEWORKS}" ]]; then
  echo "::error::No frameworks defined in ${TRACKER_FILE}"
  exit 1
fi

# Apply framework filter if provided
if [[ -n "${FRAMEWORK_FILTER}" ]]; then
  if ! echo "${FRAMEWORKS}" | grep -qx "${FRAMEWORK_FILTER}"; then
    echo "::error::Framework '${FRAMEWORK_FILTER}' not found in tracker registry. Available: $(echo ${FRAMEWORKS} | tr '\n' ', ')"
    exit 1
  fi
  FRAMEWORKS="${FRAMEWORK_FILTER}"
fi

echo "Frameworks to check: $(echo ${FRAMEWORKS} | tr '\n' ' ')"

# Per-framework tracking
declare -A FRAMEWORK_STATUS
TOTAL=0
FAILED=0

# Process each framework
for framework in ${FRAMEWORKS}; do
  TOTAL=$((TOTAL + 1))
  echo ""
  echo "============================================================"
  echo "Processing: ${framework}"
  echo "============================================================"

  # Wrap each framework in error handling for failure isolation
  set +e
  (
    set -euo pipefail

    # -----------------------------------------------------------------
    # Read framework config from autocurrency-tracker.yml
    # -----------------------------------------------------------------
    github_repo=$(yq eval ".frameworks.${framework}.github_repo" "${TRACKER_FILE}")
    tag_prefix=$(yq eval ".frameworks.${framework}.tag_prefix // \"v\"" "${TRACKER_FILE}")

    if [[ -z "${github_repo}" || "${github_repo}" == "null" ]]; then
      echo "::error::Framework '${framework}' missing required field 'github_repo'"
      exit 1
    fi

    # -----------------------------------------------------------------
    # Call GitHub Releases API for latest release
    # -----------------------------------------------------------------
    echo "Checking ${github_repo} for latest release..."

    api_response=$(curl -s -w "\n%{http_code}" \
      -H "Accept: application/vnd.github+json" \
      "https://api.github.com/repos/${github_repo}/releases/latest")

    http_code=$(echo "${api_response}" | tail -1)
    api_body=$(echo "${api_response}" | sed '$d')

    # Handle API errors
    if [[ "${http_code}" == "404" ]]; then
      echo "::warning::${framework}: No releases found for ${github_repo} (HTTP 404). Skipping."
      exit 0
    fi

    if [[ "${http_code}" == "403" ]]; then
      rate_remaining=$(curl -sI \
        "https://api.github.com/rate_limit" 2>/dev/null \
        | grep -i "x-ratelimit-remaining" || echo "unknown")
      echo "::error::${framework}: GitHub API rate limit hit (HTTP 403). Rate-limit info: ${rate_remaining}"
      exit 1
    fi

    if [[ "${http_code}" != "200" ]]; then
      echo "::warning::${framework}: GitHub API returned HTTP ${http_code}. Skipping."
      exit 0
    fi

    # -----------------------------------------------------------------
    # Check prerelease and draft fields
    # -----------------------------------------------------------------
    is_prerelease=$(echo "${api_body}" | jq -r '.prerelease')
    is_draft=$(echo "${api_body}" | jq -r '.draft')

    if [[ "${is_prerelease}" == "true" || "${is_draft}" == "true" ]]; then
      echo "${framework}: Latest release is prerelease=${is_prerelease} draft=${is_draft}. Skipping."
      exit 0
    fi

    # -----------------------------------------------------------------
    # Extract release info
    # -----------------------------------------------------------------
    tag_name=$(echo "${api_body}" | jq -r '.tag_name')
    html_url=$(echo "${api_body}" | jq -r '.html_url')

    echo "${framework}: Latest release tag: ${tag_name}"

    # -----------------------------------------------------------------
    # Strip tag prefix and check for RC
    # -----------------------------------------------------------------
    latest_version=$(strip_tag_prefix "${tag_name}" "${tag_prefix}")
    echo "${framework}: Stripped version: ${latest_version}"

    if is_rc_version "${latest_version}"; then
      echo "${framework}: Version ${latest_version} is an RC release. Skipping."
      exit 0
    fi

    # -----------------------------------------------------------------
    # Read current version from first config file
    # -----------------------------------------------------------------
    first_config=$(yq eval ".frameworks.${framework}.config_files[0].path" "${TRACKER_FILE}")

    if [[ -z "${first_config}" || "${first_config}" == "null" ]]; then
      echo "::error::${framework}: No config_files defined"
      exit 1
    fi

    if [[ ! -f "${first_config}" ]]; then
      echo "::error::${framework}: Config file not found: ${first_config}"
      exit 1
    fi

    current_version=$(get_current_version "${first_config}")
    echo "${framework}: Current version: ${current_version}, Upstream version: ${latest_version}"

    # -----------------------------------------------------------------
    # Compare versions
    # -----------------------------------------------------------------
    if ! is_newer_version "${latest_version}" "${current_version}"; then
      echo "${framework}: Current version ${current_version} is up to date. No update needed."
      exit 0
    fi

    echo "${framework}: New version detected! ${current_version} -> ${latest_version}"

    # -----------------------------------------------------------------
    # Check if branch already exists (idempotency guard)
    # -----------------------------------------------------------------
    branch_name="auto-update/${framework}-${latest_version}"

    if git ls-remote --exit-code --heads origin "${branch_name}" &>/dev/null; then
      echo "${framework}: Branch '${branch_name}' already exists. PR likely in progress. Skipping."
      exit 0
    fi

    # -----------------------------------------------------------------
    # Dry-run mode: log and skip
    # -----------------------------------------------------------------
    if [[ "${DRY_RUN}" == "true" ]]; then
      echo "[DRY RUN] ${framework}: Would create PR to update ${current_version} -> ${latest_version}"
      echo "[DRY RUN] ${framework}: Branch would be: ${branch_name}"
      exit 0
    fi

    # -----------------------------------------------------------------
    # Update config files
    # -----------------------------------------------------------------
    config_entries_json=$(yq eval -o=json ".frameworks.${framework}.config_files" "${TRACKER_FILE}")
    updated_files=$(update_config_files "${framework}" "${latest_version}" "${config_entries_json}")
    echo "${framework}: Updated config files:"
    echo "${updated_files}"

    # -----------------------------------------------------------------
    # Update Dockerfiles if configured
    # -----------------------------------------------------------------
    has_dockerfiles=$(yq eval ".frameworks.${framework}.dockerfiles // null" "${TRACKER_FILE}")
    if [[ "${has_dockerfiles}" != "null" ]]; then
      dockerfile_entries_json=$(yq eval -o=json ".frameworks.${framework}.dockerfiles" "${TRACKER_FILE}")
      dockerfile_updates=$(update_dockerfiles "${latest_version}" "${dockerfile_entries_json}")
      if [[ -n "${dockerfile_updates}" ]]; then
        updated_files="${updated_files}"$'\n'"${dockerfile_updates}"
        echo "${framework}: Updated Dockerfiles:"
        echo "${dockerfile_updates}"
      fi
    fi

    # -----------------------------------------------------------------
    # Rename test setup script if configured
    # -----------------------------------------------------------------
    has_test_setup=$(yq eval ".frameworks.${framework}.test_setup_script // null" "${TRACKER_FILE}")
    if [[ "${has_test_setup}" != "null" ]]; then
      test_setup_json=$(yq eval -o=json ".frameworks.${framework}.test_setup_script" "${TRACKER_FILE}")
      echo "${framework}: Renaming test setup script..."
      script_updates=$(rename_test_setup_script "${current_version}" "${latest_version}" "${test_setup_json}") || {
        echo "::warning::${framework}: Failed to rename test setup script. Continuing without rename."
        script_updates=""
      }
      if [[ -n "${script_updates}" ]]; then
        updated_files="${updated_files}"$'\n'"${script_updates}"
        echo "${framework}: Renamed test setup script:"
        echo "${script_updates}"
      fi
    fi

    # -----------------------------------------------------------------
    # Create branch, commit, push, and create PR
    # -----------------------------------------------------------------
    echo "${framework}: Creating branch ${branch_name}..."
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git checkout -b "${branch_name}"

    # Stage all updated files
    echo "${updated_files}" | while IFS= read -r file; do
      if [[ -n "${file}" ]]; then
        git add "${file}"
      fi
    done

    git commit -m "[Auto-Update] ${framework} ${latest_version}"
    git push origin "${branch_name}"

    # Build PR description
    pr_body=$(build_pr_body \
      "${framework}" \
      "${latest_version}" \
      "${current_version}" \
      "${github_repo}" \
      "${tag_name}" \
      "${html_url}" \
      "${updated_files}")

    # Create PR
    echo "${framework}: Creating pull request..."
    pr_url=$(gh pr create \
      --base main \
      --head "${branch_name}" \
      --title "[Auto-Update] ${framework} ${latest_version}" \
      --label "auto-update" \
      --body "${pr_body}")

    echo "${framework}: PR created: ${pr_url}"

    # -----------------------------------------------------------------
    # Send Slack notification if enabled
    # -----------------------------------------------------------------
    slack_enabled=$(yq eval '.notifications.slack.enabled // false' "${TRACKER_FILE}")
    if [[ "${slack_enabled}" == "true" ]]; then
      send_slack_notification \
        "${SLACK_WEBHOOK_URL:-}" \
        "${framework}" \
        "${latest_version}" \
        "${pr_url}" || true
    fi

    echo "FRAMEWORK_RESULT:success"
  )
  framework_exit=$?
  set -e

  # Track per-framework results
  if [[ ${framework_exit} -eq 0 ]]; then
    FRAMEWORK_STATUS["${framework}"]="success"
  else
    FRAMEWORK_STATUS["${framework}"]="failed"
    FAILED=$((FAILED + 1))
    echo "::warning::${framework}: Processing failed with exit code ${framework_exit}"
  fi

  # Return to main branch for next framework iteration
  git checkout main 2>/dev/null || true
done

# -------------------------------------------------------------------
# Output summary
# -------------------------------------------------------------------
echo ""
echo "============================================================"
echo "Summary"
echo "============================================================"
echo "Total frameworks processed: ${TOTAL}"
echo "Failed: ${FAILED}"
echo ""

for fw in "${!FRAMEWORK_STATUS[@]}"; do
  echo "  ${fw}: ${FRAMEWORK_STATUS[${fw}]}"
done

# Fail the workflow if at least one framework failed
if [[ ${FAILED} -gt 0 ]]; then
  echo "::error::${FAILED}/${TOTAL} framework(s) failed processing"
  exit 1
fi
