# Expecting base image to be the image built by ../{cuda_version}/Dockerfile.gpu ec2 target
ARG BASE_IMAGE=""

FROM $BASE_IMAGE

# Add any script or repo as required
RUN git clone -b v0.1 https://github.com/aws-samples/deep-learning-models
WORKDIR "/"
