ARG RELEASED_IMAGE=""

FROM $RELEASED_IMAGE

ARG RELEASED_IMAGE_SHA=""

COPY patching-info /opt/aws/dlc/patching-info
COPY miscellaneous_scripts /opt/aws/dlc/miscellaneous_scripts

RUN chmod +x /opt/aws/dlc/miscellaneous_scripts/dockerfile_patch_script.sh && \
    /opt/aws/dlc/miscellaneous_scripts/dockerfile_patch_script.sh $RELEASED_IMAGE_SHA
