ARG RELEASED_IMAGE=""

FROM $RELEASED_IMAGE

ARG RELEASED_IMAGE_SHA=""

# If patch-details-archive is not present, create it for the first time and add first_image_sha.txt
RUN if !(( $([ -d /opt/aws/dlc/patch-details-archive ]) )) ; then \
        mkdir /opt/aws/dlc/patch-details-archive && \
        echo $RELEASED_IMAGE_SHA >> /opt/aws/dlc/patch-details-archive/first_image_sha.txt ; \
    fi

# If patch-details is present, move it to patch-details-archive and add image_sha to the folder
RUN if [ -d /opt/aws/dlc/patch-details ] ; then \
        existing_file_count=$(ls -l /opt/aws/dlc/patch-details-archive | wc -l) && \
        reduce_count_value=1 && \
        patch_count=$((existing_file_count-reduce_count_value)) && \
        mv /opt/aws/dlc/patch-details /opt/aws/dlc/patch-details-archive/patch-details-$patch_count && \
        echo $RELEASED_IMAGE_SHA >> /opt/aws/dlc/patch-details-archive/patch-details-$patch_count/image_sha.txt ; \
    fi

COPY patch-details /opt/aws/dlc/patch-details
COPY miscellaneous_scripts /opt/aws/dlc/miscellaneous_scripts
RUN chmod +x /opt/aws/dlc/patch-details/install_script_language.sh && /opt/aws/dlc/patch-details/install_script_language.sh
RUN chmod +x /opt/aws/dlc/patch-details/install_script_os.sh && /opt/aws/dlc/patch-details/install_script_os.sh
RUN python /opt/aws/dlc/miscellaneous_scripts/derive_history.py
RUN python /opt/aws/dlc/miscellaneous_scripts/extract_apt_patch_data.py --save-result-path /opt/aws/dlc/patch-details/os_summary.json --mode_type modify
RUN rm -r /opt/aws/dlc/miscellaneous_scripts
