#### First image: sha256:3b42a750915b9c04bbc48fa05801cee087ce36fce4a1a9c3ee54f92af63fe617 ####
#### Patch contents for patch-1: sha256:661752b8da5f7fa0b6c6ec90dfca2a0080fcbbee460df986e9055978da56a36b ####
echo N/A
apt-get update && apt-get install -y --only-upgrade libtiff5
#### Patch contents for patch-2: sha256:bd6987015da36f8094b34aec068f0263fa5d4257a3d9b02b31569c8d93c45b4b ####
echo N/A
apt-get update && apt-get install -y --only-upgrade libtiff5 linux-libc-dev
#### Patch contents for patch-3: sha256:96185448c52b50d37a60bd333123e85380448e078803f3b32806101d881f16ae ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libtiff5 linux-libc-dev
#### Patch contents for patch-4: sha256:e57a490957b116687aec0154e3c5cdf0305feaa216f2e746eccc611d0b4c2b45 ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 libtiff5 linux-libc-dev
#### Patch contents for patch-5: sha256:f88b9782dba85b1f0143763dae8dc4b93852cd7fab47b553d5cc8842db4445eb ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 libtiff5 linux-libc-dev wget
#### Patch contents for patch-6: sha256:87ffd2c212acddc0d29a2802b8b73a0db850774bd6abc36edac59b2c87a4fe5b ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 libtiff5 linux-libc-dev wget
#### Patch contents for patch-7: sha256:f1857de42485ae575b32408adb44c32c7a31e92e6d8cabf2a37fe81358110e27 ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 libtiff5 linux-libc-dev wget
#### Current Patch contents ####
pip install certifi==2024.7.4 urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 libtiff5 linux-libc-dev wget
