#### First image: sha256:82fe8622a8d5a3ac6aa6f6325236c10d6a0c49f538ca68159482b8d63d1b9c81 ####
#### Patch contents for patch-1: sha256:b5743655a438287edb3771fd3f2cb0f6cda31d541cfdf8300c4c0e9d054690a3 ####
pip install idna==3.7 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc6 libfdisk1 libgnutls30 libmount1 libnss3 libsmartcols1 libuuid1 mount util-linux
#### Patch contents for patch-2: sha256:6c32970d3951c252cb834cf95f49a47d81c9cb7f8b7cee71cd46b2ff5468ef6a ####
pip install idna==3.7 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc6 libfdisk1 libgnutls30 libmount1 libnghttp2-14 libnss3 libsmartcols1 libuuid1 mount util-linux
#### Patch contents for patch-3: sha256:24ca7a71002511c619104c771ec2fb90d2f617c20d6fa5446e36691c0f42f162 ####
pip install idna==3.7 tqdm==4.66.4 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libgnutls30 libmount1 libnghttp2-14 libnss3 libsmartcols1 libuuid1 linux-libc-dev mount util-linux
#### Patch contents for patch-4: sha256:cb3e161dd765d28eac9aeb53425cc9b0b5d0637b969c78250dc95040892df5ae ####
pip install idna==3.7 tqdm==4.66.4 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libnss3 libsmartcols1 libuuid1 linux-libc-dev mount util-linux
#### Current Patch contents ####
pip install idna==3.7 tqdm==4.66.4 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libnss3 libsmartcols1 libuuid1 linux-libc-dev mount util-linux
