#### First image: sha256:eff8585d6c4a0ddc16ae690854896fc1f1906e4c07323851d34d4d3d00f5904f ####
#### Patch contents for patch-1: sha256:37e5716563dfa11cadeb2ed4b662744cbcb9bddad24d5efd9c84c121da5d9ccd ####
pip install idna==3.7 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc6 libfdisk1 libgnutls30 libmount1 libnss3 libsmartcols1 libuuid1 mount util-linux
#### Patch contents for patch-2: sha256:73aa49e28e544014d43d1df1dd72bf0515071c86a1b08d3e0edc5c6e16b07cd7 ####
pip install idna==3.7 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc6 libfdisk1 libgnutls30 libmount1 libnghttp2-14 libnss3 libsmartcols1 libuuid1 mount util-linux
#### Patch contents for patch-3: sha256:de910a3ee7887aa1f3e98012b3d4f3c79e6fbb27d7900c8c9b3119844e7b5c9d ####
pip install idna==3.7 tqdm==4.66.4 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libgnutls30 libmount1 libnghttp2-14 libnss3 libsmartcols1 libuuid1 linux-libc-dev mount util-linux
#### Patch contents for patch-4: sha256:989150d30c9d9838786cb4fdb2c86a52e8ba6407019dc3f5ccbcdd893bb194db ####
pip install idna==3.7 tqdm==4.66.4 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libnss3 libsmartcols1 libuuid1 linux-libc-dev mount util-linux
#### Current Patch contents ####
pip install idna==3.7 tqdm==4.66.4 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libnss3 libsmartcols1 libuuid1 linux-libc-dev mount util-linux
