image:
  name: "vllm-ec2-amzn2023"
  description: "vLLM for EC2 instances (AL2023, built from source)"

metadata:
  framework: "vllm_server"
  framework_version: "0.24.0"
  os_version: "amzn2023"
  customer_type: "ec2"
  arch_type: "x86"
  device_type: "gpu"
  job_type: "general"
  prod_image: "vllm:server-cuda-v2"

build:
  dockerfile: "docker/vllm/Dockerfile.amzn2023"
  target: "vllm-ec2-amzn2023"
  python_version: "3.12"
  cuda_version: "13.0.2"
  vllm_ref: "d223c900d85224c02f2162ee2c757a769e99f519"
  flashinfer_version: "0.6.12"
  deepep_commit_hash: "73b6ea4"
  dlc_major_version: "2"
  dlc_minor_version: "2"
  use_sccache: "true"

release:
  release: true
  force_release: false
  public_registry: true
  private_registry: true
  enable_soci: true
  environment: "production"
