  account_id: '&ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>'
  region: '&REGION <set-$REGION-in-environment>'
  framework: '&FRAMEWORK tensorflow'
  version: '&VERSION 1.2.3'
  short_version: '&SHORT_VERSION 1.2'

  repository_info:
    inference_repository: &INFERENCE_REPOSITORY
        image_type: '&INFERENCE_IMAGE_TYPE inference'
        root: '!join [ *FRAMEWORK, "/", *INFERENCE_IMAGE_TYPE ]'
        repository_name: '&REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *INFERENCE_IMAGE_TYPE, "-", eia]'
        repository: '&REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]'

  context:
    inference_context: &INFERENCE_CONTEXT
      sagemaker_package_name:
        source: docker/build_artifacts/sagemaker
        target: sagemaker
      init:
        source: docker/build_artifacts/__init__.py
        target: __init__.py
      dockerd-entrypoint:
        source: docker/build_artifacts/dockerd-entrypoint.py
        target: dockerd-entrypoint.py

  images:
    BuildEIATFInferencePy36DockerImage:
      '<<': *INFERENCE_REPOSITORY
      build: '&TENSORFLOW_CPU_INFERENCE_PY3 false'
      image_size_baseline: 1000
      device_type: '&DEVICE_TYPE cpu'
      python_version: '&DOCKER_PYTHON_VERSION py3'
      tag_python_version: '&TAG_PYTHON_VERSION py36'
      os_version: '&OS_VERSION ubuntu18.04'
      tag: '!join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION ]'
      docker_file: '!join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., eia ]'
      context:
        <<: *INFERENCE_CONTEXT
