#### First image: sha256:3093fc8670f953e149f550cff3fd13199ee3a7b4a17d0f360f98bc02151524ec ####
#### Patch contents for patch-1: sha256:d9f54f527c6382712f3ce17c9f91e35fb531e6a2ac6a9185472442d7d2831fc4 ####
pip install idna==3.7 pillow==10.3.0 tqdm==4.66.4 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk less libblkid-dev libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgnutls30 libmount-dev libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev vim-common vim-runtime vim xxd
#### Patch contents for patch-2: sha256:86cd0d8b2e20b65dbf955b0e88072e71b5a0665bb67670e6316d55586b4ddb94 ####
pip install idna==3.7 pillow==10.3.0 tqdm==4.66.4 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk less libblkid-dev libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgnutls30 libmount-dev libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev vim-common vim-runtime vim xxd
#### Patch contents for patch-3: sha256:756b70f143776d2935b49b1ff6333e9c5faa73ccf11fa603afd5162dab445e65 ####
pip install idna==3.7 pillow==10.3.0 requests==2.32.2 sagemaker==2.221.0 tqdm==4.66.4 werkzeug==3.0.3 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk less libblkid-dev libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libglib2.0-0 libglib2.0-bin libgnutls30 libmount-dev libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev vim-common vim-runtime vim xxd
#### Patch contents for patch-4: sha256:82b431359187299607dc09d25083bbae680af98feb25b7ca31c33452fc9fe6db ####
pip install anyio==4.4.0 idna==3.7 pillow==10.3.0 requests==2.32.2 sagemaker==2.221.1 tqdm==4.66.4 werkzeug==3.0.3 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk less libblkid-dev libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libglib2.0-0 libglib2.0-bin libgnutls30 libmount-dev libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev vim-common vim-runtime vim xxd
#### Patch contents for patch-5: sha256:c93a4ba356cec180d9b791aa81765101eb2801eb0bfd808936f157065208fd42 ####
pip install anyio==4.4.0 idna==3.7 jinja2==3.1.4 pillow==10.3.0 requests==2.32.3 sagemaker==2.221.1 tqdm==4.66.4 werkzeug==3.0.3
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git less libblkid-dev libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libglib2.0-0 libglib2.0-bin libgnutls30 libmount-dev libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev vim-common vim-runtime vim xxd
#### Patch contents for patch-6: sha256:38a6cdef2e7e42c7d2afb20bb7dcde4f4145534f3313d63029db5f28e2b89f2e ####
pip install anyio==4.4.0 idna==3.7 jinja2==3.1.4 pillow==10.3.0 requests==2.32.3 sagemaker==2.222.0 tqdm==4.66.4 werkzeug==3.0.3
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git less libblkid-dev libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libglib2.0-bin libgnutls30 libmount-dev libmount1 libnghttp2-14 libsmartcols1 libuuid1 libvpx6 linux-libc-dev mount util-linux uuid-dev vim-common vim-runtime vim xxd
#### Patch contents for patch-7: sha256:a2fad50101354491fc9fd77dc2bdd00bbc7c4faef18a5d66ed8599896c24c5b0 ####
pip install anyio==4.4.0 idna==3.7 jinja2==3.1.4 pillow==10.3.0 requests==2.32.3 sagemaker==2.223.0 tqdm==4.66.4 werkzeug==3.0.3
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git less libblkid-dev libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libglib2.0-bin libgnutls30 libmount-dev libmount1 libnghttp2-14 libsmartcols1 libtiff5 libuuid1 libvpx6 linux-libc-dev mount util-linux uuid-dev vim-common vim-runtime vim xxd
#### Patch contents for patch-8: sha256:4882713e2f9f6cf72ebf168a04748391df19a052cefe3c245b5f46a0215c3e31 ####
pip install anyio==4.4.0 awscli==1.33.13 botocore==1.34.131 cryptography==42.0.8 idna==3.7 jinja2==3.1.4 jupyter-server==2.14.1 pillow==10.3.0 requests==2.32.3 sagemaker==2.224.1 scikit-learn==1.5.0 tqdm==4.66.4 urllib3==2.2.2 werkzeug==3.0.3
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git less libblkid-dev libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libglib2.0-bin libgnutls30 libmount-dev libmount1 libnghttp2-14 libsmartcols1 libtiff5 libuuid1 libvpx6 linux-libc-dev mount util-linux uuid-dev vim-common vim-runtime vim xxd
#### Patch contents for patch-9: sha256:47b0149cb5b630d554e89fa32f2c343089bdb34ea9b61ab7035ac79750f14307 ####
pip install anyio==4.4.0 awscli==1.33.14 botocore==1.34.132 cryptography==42.0.8 idna==3.7 jinja2==3.1.4 jupyter-server==2.14.1 pillow==10.3.0 requests==2.32.3 sagemaker==2.224.1 scikit-learn==1.5.0 tqdm==4.66.4 urllib3==2.2.2 werkzeug==3.0.3
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git less libblkid-dev libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libglib2.0-bin libgnutls30 libmount-dev libmount1 libnghttp2-14 libsmartcols1 libtiff5 libuuid1 libvpx6 linux-libc-dev mount util-linux uuid-dev vim-common vim-runtime vim xxd
#### Current Patch contents ####
pip install anyio==4.4.0 awscli==1.33.19 botocore==1.34.137 cryptography==42.0.8 idna==3.7 jinja2==3.1.4 jupyter-server==2.14.1 pillow==10.4.0 requests==2.32.3 sagemaker==2.224.2 scikit-learn==1.5.0 tqdm==4.66.4 urllib3==2.2.2 werkzeug==3.0.3
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git less libblkid-dev libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcdio18 libcups2 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libglib2.0-bin libgnutls30 libmount-dev libmount1 libnghttp2-14 libsmartcols1 libtiff5 libuuid1 libvpx6 linux-libc-dev mount util-linux uuid-dev vim-common vim-runtime vim wget xxd
