image:
  name: "sagemaker-tei-gpu"
  description: "SageMaker TEI 1.9.3 GPU"

metadata:
  framework: "tei"
  framework_version: "1.9.3"
  os_version: "ubuntu24.04"
  customer_type: "sagemaker"
  platform: "sagemaker"
  arch_type: "x86"
  device_type: "gpu"
  job_type: "inference"
  prod_image: "tei:2.0.1-tei1.9.3-gpu-py310-cu129-ubuntu24.04"

build:
  dockerfile: "docker/tei/1.9.3/gpu/Dockerfile"
  target: "sagemaker"
  python_version: "3.10"
  cuda_version: "12.9.1"

release:
  release: false
  force_release: false
  public_registry: false
  private_registry: true
  enable_soci: false
  environment: "gamma"
