framework: &FRAMEWORK tensorflow
<<<<<<< HEAD
nightly_versions:
  - "2.9-nightly"
current_versions:
  # With N parallel pipelines, create entries for the N latest framework versions
  # N = 4
  - "2.8"
  - "2.7"
  - "2.6"
  - "2.5"
current_neuron_versions:
  # N = 2
  # With N parallel pipelines, create entries for the N latest framework versions
  - "2.5-neuron"
  - "1.15-neuron"
current_graviton_versions:
  # N = 1
  # With N parallel pipelines, create entries for the N latest framework versions
  - "2.7-graviton"
buildspecs:
  # Specify the dedicated buildspec file for each framework version here
  # Ensure that the key is exactly the same as the entry (if any) in the "current_versions" lists above
  "2.9-nightly": !join [ *FRAMEWORK, "/", "buildspec-2-9.yml" ]
  "2.8": !join [ *FRAMEWORK, "/", "buildspec-2-8.yml" ]
  "2.7": !join [ *FRAMEWORK, "/", "buildspec-2-7.yml" ]
  "2.6": !join [ *FRAMEWORK, "/", "buildspec-2-6.yml" ]
  "2.5": !join [ *FRAMEWORK, "/", "buildspec-2-5.yml" ]
  "2.4": !join [ *FRAMEWORK, "/", "buildspec-2-4.yml" ]
  "2.3": !join [ *FRAMEWORK, "/", "buildspec-2-3.yml" ]
  "2.2": !join [ *FRAMEWORK, "/", "buildspec-2-2.yml" ]
  "2.1": !join [ *FRAMEWORK, "/", "buildspec-2-1.yml" ]
  "2.0": !join [ *FRAMEWORK, "/", "buildspec-2-0.yml" ]
  "1.15": !join [ *FRAMEWORK, "/", "buildspec-1-15.yml" ]
  # Neuron
  "2.5-neuron": !join [ *FRAMEWORK, "/", "buildspec-neuron.yml" ]
  "1.15-neuron": !join [ *FRAMEWORK, "/", "buildspec-tf1-neuron.yml" ]
  # Graviton
  "2.7-graviton": !join [ *FRAMEWORK, "/", "buildspec-graviton.yml" ]
=======

>>>>>>> master
