  account_id: &ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>
  region: &REGION <set-$REGION-in-environment>
  framework: &FRAMEWORK tensorflow
  version: &VERSION 1.15
  
  repository_info:
    training_repository: &TRAINING_REPOSITORY
      image_type: &IMAGE_TYPE training
      root: !join [ *FRAMEWORK, "/", *IMAGE_TYPE ]
      repository_name: &REPOSITORY_NAME !join [beta, "-", *FRAMEWORK, "-", *IMAGE_TYPE]
      repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]
    inference_repository: &INFERENCE_REPOSITORY
      image_type: &IMAGE_TYPE inference
      root: !join [ *FRAMEWORK, "/", *IMAGE_TYPE ]
      repository_name: &REPOSITORY_NAME !join [beta, "-", *FRAMEWORK, "-", *IMAGE_TYPE]
      repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]

  context:
    training_context: &TRAINING_CONTEXT
      dist/sagemaker_tensorflow_container-2.0.8.dev0.tar.gz: sagemaker_tensorflow_container-2.0.8.dev0.tar.gz
      docker/build_artifacts/dockerd-entrypoint.py: dockerd-entrypoint.py
      docker/build_artifacts/deep_learning_container.py: deep_learning_container.py
    inference_context: &INFERENCE_CONTEXT
      docker/build_artifacts/sagemaker: sagemaker
      docker/build_artifacts/deep_learning_container.py: deep_learning_container.py
      docker/build_artifacts/__init__.py: __init__.py 
      docker/build_artifacts/dockerd-entrypoint.py: dockerd-entrypoint.py


  images:
    BuildTensorflowCPUTrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      version: 1.15
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildTensorflowGPUTrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      version: 1.15
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildTensorflowCPUTrainPy2DockerImage:
      <<: *TRAINING_REPOSITORY
      version: 1.15
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py2
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildTensorflowGPUTrainPy2DockerImage:
      <<: *TRAINING_REPOSITORY
      version: 1.15
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py2
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildTensorflowCPUInferenceDockerImage:
      <<: *INFERENCE_REPOSITORY
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION,  /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
    BuildTensorflowGPUInferenceDockerImage:
      <<: *INFERENCE_REPOSITORY
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION,  /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT

