  account_id: &ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>
  region: &REGION <set-$REGION-in-environment>
  framework: &FRAMEWORK tensorflow
  version: &VERSION 2.1.0
  cuda_version: &CUDA_VERSION cu101
  os_version: &OS_VERSION ubuntu18.04

  repository_info:
    training_repository: &TRAINING_REPOSITORY
      image_type: &TRAINING_IMAGE_TYPE training
      root: !join [ *FRAMEWORK, "/", *TRAINING_IMAGE_TYPE ]
      repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *TRAINING_IMAGE_TYPE]
      repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]
    inference_repository: &INFERENCE_REPOSITORY
      image_type: &INFERENCE_IMAGE_TYPE inference
      root: !join [ *FRAMEWORK, "/", *INFERENCE_IMAGE_TYPE ]
      repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *INFERENCE_IMAGE_TYPE]
      repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]

  context:
    training_context: &TRAINING_CONTEXT
      sagemaker_package_name:
        source: dist/sagemaker_tensorflow_container-2.0.8.dev0.tar.gz
        target: sagemaker_tensorflow_container-2.0.8.dev0.tar.gz
      dockerd-entrypoint:
        source: docker/build_artifacts/dockerd-entrypoint.py
        target: dockerd-entrypoint.py
      deep_learning_container:
        source: docker/build_artifacts/deep_learning_container.py
        target: deep_learning_container.py
    inference_context: &INFERENCE_CONTEXT
      sagemaker_package_name:
        source: docker/build_artifacts/sagemaker
        target: sagemaker
      deep_learning_container:
        source: docker/build_artifacts/deep_learning_container.py
        target: deep_learning_container.py
      init:
        source: docker/build_artifacts/__init__.py
        target: __init__.py
      dockerd-entrypoint:
        source: docker/build_artifacts/dockerd-entrypoint.py
        target: dockerd-entrypoint.py

  images:
    BuildTensorflowCPUTrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &TENSORFLOW_CPU_TRAINING_PY3 false
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py36
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildTensorflowGPUTrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &TENSORFLOW_GPU_TRAINING_PY3 false
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py36
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildTensorflowCPUTrainPy2DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &TENSORFLOW_CPU_TRAINING_PY2 false
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py27
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildTensorflowGPUTrainPy2DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &TENSORFLOW_GPU_TRAINING_PY2 false
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py27
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildTensorflowCPUInferencePy3DockerImage:
      <<: *INFERENCE_REPOSITORY
      build: &TENSORFLOW_CPU_INFERENCE_PY3 false
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py36
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
    BuildTensorflowGPUInferencePy3DockerImage:
      <<: *INFERENCE_REPOSITORY
      build: &TENSORFLOW_GPU_INFERENCE_PY3 false
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py36
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
    BuildTensorflowCPUInferencePy2DockerImage:
      <<: *INFERENCE_REPOSITORY
      build: &TENSORFLOW_CPU_INFERENCE_PY2 false
      image_size_baseline: 661
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py27
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
    BuildTensorflowGPUInferencePy2DockerImage:
      <<: *INFERENCE_REPOSITORY
      build: &TENSORFLOW_GPU_INFERENCE_PY2 false
      image_size_baseline: 2870
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py27
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
    BuildTensorflowExampleGPUTrainPy2DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &TENSORFLOW_GPU_TRAINING_PY2 false
      image_size_baseline: 4899
      base_image_name: BuildTensorflowGPUTrainPy2DockerImage
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py27
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION,
                   "-example" ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /example, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildTensorflowExampleGPUTrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &TENSORFLOW_GPU_TRAINING_PY3 false
      image_size_baseline: 4899
      base_image_name: BuildTensorflowGPUTrainPy3DockerImage
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py36
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION,
                   "-example" ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /example, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
