  account_id: &ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>
  region: &REGION <set-$REGION-in-environment>
  framework: &FRAMEWORK tensorflow
  short_version: &SHORT_VERSION 1.15
  version: &VERSION 1.15.5

  repository_info:
    training_repository: &TRAINING_REPOSITORY
      image_type: &TRAINING_IMAGE_TYPE training
      root: !join [ *FRAMEWORK, "/", *TRAINING_IMAGE_TYPE ]
      repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *TRAINING_IMAGE_TYPE]
      repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]
    inference_repository: &INFERENCE_REPOSITORY
      image_type: &INFERENCE_IMAGE_TYPE inference
      root: !join [ *FRAMEWORK, "/", *INFERENCE_IMAGE_TYPE ]
      repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *INFERENCE_IMAGE_TYPE]
      repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]

  context:
    training_context: &TRAINING_CONTEXT
      dockerd-entrypoint:
        source: docker/build_artifacts/dockerd-entrypoint.py
        target: dockerd-entrypoint.py
    inference_context: &INFERENCE_CONTEXT
      sagemaker_package_name:
        source: docker/build_artifacts/sagemaker
        target: sagemaker
      init:
        source: docker/build_artifacts/__init__.py
        target: __init__.py
      dockerd-entrypoint:
        source: docker/build_artifacts/dockerd-entrypoint.py
        target: dockerd-entrypoint.py

  images:
    BuildTensorflowCPUTrainPy36DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &TENSORFLOW_CPU_TRAINING_PY3 false
      image_size_baseline: 4489
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py36
      tag_python_version: &TAG_PYTHON_VERSION py36
      os_version: &OS_VERSION ubuntu18.04
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildTensorflowGPUCu100TrainPy36DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &TENSORFLOW_GPU_TRAINING_PY3 false
      image_size_baseline: 4489
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py36
      tag_python_version: &TAG_PYTHON_VERSION py36
      cuda_version: &CUDA_VERSION cu100
      os_version: &OS_VERSION ubuntu18.04
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildTensorflowExampleGPUCu100TrainPy36DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &TENSORFLOW_GPU_TRAINING_PY3 false
      image_size_baseline: 4489
      base_image_name: BuildTensorflowGPUCu100TrainPy36DockerImage
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py36
      tag_python_version: &TAG_PYTHON_VERSION py36
      cuda_version: &CUDA_VERSION cu100
      os_version: &OS_VERSION ubuntu18.04
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION,
                   "-example" ]
      docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /example, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildTensorflowCPUTrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &TENSORFLOW_CPU_TRAINING_PY3 false
      image_size_baseline: 4489
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag_python_version: &TAG_PYTHON_VERSION py37
      os_version: &OS_VERSION ubuntu18.04
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildTensorflowGPUCu100TrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &TENSORFLOW_GPU_TRAINING_PY3 false
      image_size_baseline:  4489
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag_python_version: &TAG_PYTHON_VERSION py37
      cuda_version: &CUDA_VERSION cu100
      os_version: &OS_VERSION ubuntu18.04
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildTensorflowExampleGPUCu100TrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &TENSORFLOW_GPU_TRAINING_PY3 false
      image_size_baseline: 4489
      base_image_name: BuildTensorflowGPUCu100TrainPy3DockerImage
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag_python_version: &TAG_PYTHON_VERSION py37
      cuda_version: &CUDA_VERSION cu100
      os_version: &OS_VERSION ubuntu18.04
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION,
                   "-example" ]
      docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /example, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildTensorflowGPUCu110TrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &TENSORFLOW_GPU_TRAINING_PY3 false
      image_size_baseline: 7738
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag_python_version: &TAG_PYTHON_VERSION py37
      cuda_version: &CUDA_VERSION cu110
      os_version: &OS_VERSION ubuntu18.04
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildTensorflowExampleGPUCu110TrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &TENSORFLOW_GPU_TRAINING_PY3 false
      image_size_baseline: 7738
      base_image_name: BuildTensorflowGPUCu110TrainPy3DockerImage
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag_python_version: &TAG_PYTHON_VERSION py37
      cuda_version: &CUDA_VERSION cu110
      os_version: &OS_VERSION ubuntu18.04
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION,
                   "-example" ]
      docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /example, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
