account_id: &ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>
region: &REGION <set-$REGION-in-environment>
framework: &FRAMEWORK tensorflow
version: &VERSION 2.5.1
short_version: &SHORT_VERSION 2.5
repository_info:
  training_repository: &TRAINING_REPOSITORY
    image_type: &TRAINING_IMAGE_TYPE training
    root: !join [ *FRAMEWORK, "/", *TRAINING_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *TRAINING_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/,
      *REPOSITORY_NAME ]
  inference_repository: &INFERENCE_REPOSITORY
    image_type: &INFERENCE_IMAGE_TYPE inference
    root: !join [ *FRAMEWORK, "/", *INFERENCE_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *INFERENCE_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/,
      *REPOSITORY_NAME ]
context:
  training_context: &TRAINING_CONTEXT
    dockerd-entrypoint:
      source: docker/build_artifacts/dockerd-entrypoint.py
      target: dockerd-entrypoint.py
    deep_learning_container:
      source: ../../src/deep_learning_container.py
      target: deep_learning_container.py
  inference_context: &INFERENCE_CONTEXT
    sagemaker_package_name:
      source: docker/build_artifacts/sagemaker
      target: sagemaker
    init:
      source: docker/build_artifacts/__init__.py
      target: __init__.py
    dockerd-entrypoint:
      source: docker/build_artifacts/dockerd-entrypoint.py
      target: dockerd-entrypoint.py
    deep_learning_container:
      source: ../../src/deep_learning_container.py
      target: deep_learning_container.py

images:
  BuildTensorflowDIYCpuPy37TrainingDockerImage:
    <<: *TRAINING_REPOSITORY
    build: &TENSORFLOW_CPU_TRAINING_PY3 false
    image_size_baseline: &IMAGE_SIZE_BASELINE 4489
    device_type: &DEVICE_TYPE cpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py37
    os_version: &OS_VERSION ubuntu18.04
    enable_test_promotion: false
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION, "-e3"
      ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile.diy.,
      *DEVICE_TYPE ]
    context:
      <<: *TRAINING_CONTEXT
  BuildTensorflowSageMakerCpuPy37TrainingDockerImage:
    <<: *TRAINING_REPOSITORY
    build: &TENSORFLOW_GPU_TRAINING_PY3 false
    image_size_baseline: &IMAGE_SIZE_BASELINE 7738
    base_image_name: BuildTensorflowDIYCpuPy37TrainingDockerImage
    device_type: &DEVICE_TYPE cpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py37
    os_version: &OS_VERSION ubuntu18.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION, "-sagemaker"
      ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile.sagemaker.,
      *DEVICE_TYPE ]
    context:
      <<: *TRAINING_CONTEXT
  BuildTensorflowDIYGpuPy37Cu112TrainingDockerImage:
    <<: *TRAINING_REPOSITORY
    build: &TENSORFLOW_GPU_TRAINING_PY3 false
    image_size_baseline: &IMAGE_SIZE_BASELINE 7738
    device_type: &DEVICE_TYPE gpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py37
    cuda_version: &CUDA_VERSION cu112
    os_version: &OS_VERSION ubuntu18.04
    enable_test_promotion: false
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION,
      "-", *OS_VERSION, "-e3" ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION,
      /Dockerfile.diy., *DEVICE_TYPE ]
    context:
      <<: *TRAINING_CONTEXT
  BuildTensorflowSageMakerGpuPy37Cu112TrainingDockerImage:
    <<: *TRAINING_REPOSITORY
    build: &TENSORFLOW_GPU_TRAINING_PY3 false
    image_size_baseline: &IMAGE_SIZE_BASELINE 7738
    base_image_name: BuildTensorflowDIYGpuPy37Cu112TrainingDockerImage
    device_type: &DEVICE_TYPE gpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py37
    cuda_version: &CUDA_VERSION cu112
    os_version: &OS_VERSION ubuntu18.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION,
      "-", *OS_VERSION, "-sagemaker" ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION,
      /Dockerfile.sagemaker., *DEVICE_TYPE ]
    context:
      <<: *TRAINING_CONTEXT
  BuildTensorflowExampleGpuPy37Cu112TrainingDockerImage:
    <<: *TRAINING_REPOSITORY
    build: &TENSORFLOW_GPU_TRAINING_PY3 false
    image_size_baseline: &IMAGE_SIZE_BASELINE 7738
    base_image_name: BuildTensorflowDIYGpuPy37Cu112TrainingDockerImage
    device_type: &DEVICE_TYPE gpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py37
    cuda_version: &CUDA_VERSION cu112
    os_version: &OS_VERSION ubuntu18.04
    enable_test_promotion: false
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION,
      "-", *OS_VERSION, "-example" ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /example,
      /Dockerfile., *DEVICE_TYPE ]
    context:
      <<: *TRAINING_CONTEXT
  BuildTensorflowDIYCPUInferencePy3DockerImage:
    <<: *INFERENCE_REPOSITORY
    build: &TENSORFLOW_CPU_INFERENCE_PY3 false
    image_size_baseline: 4899
    device_type: &DEVICE_TYPE cpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py37
    os_version: &OS_VERSION ubuntu18.04
    # TODO: To be reverted once TF Training 2.5.1 is released
    tag: !join [ "2.5.1", "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION, "-e3" ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile.diy., *DEVICE_TYPE ]
    context:
      <<: *INFERENCE_CONTEXT
  BuildTensorflowSageMakerCpuPy37InferenceDockerImage:
    <<: *INFERENCE_REPOSITORY
    build: &TENSORFLOW_CPU_INFERENCE_PY3 false
    image_size_baseline: 4899
    base_image_name: BuildTensorflowDIYCPUInferencePy3DockerImage
    device_type: &DEVICE_TYPE cpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py37
    os_version: &OS_VERSION ubuntu18.04
    # TODO: To be reverted once TF Training 2.5.1 is released
    tag: !join [ "2.5.1", "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION, "-sagemaker" ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile.sagemaker., *DEVICE_TYPE ]
    context:
      <<: *INFERENCE_CONTEXT
  BuildTensorflowDIYGPUInferencePy3DockerImage:
    <<: *INFERENCE_REPOSITORY
    build: &TENSORFLOW_GPU_INFERENCE_PY3 false
    image_size_baseline: 7738
    device_type: &DEVICE_TYPE gpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py37
    cuda_version: &CUDA_VERSION cu112
    os_version: &OS_VERSION ubuntu18.04
    enable_test_promotion: false
    # TODO: To be reverted once TF Training 2.5.1 is released
    tag: !join [ "2.5.1", "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION, "-e3" ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION, /Dockerfile.diy., *DEVICE_TYPE ]
    context:
      <<: *INFERENCE_CONTEXT
  BuildTensorflowSageMakerGpuPy37Cu112InferenceDockerImage:
    <<: *INFERENCE_REPOSITORY
    build: &TENSORFLOW_GPU_INFERENCE_PY3 false
    image_size_baseline: &IMAGE_SIZE_BASELINE 7738
    base_image_name: BuildTensorflowDIYGPUInferencePy3DockerImage
    device_type: &DEVICE_TYPE gpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py37
    cuda_version: &CUDA_VERSION cu112
    os_version: &OS_VERSION ubuntu18.04
    # TODO: To be reverted once TF Training 2.5.1 is released
    tag: !join [ "2.5.1", "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION, "-sagemaker" ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION, /Dockerfile.sagemaker., *DEVICE_TYPE ]
    context:
      <<: *INFERENCE_CONTEXT
