account_id: &ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>
region: &REGION <set-$REGION-in-environment>
framework: &FRAMEWORK tensorflow
version: &VERSION 2.9.0
short_version: &SHORT_VERSION 2.9
repository_info:
  training_repository: &TRAINING_REPOSITORY
    image_type: &TRAINING_IMAGE_TYPE training
    root: !join [ *FRAMEWORK, "/", *TRAINING_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *TRAINING_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/,
      *REPOSITORY_NAME ]
  inference_repository: &INFERENCE_REPOSITORY
    image_type: &INFERENCE_IMAGE_TYPE inference
    root: !join [ *FRAMEWORK, "/", *INFERENCE_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *INFERENCE_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]
context:
  training_context: &TRAINING_CONTEXT
    dockerd-entrypoint:
      source: docker/build_artifacts/dockerd-entrypoint.py
      target: dockerd-entrypoint.py
    deep_learning_container:
      source: ../../src/deep_learning_container.py
      target: deep_learning_container.py
  inference_context: &INFERENCE_CONTEXT
    sagemaker_package_name:
      source: docker/build_artifacts/sagemaker
      target: sagemaker
    init:
      source: docker/build_artifacts/__init__.py
      target: __init__.py
    dockerd-entrypoint:
      source: docker/build_artifacts/dockerd-entrypoint.py
      target: dockerd-entrypoint.py
    deep_learning_container:
      source: ../../src/deep_learning_container.py
      target: deep_learning_container.py

images:
  BuildTensorflowSageMakerLiteGpuPy39Cu112TrainingDockerImage:
    <<: *TRAINING_REPOSITORY
    build: &TENSORFLOW_GPU_TRAINING_PY3 false
    image_size_baseline: &IMAGE_SIZE_BASELINE 7738
    base_image_name: BuildTensorflowE3GpuCu112Py38TrainingDockerImage
    device_type: &DEVICE_TYPE gpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py38
    cuda_version: &CUDA_VERSION cu112
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION,
                "-", *OS_VERSION, "-sagemaker-lite" ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION,
                        /Dockerfile.sagemaker.lite., *DEVICE_TYPE ]
    target: sagemaker
    labels:
     aws_framework_installed: "false"
     smdebug_installed: "false"
     smddp_installed: "false"
     smdmp_installed: "false"
    context:
      <<: *TRAINING_CONTEXT
  BuildTensorflowSageMakerLiteCpuPy39TrainingDockerImage:
    <<: *TRAINING_REPOSITORY
    build: &TENSORFLOW_CPU_TRAINING_PY3 false
    image_size_baseline: &IMAGE_SIZE_BASELINE 4489
    base_image_name: BuildTensorflowE3CpuPy39TrainingDockerImage
    device_type: &DEVICE_TYPE cpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py38
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION, "-sagemaker-lite" ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile.sagemaker.lite.,
                         *DEVICE_TYPE ]
    target: sagemaker
    labels:
      aws_framework_installed: "false"
      smdebug_installed: "false"
    context:
      <<: *TRAINING_CONTEXT
