# Disable the test codebuild jobs to be run
DISABLE_SANITY_TESTS = False
DISABLE_SAGEMAKER_TESTS = False
DISABLE_ECS_TESTS = False
DISABLE_EKS_TESTS = False
DISABLE_EC2_TESTS = False
USE_SCHEDULER = True
