# Disable the test codebuild jobs to be run
DISABLE_SANITY_TESTS = False
DISABLE_SAGEMAKER_TESTS = False
DISABLE_ECS_TESTS = True
DISABLE_EKS_TESTS = True
DISABLE_EC2_TESTS = True
USE_SCHEDULER = False
