image:
  name: "sglang-ec2-amzn2023"
  description: "SGLang for EC2 instances (AL2023, built from source)"

metadata:
  framework: "sglang_server"
  framework_version: "0.5.21+dlc1"
  os_version: "amzn2023"
  customer_type: "ec2"
  arch_type: "x86"
  device_type: "gpu"
  job_type: "general"
  prod_image: "sglang:server-cuda-v1"

build:
  dockerfile: "docker/sglang/Dockerfile.amzn2023"
  target: "sglang-ec2"
  python_version: "3.12"
  cuda_version: "13.0.3"
  sglang_ref: "99c59a2ea62f32fd5497eceaf2ed18cad33389db"
  sglang_kernel_version: "0.4.7"
  flashinfer_version: "0.7.0.post1"
  deepep_commit: "874779c9ccd2294b56304bd6cc5f138f1f71d097"
  flashmla_commit: "15f13e5030374295491c5ce31b02d7e63a7772c6"
  mooncake_version: "0.3.13"
  torch_version: "2.13.0"
  nccl_version: "2.31.2"
  cudnn_version: "9.16.0.29"
  nvshmem4py_version: "0.3.1"
  efa_version: "latest"
  rust_version: "1.96.1"
  gdrcopy_version: "2.5.2"
  ffmpeg_version: "8.0.1"
  ffmpeg_sha256: "05ee0b03119b45c0bdb4df654b96802e909e0a752f72e4fe3794f487229e5a41"
  dav1d_version: "1.5.4"
  dav1d_sha256: "686616b7c69eb88d44459391ab25cac13b6647a3b288835c5784e71c1514a5c5"
  torch_cuda_arch_list: "9.0;10.0;10.3"
  dlc_major_version: "1"
  dlc_minor_version: "5"

release:
  release: true
  force_release: false
  public_registry: true
  private_registry: true
  enable_soci: true
  environment: "production"
