  account_id: &ACCOUNT_ID '669063966089'
  region: &REGION us-west-2
  framework: &FRAMEWORK pytorch
  version: &VERSION 1.3.1
  image_type: &IMAGE_TYPE inference
  root: !join [ *FRAMEWORK, "/", *IMAGE_TYPE ]
  repository_name: &REPOSITORY_NAME !join [beta, "-", *FRAMEWORK, "-", *IMAGE_TYPE]
  repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]

  # TODO: The context specifies the artifacts necessary for the
  # docker build. Each artifact needs to be specified as follows:
  # source: target
  # Both source and target can be complete paths relative to the root path
  # specified above. 
  context:
      docker/build_artifacts/mms-entrypoint.py: mms-entrypoint.py
      docker/build_artifacts/config.properties: config.properties
      docker/build_artifacts/deep_learning_container.py: deep_learning_container.py
      dist/sagemaker_pytorch_serving_container-1.3-py2.py3-none-any.whl: sagemaker_pytorch_serving_container-1.3-py2.py3-none-any.whl

  images:
    BuildCPUPTInferencePy3DockerImage:
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &PYTHON_VERSION py3
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
    BuildGPUPTInferencePy3DockerImage:
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &PYTHON_VERSION py3
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
    BuildCPUPTInferencePy2DockerImage:
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &PYTHON_VERSION py2
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
    BuildGPUPTInferencePy2DockerImage:
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &PYTHON_VERSION py2
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
