account_id: &ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>
region: &REGION <set-$REGION-in-environment>
framework: &FRAMEWORK pytorch
version: &VERSION 1.13.0
short_version: &SHORT_VERSION "1.13"
arch_type: x86
docker_file_version: &DOCKER_FILE_VERSION lite

repository_info:
  inference_repository: &INFERENCE_REPOSITORY
    image_type: &INFERENCE_IMAGE_TYPE inference
    root: !join [ *FRAMEWORK, "/", *INFERENCE_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *INFERENCE_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]

context:
  inference_context: &INFERENCE_CONTEXT
    torchserve-entrypoint:
      source: docker/build_artifacts/torchserve-entrypoint.py
      target: torchserve-entrypoint.py
    config:
      source: docker/build_artifacts/config.properties
      target: config.properties
    deep_learning_container:
      source: ../../src/deep_learning_container.py
      target: deep_learning_container.py

images:
  # Build Sagemaker CPU Inference Image
  BuildSageMakerCPUPTInferencePy3DockerImage:
    <<: *INFERENCE_REPOSITORY
    build: &PYTORCH_CPU_INFERENCE_PY3 false
    image_size_baseline: 4899
    device_type: &DEVICE_TYPE cpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py38
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION, "-sagemaker-lite" ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile.sagemaker., *DOCKER_FILE_VERSION, ".", *DEVICE_TYPE ]
    target: sagemaker
    labels:
      aws_framework_installed: false
    context:
      <<: *INFERENCE_CONTEXT
  # Build Sagemaker GPU Inference Image
  BuildSageMakerGPUPTInferencePy3DockerImage:
    <<: *INFERENCE_REPOSITORY
    build: &PYTORCH_GPU_INFERENCE_PY3 false
    image_size_baseline: 14000
    device_type: &DEVICE_TYPE gpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py38
    cuda_version: &CUDA_VERSION cu113
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION, "-sagemaker-lite" ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION, /Dockerfile.sagemaker.lite, *DOCKER_FILE_VERSION, ".", *DEVICE_TYPE ]
    target: sagemaker
    labels:
      aws_framework_installed: false
    context:
      <<: *INFERENCE_CONTEXT
