account_id: &ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>
region: &REGION <set-$REGION-in-environment>
framework: &FRAMEWORK mxnet
version: &VERSION 1.9.0
short_version: &SHORT_VERSION 1.9

repository_info:
  training_repository: &TRAINING_REPOSITORY
    image_type: &TRAINING_IMAGE_TYPE training
    root: !join [ *FRAMEWORK, "/", *TRAINING_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *TRAINING_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]

  inference_repository: &INFERENCE_REPOSITORY
    image_type: &INFERENCE_IMAGE_TYPE inference
    root: !join [ *FRAMEWORK, "/", *INFERENCE_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *INFERENCE_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]

context:
  training_context: &TRAINING_CONTEXT
    entrypoint:
      source: docker/artifacts/dockerd-entrypoint.py
      target: dockerd-entrypoint.py
    deep_learning_container:
      source: ../../src/deep_learning_container.py
      target: deep_learning_container.py
  inference_context: &INFERENCE_CONTEXT
    config:
      source: docker/artifacts/config.properties
      target: config.properties
    entrypoint:
      source: docker/artifacts/mms-entrypoint.py
      target:  mms-entrypoint.py
    e3-entrypoint:
      source: docker/artifacts/mms-entrypoint.py
      target: mms-e3-entrypoint.py
    deep_learning_container:
      source: ../../src/deep_learning_container.py
      target: deep_learning_container.py

images:
  BuildE3MXNetCPUTrainPy3DockerImage:
    <<: *TRAINING_REPOSITORY
    build: &MXNET_CPU_TRAINING_PY3 false
    image_size_baseline: 3000
    device_type: &DEVICE_TYPE cpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py38
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION, "-e3" ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
    target: e3
    context:
      <<: *TRAINING_CONTEXT
  # BuildE3MXNetGPUTrainPy3DockerImage:
  #   <<: *TRAINING_REPOSITORY
  #   build: &MXNET_GPU_TRAINING_PY3 false
  #   image_size_baseline: 7159
  #   device_type: &DEVICE_TYPE gpu
  #   python_version: &DOCKER_PYTHON_VERSION py3
  #   tag_python_version: &TAG_PYTHON_VERSION py38
  #   cuda_version: &CUDA_VERSION cu112
  #   os_version: &OS_VERSION ubuntu20.04
  #   tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION, "-e3" ]
  #   docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION, /Dockerfile., *DEVICE_TYPE ]
  #   target: e3
  #   context:
  #     <<: *TRAINING_CONTEXT
  # BuildSMMXNetCPUTrainPy3DockerImage:
  #   <<: *TRAINING_REPOSITORY
  #   build: &MXNET_CPU_TRAINING_PY3 false
  #   image_size_baseline: 3000
  #   device_type: &DEVICE_TYPE cpu
  #   python_version: &DOCKER_PYTHON_VERSION py3
  #   tag_python_version: &TAG_PYTHON_VERSION py38
  #   os_version: &OS_VERSION ubuntu20.04
  #   tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION, "-sagemaker" ]
  #   docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
  #   target: sagemaker
  #   context:
  #     <<: *TRAINING_CONTEXT
  # BuildSMMXNetGPUTrainPy3DockerImage:
  #   <<: *TRAINING_REPOSITORY
  #   build: &MXNET_GPU_TRAINING_PY3 false
  #   image_size_baseline: 7159
  #   device_type: &DEVICE_TYPE gpu
  #   python_version: &DOCKER_PYTHON_VERSION py3
  #   tag_python_version: &TAG_PYTHON_VERSION py38
  #   cuda_version: &CUDA_VERSION cu112
  #   os_version: &OS_VERSION ubuntu20.04
  #   tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION, "-sagemaker" ]
  #   docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION, /Dockerfile., *DEVICE_TYPE ]
  #   target: sagemaker
  #   context:
  #     <<: *TRAINING_CONTEXT
  # BuildE3MXNetCPUInferencePy3DockerImage:
  #   <<: *INFERENCE_REPOSITORY
  #   build: &MXNET_CPU_INFERENCE_PY3 false
  #   image_size_baseline: 2202
  #   device_type: &DEVICE_TYPE cpu
  #   python_version: &DOCKER_PYTHON_VERSION py3
  #   tag_python_version: &TAG_PYTHON_VERSION py38
  #   os_version: &OS_VERSION ubuntu20.04
  #   tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION, "-e3" ]
  #   docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
  #   target: e3
  #   context:
  #     <<: *INFERENCE_CONTEXT
  # BuildE3MXNetGPUInferencePy3DockerImage:
  #   << : *INFERENCE_REPOSITORY
  #   build: &MXNET_GPU_INFERENCE_PY3 false
  #   image_size_baseline: 6758
  #   device_type: &DEVICE_TYPE gpu
  #   python_version: &DOCKER_PYTHON_VERSION py3
  #   tag_python_version: &TAG_PYTHON_VERSION py38
  #   cuda_version: &CUDA_VERSION cu112
  #   os_version: &OS_VERSION ubuntu20.04
  #   tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION, "-e3" ]
  #   docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION, /Dockerfile., *DEVICE_TYPE ]
  #   target: e3
  #   context:
  #     <<: *INFERENCE_CONTEXT
  # BuildSMMXNetCPUInferencePy3DockerImage:
  #   <<: *INFERENCE_REPOSITORY
  #   build: &MXNET_CPU_INFERENCE_PY3 false
  #   image_size_baseline: 2202
  #   device_type: &DEVICE_TYPE cpu
  #   python_version: &DOCKER_PYTHON_VERSION py3
  #   tag_python_version: &TAG_PYTHON_VERSION py38
  #   os_version: &OS_VERSION ubuntu20.04
  #   tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION, "-sagemaker" ]
  #   docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
  #   target: sagemaker
  #   context:
  #     <<: *INFERENCE_CONTEXT
  # BuildSMMXNetGPUInferencePy3DockerImage:
  #   <<: *INFERENCE_REPOSITORY
  #   build: &MXNET_GPU_INFERENCE_PY3 false
  #   image_size_baseline: 6758
  #   device_type: &DEVICE_TYPE gpu
  #   python_version: &DOCKER_PYTHON_VERSION py3
  #   tag_python_version: &TAG_PYTHON_VERSION py38
  #   cuda_version: &CUDA_VERSION cu112
  #   os_version: &OS_VERSION ubuntu20.04
  #   tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION, "-sagemaker" ]
  #   docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION, /Dockerfile., *DEVICE_TYPE ]
  #   target: sagemaker
  #   context:
  #     <<: *INFERENCE_CONTEXT
  # BuildMXNetExampleGPUTrainPy3DockerImage:
  #   <<: *TRAINING_REPOSITORY
  #   build: &MXNET_GPU_TRAINING_PY3 false
  #   image_size_baseline: 7324
  #   base_image_name: BuildE3MXNetGPUTrainPy3DockerImage
  #   device_type: &DEVICE_TYPE gpu
  #   python_version: &DOCKER_PYTHON_VERSION py3
  #   tag_python_version: &TAG_PYTHON_VERSION py38
  #   cuda_version: &CUDA_VERSION cu112
  #   os_version: &OS_VERSION ubuntu20.04
  #   tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION,
  #                "-e3-example" ]
  #   docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /example, /Dockerfile., *DEVICE_TYPE ]
  #   context:
  #     <<: *TRAINING_CONTEXT
