  account_id: &ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>
  region: &REGION <set-$REGION-in-environment>
  framework: &FRAMEWORK mxnet
  version: &VERSION 1.6.0
  cuda_version: &CUDA_VERSION cu101
  os_version: &OS_VERSION ubuntu16.04

  repository_info:
    training_repository: &TRAINING_REPOSITORY
      image_type: &TRAINING_IMAGE_TYPE training
      root: !join [ *FRAMEWORK, "/", *TRAINING_IMAGE_TYPE ]
      repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *TRAINING_IMAGE_TYPE]
      repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ] 
    
    inference_repository: &INFERENCE_REPOSITORY
      image_type: &INFERENCE_IMAGE_TYPE inference
      root: !join [ *FRAMEWORK, "/", *INFERENCE_IMAGE_TYPE ]
      repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *INFERENCE_IMAGE_TYPE]
      repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ] 

  context:
      deep_learning_container.py:
        source: docker/artifacts/deep_learning_container.py
        target: deep_learning_container.py
      training_context: &TRAINING_CONTEXT
        sagamaker_package:
          source: dist/sagemaker_mxnet_container-3.1.5.dev0.tar.gz
          target: sagemaker_mxnet_container.tar.gz
        entrypoint:
          source: docker/artifacts/dockerd-entrypoint.py
          target: dockerd-entrypoint.py
      inference_context: &INFERENCE_CONTEXT
        sagemaker_package:
          source: dist/sagemaker_mxnet_serving_container-1.1.6.dev0.tar.gz
          target: sagemaker_mxnet_serving_container.tar.gz
        config:
          source: docker/artifacts/config.properties
          target: config.properties
        entrypoint:
          source: docker/artifacts/mms-entrypoint.py
          target:  mms-entrypoint.py

  images:
    BuildMXNetCPUTrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &MXNET_CPU_TRAINING_PY3 false
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag_python_version: &TAG_PYTHON_VERSION py36
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildMXNetGPUTrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &MXNET_GPU_TRAINING_PY3 false
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag_python_version: &TAG_PYTHON_VERSION py36
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildMXNetCPUTrainPy2DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &MXNET_CPU_TRAINING_PY2 false
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py2
      tag_python_version: &TAG_PYTHON_VERSION py27
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildMXNetGPUTrainPy2DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &MXNET_GPU_TRAINING_PY2 false
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py2
      tag_python_version: &TAG_PYTHON_VERSION py27
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildMXNetCPUInferencePy3DockerImage:
      <<: *INFERENCE_REPOSITORY
      build: &MXNET_CPU_INFERENCE_PY3 false
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag_python_version: &TAG_PYTHON_VERSION py36
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
    BuildMXNetGPUInferencePy3DockerImage:
      << : *INFERENCE_REPOSITORY
      build: &MXNET_GPU_INFERENCE_PY3 false
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag_python_version: &TAG_PYTHON_VERSION py36
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
    BuildMXNetCPUInferencePy2DockerImage:
      << : *INFERENCE_REPOSITORY
      build: &MXNET_CPU_INFERENCE_PY2 false
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py2
      tag_python_version: &TAG_PYTHON_VERSION py27
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
    BuildMXNetGPUInferencePy2DockerImage:
      << : *INFERENCE_REPOSITORY
      build: &MXNET_GPU_INFERENCE_PY2 false
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py2
      tag_python_version: &TAG_PYTHON_VERSION py27
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
    BuildMXNetExampleGPUTrainPy2DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &MXNET_GPU_TRAINING_PY2 false
      image_size_baseline: 4500
      base_image_name: BuildMXNetGPUTrainPy2DockerImage
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py2
      tag_python_version: &TAG_PYTHON_VERSION py27
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION,
                   "-example" ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /example, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
    BuildMXNetExampleGPUTrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &MXNET_GPU_TRAINING_PY3 false
      image_size_baseline: 5000
      base_image_name: BuildMXNetGPUTrainPy3DockerImage
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag_python_version: &TAG_PYTHON_VERSION py36
      tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION,
                   "-example" ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /example, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT

