  account_id: &ACCOUNT_ID '669063966089'
  region: &REGION us-west-2
  framework: &FRAMEWORK mxnet
  version: &VERSION 1.6.0
  
  repository_info:
    training_repository: &TRAINING_REPOSITORY
      image_type: &IMAGE_TYPE training
      root: !join [ *FRAMEWORK, "/", *IMAGE_TYPE ]
      repository_name: &REPOSITORY_NAME !join [beta, "-", *FRAMEWORK, "-", *IMAGE_TYPE]
      repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ] 
    
    inference_repository: &INFERENCE_REPOSITORY
      image_type: &IMAGE_TYPE inference
      root: !join [ *FRAMEWORK, "/", *IMAGE_TYPE ]
      repository_name: &REPOSITORY_NAME !join [beta, "-", *FRAMEWORK, "-", *IMAGE_TYPE]
      repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ] 

  context:
      docker/artifacts/deep_learning_container.py: deep_learning_container.py
      docker/artifacts/__init__.py: __init__.py 
      training_context: &TRAINING_CONTEXT
          dist/sagemaker_mxnet_container-3.1.5.dev0.tar.gz: sagemaker_mxnet_container.tar.gz
          docker/artifacts/dockerd-entrypoint.py: dockerd-entrypoint.py
      inference_context: &INFERENCE_CONTEXT
          dist/sagemaker_mxnet_serving_container-1.1.6.dev0.tar.gz: sagemaker_mxnet_serving_container.tar.gz
          docker/artifacts/config.properties: config.properties
          docker/artifacts/mms-entrypoint.py: mms-entrypoint.py

  images:
    BuildMXNetCPUTrainPy3DockerImage:
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &PYTHON_VERSION py3
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      << : *TRAINING_REPOSITORY
      context:
        <<: *TRAINING_CONTEXT
    BuildMXNetGPUTrainPy3DockerImage:
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &PYTHON_VERSION py3
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      << : *TRAINING_REPOSITORY
      context:
        <<: *TRAINING_CONTEXT
    BuildMXNetCPUTrainPy2DockerImage:
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &PYTHON_VERSION py2
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      << : *TRAINING_REPOSITORY
      context:
        <<: *TRAINING_CONTEXT
    BuildMXNetGPUTrainPy2DockerImage:
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &PYTHON_VERSION py2
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      << : *TRAINING_REPOSITORY
      context:
        <<: *TRAINING_CONTEXT
    BuildMXNetCPUInferencePy3DockerImage:
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &PYTHON_VERSION py3
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      << : *INFERENCE_REPOSITORY
      context:
        <<: *INFERENCE_CONTEXT
    BuildMXNetGPUInferencePy3DockerImage:
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &PYTHON_VERSION py3
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      << : *INFERENCE_REPOSITORY
      context:
        <<: *INFERENCE_CONTEXT
    BuildMXNetCPUInferencePy2DockerImage:
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &PYTHON_VERSION py2
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      << : *INFERENCE_REPOSITORY
      context:
        <<: *INFERENCE_CONTEXT
    BuildMXNetGPUInferencePy2DockerImage:
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &PYTHON_VERSION py2
      tag: !join [ *IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      << : *INFERENCE_REPOSITORY
      context:
        <<: *INFERENCE_CONTEXT

