  account_id: &ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>
  region: &REGION <set-$REGION-in-environment>
  framework: &FRAMEWORK mxnet
  version: &VERSION 1.6.0
  
  repository_info:
    training_repository: &TRAINING_REPOSITORY
      image_type: &TRAINING_IMAGE_TYPE training
      root: !join [ *FRAMEWORK, "/", *TRAINING_IMAGE_TYPE ]
      repository_name: &REPOSITORY_NAME !join [beta, "-", *FRAMEWORK, "-", *TRAINING_IMAGE_TYPE]
      repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ] 
    
    inference_repository: &INFERENCE_REPOSITORY
      image_type: &INFERENCE_IMAGE_TYPE inference
      root: !join [ *FRAMEWORK, "/", *INFERENCE_IMAGE_TYPE ]
      repository_name: &REPOSITORY_NAME !join [beta, "-", *FRAMEWORK, "-", *INFERENCE_IMAGE_TYPE]
      repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ] 

  context:
      deep_learning_container.py:
        source: docker/artifacts/deep_learning_container.py
        target: deep_learning_container.py
      training_context: &TRAINING_CONTEXT
        sagamaker_package:
          source: dist/sagemaker_mxnet_container-3.1.5.dev0.tar.gz
          target: sagemaker_mxnet_container.tar.gz
        entrypoint:
          source: docker/artifacts/dockerd-entrypoint.py
          target: dockerd-entrypoint.py
      inference_context: &INFERENCE_CONTEXT
        sagemaker_package:
          source: dist/sagemaker_mxnet_serving_container-1.1.6.dev0.tar.gz
          target: sagemaker_mxnet_serving_container.tar.gz
        config:
          source: docker/artifacts/config.properties
          target: config.properties
        entrypoint:
          source: docker/artifacts/mms-entrypoint.py
          target:  mms-entrypoint.py

  images:
    BuildMXNetCPUTrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &BUILD true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag: !join [ *TRAINING_IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
        requirements:
         source: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /requirements., *DEVICE_TYPE ]
         target: requirements.txt
    BuildMXNetGPUTrainPy3DockerImage:
      <<: *TRAINING_REPOSITORY
      build: &BUILD true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag: !join [ *TRAINING_IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
        requirements:
         source: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /requirements., *DEVICE_TYPE ]
         target: requirements.txt
    BuildMXNetCPUTrainPy2DockerImage:
      <<: *TRAINING_REPOSITORY
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py2
      tag: !join [ *TRAINING_IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
        requirements:
         source: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /requirements., *DEVICE_TYPE ]
         target: requirements.txt
    BuildMXNetGPUTrainPy2DockerImage:
      <<: *TRAINING_REPOSITORY
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py2
      tag: !join [ *TRAINING_IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *TRAINING_CONTEXT
        requirements:
         source: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /requirements., *DEVICE_TYPE ]
         target: requirements.txt
    BuildMXNetCPUInferencePy3DockerImage:
      <<: *INFERENCE_REPOSITORY
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag: !join [ *INFERENCE_IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
        requirements:
         source: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /requirements., *DEVICE_TYPE ]
         target: requirements.txt
    BuildMXNetGPUInferencePy3DockerImage:
      << : *INFERENCE_REPOSITORY
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py3
      tag: !join [ *INFERENCE_IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
        requirements:
         source: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /requirements., *DEVICE_TYPE ]
         target: requirements.txt
    BuildMXNetCPUInferencePy2DockerImage:
      << : *INFERENCE_REPOSITORY
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE cpu
      python_version: &DOCKER_PYTHON_VERSION py2
      tag: !join [ *INFERENCE_IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
        requirements:
         source: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /requirements., *DEVICE_TYPE ]
         target: requirements.txt
    BuildMXNetGPUInferencePy2DockerImage:
      << : *INFERENCE_REPOSITORY
      build: true
      image_size_baseline: 4899
      device_type: &DEVICE_TYPE gpu
      python_version: &DOCKER_PYTHON_VERSION py2
      tag: !join [ *INFERENCE_IMAGE_TYPE, "-" , *DEVICE_TYPE, "-", *DOCKER_PYTHON_VERSION ]
      docker_file: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
      context:
        <<: *INFERENCE_CONTEXT
        requirements:
         source: !join [ docker/, *VERSION, /, *DOCKER_PYTHON_VERSION, /requirements., *DEVICE_TYPE ]
         target: requirements.txt
