name: 'Release DLC Image (Three Steps)'
description: 'Complete DLC release workflow: publish images, generate release info, and publish notifications'

inputs:
  source-image-uri:
    description: 'Full ECR image URI to pull and promote (e.g., 123456789012.dkr.ecr.us-west-2.amazonaws.com/repo:tag)'
    required: true
  release-spec-content:
    description: 'YAML content for release specification'
    required: true
  release-package-s3-bucket:
    description: 'S3 bucket containing the release package'
    required: false
    default: 'dlc-release-logic-v2'
  release-package-s3-prefix:
    description: 'S3 prefix/folder path to the package'
    required: false
    default: 'DLContainersReleaseLogicV2/DLContainersReleaseLogicV2'
  aws-region:
    description: 'AWS region for S3 and ECR'
    required: false
    default: 'us-west-2'
  source-stage:
    description: 'Source stage (e.g., private, beta)'
    required: true
  target-stage:
    description: 'Target stage (e.g., gamma, release)'
    required: true
  arch:
    description: 'Architecture (amd64 or arm64)'
    required: false
    default: 'amd64'

outputs:
  release-metadata-file:
    description: 'Path to release metadata file'
    value: '/tmp/release_metadata_${{ github.run_id }}-${{ github.run_attempt }}.dict'
  release-completed:
    description: 'Whether all three steps completed successfully'
    value: ${{ steps.step3.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Install SOCI and nerdctl
      shell: bash
      run: |
        echo "Installing SOCI and nerdctl..."
        ARCH_SUFFIX="${{ inputs.arch }}"
        echo "Using architecture: ${ARCH_SUFFIX}"

        # **************** SOCI SNAPSHOTTER *********************************************
        if command -v soci &> /dev/null; then
          echo "SOCI already installed:"
          soci --version
        else
          echo "Installing SOCI for ${ARCH_SUFFIX}..."
          SOCI_VERSION="0.11.1"
          wget https://github.com/awslabs/soci-snapshotter/releases/download/v${SOCI_VERSION}/soci-snapshotter-${SOCI_VERSION}-linux-${ARCH_SUFFIX}.tar.gz
          sudo tar -C /usr/local/bin -xvf soci-snapshotter-${SOCI_VERSION}-linux-${ARCH_SUFFIX}.tar.gz soci soci-snapshotter-grpc
          rm soci-snapshotter-${SOCI_VERSION}-linux-${ARCH_SUFFIX}.tar.gz
          soci --version
          echo "Successfully installed SOCI v${SOCI_VERSION} for ${ARCH_SUFFIX}"
        fi
        # **************** END SOCI SNAPSHOTTER *****************************************

        # **************** NERDCTL ******************************************************
        if command -v nerdctl &> /dev/null; then
          echo "nerdctl already installed:"
          nerdctl --version
        else
          echo "Installing nerdctl for ${ARCH_SUFFIX}..."
          export CONTAINERD_ADDRESS=/var/run/docker/containerd/containerd.sock
          NERDCTL_VERSION="2.1.5"
          wget https://github.com/containerd/nerdctl/releases/download/v${NERDCTL_VERSION}/nerdctl-${NERDCTL_VERSION}-linux-${ARCH_SUFFIX}.tar.gz
          sudo tar -C /usr/local/bin -xzf nerdctl-${NERDCTL_VERSION}-linux-${ARCH_SUFFIX}.tar.gz
          sudo chmod +x /usr/local/bin/nerdctl
          rm nerdctl-${NERDCTL_VERSION}-linux-${ARCH_SUFFIX}.tar.gz
          nerdctl --version
          echo "Successfully installed nerdctl v${NERDCTL_VERSION} for ${ARCH_SUFFIX}"
        fi
        # **************** END NERDCTL **************************************************

        echo "CONTAINERD_ADDRESS=/var/run/docker/containerd/containerd.sock" >> ${GITHUB_ENV}
        echo "ARCH=${ARCH_SUFFIX}" >> ${GITHUB_ENV}

    - name: Download and install release package
      shell: bash
      run: |
        echo "Downloading release package from S3..."
        PACKAGE_DIR="release_package"
        mkdir -p ${PACKAGE_DIR}

        aws s3 sync \
          s3://${{ inputs.release-package-s3-bucket }}/${{ inputs.release-package-s3-prefix }} \
          ${PACKAGE_DIR} \
          --region ${{ inputs.aws-region }}

        if [ ! -d "${PACKAGE_DIR}" ] || [ -z "$(ls -A ${PACKAGE_DIR})" ]; then
          echo "Error: Failed to download package from S3"
          exit 1
        fi

        echo "Creating virtual environment with uv..."
        uv venv --python 3.12 .venv

        echo "Installing release package..."
        uv pip install -e ./${PACKAGE_DIR}

        echo "Making scripts executable and adding to PATH..."
        chmod +x ${PACKAGE_DIR}/scripts/*

        echo "Verifying scripts are executable..."
        ls -la ${PACKAGE_DIR}/scripts/ | grep -E "publish_dlc_images|generate_dlc_image_release_information|publish_release_information"

        echo "PACKAGE_DIR=${PACKAGE_DIR}" >> ${GITHUB_ENV}
        echo "VIRTUAL_ENV=${PWD}/.venv" >> ${GITHUB_ENV}

        # Add both venv/bin and scripts directory to PATH
        echo "${PWD}/.venv/bin" >> ${GITHUB_PATH}
        echo "${PWD}/${PACKAGE_DIR}/scripts" >> ${GITHUB_PATH}

    - name: Set release environment variables
      shell: bash
      run: |
        echo "Setting release environment variables..."

        # Verify scripts are in PATH
        echo "Current PATH: ${PATH}"
        echo "Checking for scripts..."
        which publish_dlc_images || echo "publish_dlc_images not in PATH"
        which generate_dlc_image_release_information || echo "generate_dlc_image_release_information not in PATH"
        which publish_release_information || echo "publish_release_information not in PATH"

        # Create unique identifier for this run
        RUN_IDENTIFIER="${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
        echo "RUN_IDENTIFIER=${RUN_IDENTIFIER}" >> ${GITHUB_ENV}

        # Set metadata file path with unique identifier
        METADATA_FILE="/tmp/release_metadata_${RUN_IDENTIFIER}.dict"
        echo "METADATA_FILE=${METADATA_FILE}" >> ${GITHUB_ENV}

        echo "REGION=${{ inputs.aws-region }}" >> ${GITHUB_ENV}
        echo "SOURCE_STAGE=${{ inputs.source-stage }}" >> ${GITHUB_ENV}
        echo "TARGET_STAGE=${{ inputs.target-stage }}" >> ${GITHUB_ENV}

        echo "Environment variables set:"
        echo "  RUN_IDENTIFIER: ${RUN_IDENTIFIER}"
        echo "  METADATA_FILE: ${METADATA_FILE}"
        echo "  REGION: ${{ inputs.aws-region }}"
        echo "  SOURCE_STAGE: ${{ inputs.source-stage }}"
        echo "  TARGET_STAGE: ${{ inputs.target-stage }}"

    - name: Step 1 - Publish DLC Images
      id: step1
      shell: bash
      run: |
        echo "=========================================="
        echo "Step 1: Publishing DLC Images"
        echo "=========================================="
        echo "Run Identifier: ${RUN_IDENTIFIER}"
        echo "Metadata File: ${METADATA_FILE}"
        echo "Region: ${REGION}"
        echo "Source Stage: ${SOURCE_STAGE}"
        echo "Target Stage: ${TARGET_STAGE}"
        echo "Source Image URI: ${{ inputs.source-image-uri }}"

        # Create release spec file
        cat > release_spec.yml <<'EOF'
        ${{ inputs.release-spec-content }}
        EOF

        echo "Release specification:"
        cat release_spec.yml

        # Run publish_dlc_images with source image URI and custom metadata file path
        publish_dlc_images \
          --release-spec release_spec.yml \
          --source-image-uri "${{ inputs.source-image-uri }}" \
          --metadata-file "${METADATA_FILE}"

        echo "Step 1 completed: Images published successfully"

        # Verify metadata file was created
        if [ -f "${METADATA_FILE}" ]; then
          echo "Release metadata created at: ${METADATA_FILE}"
          cat ${METADATA_FILE}
          echo "success=true" >> ${GITHUB_OUTPUT}
        else
          echo "Error: Release metadata file not found at ${METADATA_FILE}"
          echo "success=false" >> ${GITHUB_OUTPUT}
          exit 1
        fi

    - name: Step 2 - Generate Release Information
      id: step2
      if: steps.step1.outputs.success == 'true'
      shell: bash
      run: |
        echo "=========================================="
        echo "Step 2: Generating Release Information"
        echo "=========================================="
        echo "Run Identifier: ${RUN_IDENTIFIER}"
        echo "Metadata File: ${METADATA_FILE}"
        echo "Region: ${REGION}"
        echo "Source Stage: ${SOURCE_STAGE}"
        echo "Target Stage: ${TARGET_STAGE}"

        # Verify metadata from Step 1 exists
        if [ ! -f "${METADATA_FILE}" ]; then
          echo "Error: Release metadata from Step 1 not found at ${METADATA_FILE}"
          echo "Step 1 must complete successfully before Step 2 can run"
          exit 1
        fi

        echo "Release metadata from Step 1:"
        cat ${METADATA_FILE}

        # Run generate_dlc_image_release_information with custom metadata file path and run ID
        generate_dlc_image_release_information \
          --metadata-file "${METADATA_FILE}" \
          --run-id "${RUN_IDENTIFIER}"

        echo "Step 2 completed: Release information generated and uploaded to S3"
        echo "success=true" >> ${GITHUB_OUTPUT}

    - name: Step 3 - Publish Release Information
      id: step3
      if: steps.step2.outputs.success == 'true'
      shell: bash
      run: |
        echo "=========================================="
        echo "Step 3: Publishing Release Information"
        echo "=========================================="
        echo "Run Identifier: ${RUN_IDENTIFIER}"
        echo "Region: ${REGION}"
        echo "Source Stage: ${SOURCE_STAGE}"
        echo "Target Stage: ${TARGET_STAGE}"

        # Run publish_release_information with run_id
        # This script will:
        # 1. Load release info from S3 (uploaded in Step 2)
        # 2. Write image SHA to availability canaries bucket
        # 3. Publish SNS notifications
        publish_release_information --run-id "${RUN_IDENTIFIER}"

        echo "Step 3 completed: Release information published successfully"
        echo "success=true" >> ${GITHUB_OUTPUT}

        echo "=========================================="
        echo "All three steps completed successfully!"
        echo "=========================================="

    - name: Release Summary
      if: always()
      shell: bash
      run: |
        echo "=========================================="
        echo "Release Execution Summary"
        echo "=========================================="
        echo "Step 1 (Publish Images): ${{ steps.step1.outputs.success || 'failed/skipped' }}"
        echo "Step 2 (Generate Info):  ${{ steps.step2.outputs.success || 'failed/skipped' }}"
        echo "Step 3 (Publish Notifications): ${{ steps.step3.outputs.success || 'failed/skipped' }}"
        echo "=========================================="

        if [ "${{ steps.step1.outputs.success }}" != "true" ]; then
          echo "❌ Release failed at Step 1 (Publish Images)"
          echo "   Step 2 and Step 3 were skipped"
        elif [ "${{ steps.step2.outputs.success }}" != "true" ]; then
          echo "❌ Release failed at Step 2 (Generate Info)"
          echo "   Step 3 was skipped"
        elif [ "${{ steps.step3.outputs.success }}" != "true" ]; then
          echo "❌ Release failed at Step 3 (Publish Notifications)"
        else
          echo "✅ All steps completed successfully!"
        fi

    - name: Cleanup
      if: always()
      shell: bash
      run: |
        rm -rf ${PACKAGE_DIR} || true
        rm -f release_spec.yml || true
        echo "Cleanup completed"
