#### First image: sha256:d0358d5da83e45e86796a3d350384e9f1cacc72934da3af2357602f84d084601 ####
#### Patch contents for patch-1: sha256:83b6741e2d237c3898bca7b49ab3baa1e7186e8630020fa43eea1cb4c9b73484 ####
pip install idna==3.7 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-2: sha256:c0525175a8df250c24db0787e7b98c7e570c76d12402f507d524a53f104bc9e7 ####
pip install idna==3.7 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-3: sha256:c7f226e4144317cd02c9ab03d7b6b0a4133c13d0a80dcdbb8ee6851e7b6e9c7f ####
pip install idna==3.7 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-4: sha256:113e0041b75254eb4032c0539558b6f46517ddbebbdbc11e7b221508be3ca1a1 ####
pip install idna==3.7 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-5: sha256:56773f735f4fc28eae052bca6bfb5be0d7a63751ff9fc9bf5b1e960263601ef5 ####
pip install idna==3.7 requests==2.32.2 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-6: sha256:e8f53d39eb566a4a59f897b1de14c8850d7f0b5501ba60c66e076a37c434e650 ####
pip install idna==3.7 requests==2.32.3
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-7: sha256:364d4e64bb238fb3959babd896a3e9a79d70f522737fe1a214f2879e7002158a ####
pip install idna==3.7 requests==2.32.3
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-8: sha256:5c57fbb94d3021330de3ba3ac757085c6c07d0ae008f54df985aee80ec6e39b5 ####
pip install idna==3.7 requests==2.32.3
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-9: sha256:66b5a204b80bdeeedfe0784b2dc365fa70df0f3ff18b2dd38da5cab45c775f34 ####
pip install idna==3.7 requests==2.32.3 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-10: sha256:dab405e60e55fff586fcf70fafe84dcafb9ab941edda956124782b82090c99a7 ####
pip install idna==3.7 requests==2.32.3 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-11: sha256:7899ccf8a729e2fef867e3a5edfeb27856a36547bc9e93ee5f50a462aa6fd366 ####
pip install idna==3.7 requests==2.32.3 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-12: sha256:84a10cf80d12817ac0092b270130d78470b8fcdf18b15c29c2bee7d17b45d87f ####
pip install idna==3.7 requests==2.32.3 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-13: sha256:14204cb7079c0ab5a2ae8ed58984e0f13db722a64b52986163183a4513317a0e ####
pip install idna==3.7 requests==2.32.3 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-14: sha256:8318829aae4ffb15852a5fe98c4244fdf021a737f536451d04278d93df4f2e13 ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-15: sha256:1856fa2a5394eafa6321e5d2377095ca6768ab6b80d7e1ae0beae479acf7f695 ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==71.0.1 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgtk-3-0 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-16: sha256:e00ddefdfe842e1b1ddca3bc9f14b90e3694280ae85e44eb4a5d645ce897c779 ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==71.1.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgtk-3-0 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-17: sha256:c5788730c5425bb1616647434326a2cea3f5e9966748da36cc6239f60d1a4b96 ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==72.0.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgtk-3-0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-18: sha256:31a9b66749bae6abe43621876caf30738027e9266618ff807380a0d88932c44f ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==72.1.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgtk-3-0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-19: sha256:0fb128505c3703b48389ccc7b6087147e26f94c75168b42d91d56430a755b0b7 ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==72.1.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgtk-3-0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libssl1.1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-20: sha256:4ec94322b70c1d5dafaf2ba1b1fc654757a7078f2d5c35277b99f74760e351d0 ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==72.1.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libcurl3-gnutls libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgtk-3-0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libssl1.1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-21: sha256:324e4271444d98ca74e1da6d7de29a85f5971c2bbeb8f5443b9609fa06574543 ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==72.1.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libcurl3-gnutls libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libssl1.1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-22: sha256:054030afd53a9b31079c032db95277d121cb4826a4945c65fb99ce996d5a6a8b ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==72.2.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libcurl3-gnutls libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libssl1.1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-23: sha256:8ff45e2e87d7a9bacc8c279299511932ba8ef3a0ac7a05c3e62fc4fe22c51fba ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==72.2.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libcurl3-gnutls libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libssl1.1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-24: sha256:9c3133a50b59584e0a621394e3d1d71e96cf1ff59e20cb3383c874967a6295b2 ####
pip install certifi==2024.7.4 idna==3.8 requests==2.32.3 setuptools==73.0.1 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libcurl3-gnutls libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libssl1.1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-25: sha256:7153f1f288bf85aa8e0af4a6d36ec63738873004ba28808460b304d7d79bbeaa ####
pip install certifi==2024.7.4 idna==3.8 requests==2.32.3 setuptools==74.0.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libcurl3-gnutls libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libssl1.1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Current Patch contents ####
pip install certifi==2024.8.30 idna==3.8 requests==2.32.3 setuptools==74.0.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libcurl3-gnutls libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libssl1.1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
