#### First image: sha256:ac9d45320a0f9ccdd038a4f0930f5b88a78b2daac89a1672a66459c438c98a16 ####
#### Current Patch contents ####
echo N/A 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils bsdutils curl fdisk libbinutils libblkid1 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4 libfdisk1 libmount1 libsmartcols1 libssl-dev libssl1.1 libuuid1 libxml2 mount openssl util-linux uuid-dev vim-common vim-runtime vim xxd
