#### First image: sha256:3c350bf4d1802bd845424b2b65546cd2411ad945c7a84a568cc6d881aa41f4e4 ####
#### Patch contents for patch-1: sha256:2245ca8965cdf0f491a5685d30e01425fe70f2c350ccf395ddb54a43216ad5d7 ####
pip install idna==3.7 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-2: sha256:fc1705d0c850da08205fa23ae2e732735effab608a44b8ee4ef2b5292423765c ####
pip install idna==3.7 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-3: sha256:9377f39a88ab1a74fcdea00a21b3b5ade92c1bba770ac6e261376524d640fcad ####
pip install idna==3.7 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-4: sha256:35fe316ba21c2c98d9b46c2d409ec0acfa15e1bed8f5658ac3b0d45637753fa8 ####
pip install idna==3.7 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-5: sha256:f70c00bce25697e2cb7b483826c94d8e5bc36a2fe7b1592234279984c9962b63 ####
pip install idna==3.7 requests==2.32.2 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-6: sha256:3febe976ad46cb8d9b349c8e7bba2368b808a26b77d8a444eca0b532f40a3c81 ####
pip install idna==3.7 requests==2.32.3
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-7: sha256:ca809f1b75e2f1c6285971a291b229d2361664e30642e7afc01342338c25cf2c ####
pip install idna==3.7 requests==2.32.3
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-8: sha256:6267b2761fa30ef091ff52996f6ebe86f5356990124776053fbcb83c0e5ce8a2 ####
pip install idna==3.7 requests==2.32.3
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-9: sha256:6b41bc23c90157243d0649b639417c07eda19feef960cdf8de3ce94d47db99b0 ####
pip install idna==3.7 requests==2.32.3 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-10: sha256:14dbb02e0175a3c0a97f6d25ee461640b60d7f1810b880e463f58ac7d890949a ####
pip install idna==3.7 requests==2.32.3 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-11: sha256:1fb2705360692a8a6351588f828fd5dd1fa5997f6ab7a4183bea31dac0b5d16e ####
pip install idna==3.7 requests==2.32.3 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev
#### Patch contents for patch-12: sha256:d367fcf06f3d3010ee2cd9580cc4457f5d7f4a3f08f04fc5eab27edd29c0c092 ####
pip install idna==3.7 requests==2.32.3 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-13: sha256:70fcfff597244319857cd9387c2764c1a43270b4e2eec73c3884e6aee0c505b7 ####
pip install idna==3.7 requests==2.32.3 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-14: sha256:75cd7a0e51e9e2c111b1ad98c155822a8b3c06d99cf94feb51a226f5f5975941 ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-15: sha256:7ff60e414e5d265e4ae12b97434c10de1e92f36631997cd90e94183b5ab98b38 ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==71.0.1 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgtk-3-0 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-16: sha256:d2ad07c16b80268acccfa345f9b5c697f0f025f01894e02e52f261ec119a0730 ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==71.1.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgtk-3-0 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-17: sha256:db48f7b8d9b7e5ae21d0963845ab4a4621c689f1d8ab4f351273d0b5942df400 ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==72.0.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgtk-3-0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-18: sha256:398079cb604aa52b9532e103736b04188fb4c540892b1b5fdaac4eec9920c44c ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==72.1.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgtk-3-0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-19: sha256:a19bdadbee5b3fa154a6aad8c90bf775a80579249af62ab613de88278a59df5e ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==72.1.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgtk-3-0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libssl1.1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-20: sha256:8c317a1b2320b0eed17301acade0a438efa40c6b08fbdd2eb01b3a04004eac9f ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==72.1.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libcurl3-gnutls libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgtk-3-0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libssl1.1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-21: sha256:30dfd44b1c66e2f72a8678bdf140d90c6e84ac05060eccd6f7ad101b587e12c9 ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==72.1.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libcurl3-gnutls libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libssl1.1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-22: sha256:da38aacc67646ed2294e483385c159c0e6991f6ff9bd5105c7dd8dc56bae770d ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==72.2.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libcurl3-gnutls libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libssl1.1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-23: sha256:800cf8c1c774d287b714f471ae111e3fad7bde840c84678f92f77e028fcaccc1 ####
pip install certifi==2024.7.4 idna==3.7 requests==2.32.3 setuptools==72.2.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libcurl3-gnutls libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libssl1.1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-24: sha256:3a91f580fb537dc9e46af403fb7c5675b6c404e2d8e16632ae64f6042b8478b2 ####
pip install certifi==2024.7.4 idna==3.8 requests==2.32.3 setuptools==73.0.1 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libcurl3-gnutls libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libssl1.1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Patch contents for patch-25: sha256:172b93c333c3daa6eb68aaf34d6f2c224355e025d26825608c0ddaa7253fa99a ####
pip install certifi==2024.7.4 idna==3.8 requests==2.32.3 setuptools==74.0.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libcurl3-gnutls libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libssl1.1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
#### Current Patch contents ####
pip install certifi==2024.8.30 idna==3.8 requests==2.32.3 setuptools==74.0.0 urllib3==2.2.2
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk git-man git imagemagick-6-common libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcups2 libcurl3-gnutls libcurl4 libfdisk1 libgdk-pixbuf2.0-0 libglib2.0-0 libgnutls30 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmount1 libnghttp2-14 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libsmartcols1 libssl1.1 libtiff5 libuuid1 linux-libc-dev mount util-linux uuid-dev wget
