# https://aws.github.io/deep-learning-containers/reference/available_images/
# refer to the above page to pull latest Pytorch image

# docker image region us-west-2
FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:2.9.0-gpu-py312-cu130-ubuntu22.04-sagemaker

LABEL maintainer="Amazon AI"
LABEL dlc_major_version="1"

# version args
ARG TRANSFORMERS_VERSION=5.3.0
ARG DATASETS_VERSION=4.5.0
ARG HUGGINGFACE_HUB_VERSION=1.3.0
ARG DIFFUSERS_VERSION=0.37.0
ARG EVALUATE_VERSION=0.4.6
ARG ACCELERATE_VERSION=1.12.0
ARG TRL_VERSION=0.28.0
ARG PEFT_VERSION=0.18.1
ARG TRACKIO_VERSION=0.21.2
ARG FLASH_ATTN_VERSION=2.8.3
ARG NINJA_VERSION=1.13.0
ARG KERNELS_VERSION=0.10.5
ARG PYTHON=python3

# Pre-install kenlm without build isolation so it uses system cmake
RUN pip install --no-cache-dir --no-build-isolation kenlm

# Pre-install flash-attn withour build isolation to prevent `ModuleNotFoundError: No module named 'torch'`
RUN pip install --no-cache-dir --no-build-isolation flash-attn==${FLASH_ATTN_VERSION}

# Install Hugging Face libraries and dependencies
RUN pip install --no-cache-dir \
    huggingface_hub==${HUGGINGFACE_HUB_VERSION} \
    transformers[torch,sentencepiece,tokenizers,vision,timm,video,codecarbon,accelerate,mistral-common,chat_template,kernels,sklearn,audio,tiktoken,sagemaker]==${TRANSFORMERS_VERSION} \
    datasets==${DATASETS_VERSION} \
    diffusers==${DIFFUSERS_VERSION} \
    Jinja2 \
    tensorboard \
    bitsandbytes \
    evaluate==${EVALUATE_VERSION} \
    ninja==${NINJA_VERSION} \
    trl==${TRL_VERSION} \
    peft==${PEFT_VERSION} \
    trackio==${TRACKIO_VERSION}

# Override conflicting versions to satisfy datasets requirements
RUN pip install --no-cache-dir dill==0.3.8 multiprocess==0.70.16 \
 && pip install --no-cache-dir pathos==0.3.3 --no-deps \
 && PATHOS_META=$(find /usr/local/lib -type f -path "*pathos-0.3.3.dist-info/METADATA") \
 && sed -i 's/dill.*/dill/' $PATHOS_META \
 && sed -i 's/multiprocess.*/multiprocess/' $PATHOS_META

# Fix CVE-77744: Upgrade urllib3 to version 2.5.0 or higher
# Remove sigopt to avoid dependency conflict (it's not essential for core functionality)
# Fix CVE-2026-0994 - protobuf versions 6.33.5 and above have the fix for this vulnerability
# CVE patch
RUN pip install --upgrade pip \
 && pip uninstall -y sigopt || true \
 && pip uninstall -y ray pyctcdecode \
 && pip install --no-cache-dir -U \
    pyarrow \
    cryptography \
    pyopenssl \
    "Pillow>=10.3.0,<12.0.0" \
    wheel \
    setuptools \
    "s3fs>=2026.2.0" \
    "awscli>=1.44.60,<2" \
    "boto3>=1.42.70,<2" \
    "botocore>=1.42.70,<1.43.0" \
    "werkzeug>=3.1.4" \
    "filelock>=3.20.1" \
    "numpy<2" \
    "shap<0.50.0" \
    "urllib3>=2.5.0" \
    "protobuf>=6.33.5,<7.0"

ENV HF_HUB_USER_AGENT_ORIGIN="aws:sagemaker:gpu-cuda:training"

RUN apt-get update \
 && apt-get install -y --allow-change-held-packages --no-install-recommends \
    libgl1-mesa-glx \
    build-essential \
    ca-certificates \
    zlib1g-dev \
    openssl \
    python3-dev \
    pkg-config \
    check \
    curl \
    git \
    jq \
    unzip \
    vim \
    wget \
    libcrypt1 \
&& rm -rf /var/lib/apt/lists/*

COPY cuda-compatibility-lib.sh /usr/local/bin/cuda-compatibility-lib.sh
RUN chmod +x /usr/local/bin/cuda-compatibility-lib.sh

RUN apt-get update \
 && apt-get upgrade -y \
 && apt-get autoremove -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Fix CVE-2024-53920 and CVE-2025-1244: emacs is not essential for core functionality and has known
# vulnerabilities, so we remove it
RUN apt-get remove -y --purge emacs emacs-common \
 && apt-get autoremove -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN HOME_DIR=/root \
 && curl -o ${HOME_DIR}/oss_compliance.zip https://aws-dlinfra-utilities.s3.amazonaws.com/oss_compliance.zip \
 && unzip -o ${HOME_DIR}/oss_compliance.zip -d ${HOME_DIR}/ \
 && cp ${HOME_DIR}/oss_compliance/test/testOSSCompliance /usr/local/bin/testOSSCompliance \
 && chmod +x /usr/local/bin/testOSSCompliance \
 && chmod +x ${HOME_DIR}/oss_compliance/generate_oss_compliance.sh \
 && ${HOME_DIR}/oss_compliance/generate_oss_compliance.sh ${HOME_DIR} ${PYTHON} \
 && rm -rf ${HOME_DIR}/oss_compliance*
