name: Container Pull
description: Login to ECR, get image URI from current workflow artifacts, then pull the image onto host runner.

inputs:
  aws_region:
    description: AWS Region for docker image repository
    required: true
  aws_account_id:
    description: AWS Account ID for docker image registry
    required: true
  image_uri:
    description: Docker image URI to pull from ECR
    required: true

runs:
  using: composite
  steps:

    - name: ECR login
      shell: bash
      run: |
        aws ecr get-login-password --region ${{ inputs.aws_region }} | docker login --username AWS --password-stdin ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com

    - name: Pull image
      shell: bash
      run: |
        docker pull ${{ inputs.image_uri }}
