#### First image: sha256:f7a0191502c1998b8a0ff906b518886288e072e40a7980409c6a53253d66608a ####
#### Patch contents for patch-1: sha256:4971bd2138b2e4abdd534a223c1218d3cbff6eb0cc402cba74e1de511a22faa3 ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 libtiff5 linux-libc-dev wget
#### Patch contents for patch-2: sha256:1a5b621b7e15af17a989af9628ceef820984b2a589dd442a654098564fd4b5f2 ####
pip install certifi==2024.7.4 urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 libtiff5 linux-libc-dev wget
#### Patch contents for patch-3: sha256:596d7a69f462193b8c0077ade73c662a10b2116d514e1bcfe7a7828720681a9c ####
pip install certifi==2024.7.4 urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 libpython3.8-dev libpython3.8-minimal libpython3.8-stdlib libpython3.8 libtiff5 linux-libc-dev python3.8-dev python3.8-minimal python3.8 wget
#### Patch contents for patch-4: sha256:02d6a62d4d6c528fdd079e194e649b385f712881a988764e97d42d48ca2da349 ####
pip install certifi==2024.7.4 setuptools==71.0.4 urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 libgtk-3-0 libpython3.8-dev libpython3.8-minimal libpython3.8-stdlib libpython3.8 libtiff5 linux-libc-dev python3.8-dev python3.8-minimal python3.8 wget
#### Patch contents for patch-5: sha256:1a1a014fc5bdd8538c6883c84ed6022b67bc7d391f5dc21f0668510e645fb9f6 ####
pip install certifi==2024.7.4 setuptools==71.1.0 urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 libgtk-3-0 libpython3.8-dev libpython3.8-minimal libpython3.8-stdlib libpython3.8 libtiff5 linux-libc-dev python3.8-dev python3.8-minimal python3.8 wget
#### Patch contents for patch-6: sha256:c290f10bd8a78352e5a9c498b0aa581b2b983d6e4c4761589ccf734b226cc748 ####
pip install certifi==2024.7.4 setuptools==71.1.0 urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git imagemagick-6-common libcups2 libgtk-3-0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-dev libpython3.8-minimal libpython3.8-stdlib libpython3.8 libtiff5 linux-libc-dev python3.8-dev python3.8-minimal python3.8 wget
#### Patch contents for patch-7: sha256:cf6b9c41454d9926b19367ecf3573875368d39d326335f55b00927ad773b5828 ####
pip install certifi==2024.7.4 setuptools==72.1.0 urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git imagemagick-6-common libcups2 libgtk-3-0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-dev libpython3.8-minimal libpython3.8-stdlib libpython3.8 libtiff5 linux-libc-dev python3.8-dev python3.8-minimal python3.8 wget
#### Patch contents for patch-8: sha256:1eba1f81a8d80d13b3c6c0db19fe18dd651aa9b63a75cf3a303d7bedd8224ec5 ####
pip install certifi==2024.7.4 setuptools==72.1.0 urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git imagemagick-6-common libcups2 libgtk-3-0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-dev libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 libtiff5 linux-libc-dev openjdk-17-jdk-headless openjdk-17-jdk openjdk-17-jre-headless openjdk-17-jre python3.8-dev python3.8-minimal python3.8 wget
#### Patch contents for patch-9: sha256:d9d24ac0d4ac85a19d314ad8f4c17e806a36f8ad31e69adaf4abde29276a899a ####
pip install certifi==2024.7.4 setuptools==72.1.0 urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade curl git-man git imagemagick-6-common libcups2 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libgtk-3-0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-dev libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 libtiff5 linux-libc-dev openjdk-17-jdk-headless openjdk-17-jdk openjdk-17-jre-headless openjdk-17-jre python3.8-dev python3.8-minimal python3.8 wget
#### Patch contents for patch-10: sha256:4a82d789985c952f9a58992a3b33a8670c6e668c593fc45a8ba7d53cb75eb0cb ####
pip install certifi==2024.7.4 setuptools==72.1.0 urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade curl git-man git imagemagick-6-common libcups2 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-dev libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 libtiff5 linux-libc-dev openjdk-17-jdk-headless openjdk-17-jdk openjdk-17-jre-headless openjdk-17-jre python3.8-dev python3.8-minimal python3.8 wget
#### Patch contents for patch-11: sha256:ff4743d9232589f4972747c1a3a1f49b21d2350f40bbdb5bac269f835faf5be0 ####
pip install certifi==2024.7.4 setuptools==72.2.0 urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade curl git-man git imagemagick-6-common libcups2 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-dev libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 libtiff5 linux-libc-dev openjdk-17-jdk-headless openjdk-17-jdk openjdk-17-jre-headless openjdk-17-jre python3.8-dev python3.8-minimal python3.8 wget
#### Patch contents for patch-12: sha256:3f09e03210d46f4965e728389f4f32f8c35dd6802bfe6c845f069f36d0096edd ####
pip install certifi==2024.7.4 setuptools==74.0.0 urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade curl git-man git imagemagick-6-common libcups2 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-dev libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 libtiff5 linux-libc-dev openjdk-17-jdk-headless openjdk-17-jdk openjdk-17-jre-headless openjdk-17-jre python3.8-dev python3.8-minimal python3.8 wget
#### Current Patch contents ####
pip install certifi==2024.8.30 setuptools==74.0.0 urllib3==1.26.20
apt-get update && apt-get install -y --only-upgrade curl git-man git imagemagick-6-common libcups2 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libgssapi-krb5-2 libgtk-3-0 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-dev libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 libtiff5 linux-libc-dev openjdk-17-jdk-headless openjdk-17-jdk openjdk-17-jre-headless openjdk-17-jre python3.8-dev python3.8-minimal python3.8 wget
