#### First image: sha256:6c21bf0ab198df5f2a9a1ce9af83e99f5a34d4ec1cb00a9c4d07a3983316ed4c ####
#### Patch contents for patch-1: sha256:e09f326f9a15dfaad788b045ed133c97342c9938277311bf846580cb34ba3e0c ####
pip install urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 libtiff5 linux-libc-dev wget
#### Current Patch contents ####
pip install certifi==2024.7.4 urllib3==1.26.19
apt-get update && apt-get install -y --only-upgrade git-man git libcups2 libtiff5 linux-libc-dev wget
