account_id: &ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>
region: &REGION <set-$REGION-in-environment>
base_framework: &BASE_FRAMEWORK pytorch
framework: &FRAMEWORK !join [ "huggingface_", *BASE_FRAMEWORK]
version: &VERSION 2.3.0
short_version: &SHORT_VERSION "2.3"
contributor: huggingface
arch_type: x86

repository_info:
  inference_repository: &INFERENCE_REPOSITORY
    image_type: &INFERENCE_IMAGE_TYPE inference
    root: !join [ "huggingface/", *BASE_FRAMEWORK, "/", *INFERENCE_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join ["pr", "-", "huggingface", "-", *BASE_FRAMEWORK, "-", *INFERENCE_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]

context:
  inference_context: &INFERENCE_CONTEXT
    mms-entrypoint:
      source: ../../build_artifacts/inference/mms-entrypoint.py
      target: mms-entrypoint.py
    config:
      source: ../../build_artifacts/inference/config.properties
      target: config.properties
    deep_learning_container:
      source: ../../../src/deep_learning_container.py
      target: deep_learning_container.py

images:
  BuildHuggingFacePytorchCpuPy311InferenceDockerImage:
    <<: *INFERENCE_REPOSITORY
    build: &HUGGINGFACE_PYTORCH_CPU_INFERENCE_PY3 false
    image_size_baseline: 15000
    device_type: &DEVICE_TYPE cpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py311
    os_version: &OS_VERSION ubuntu22.04
    transformers_version: &TRANSFORMERS_VERSION 4.46.1
    tag: !join [ *VERSION, '-', 'transformers', *TRANSFORMERS_VERSION, '-', *DEVICE_TYPE, '-', *TAG_PYTHON_VERSION, '-', *OS_VERSION ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /Dockerfile., *DEVICE_TYPE ]
    context:
      <<: *INFERENCE_CONTEXT
  BuildHuggingFacePytorchGpuPy311Cu121InferenceDockerImage:
    <<: *INFERENCE_REPOSITORY
    build: &HUGGINGFACE_PYTORCH_GPU_INFERENCE_PY3 false
    image_size_baseline: &IMAGE_SIZE_BASELINE 15000
    device_type: &DEVICE_TYPE gpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py311
    cuda_version: &CUDA_VERSION cu121
    os_version: &OS_VERSION ubuntu20.04
    transformers_version: &TRANSFORMERS_VERSION 4.46.1
    tag: !join [ *VERSION, '-', 'transformers', *TRANSFORMERS_VERSION, '-', *DEVICE_TYPE, '-', *TAG_PYTHON_VERSION, '-',
                 *CUDA_VERSION, '-', *OS_VERSION ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /,
                         *CUDA_VERSION, /Dockerfile., *DEVICE_TYPE ]
    context:
      <<: *INFERENCE_CONTEXT
