account_id: &ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>
region: &REGION <set-$REGION-in-environment>
base_framework: &BASE_FRAMEWORK pytorch
framework: &FRAMEWORK !join [ "huggingface_", *BASE_FRAMEWORK]
version: &VERSION 1.13.1
short_version: &SHORT_VERSION "1.13"
contributor: &CONTRIBUTOR huggingface
arch_type: x86

repository_info:
  inference_repository: &INFERENCE_REPOSITORY
    image_type: &IMAGE_TYPE inference
    root: !join [ "huggingface/", *BASE_FRAMEWORK, "/", *IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join ["pr", "-", *CONTRIBUTOR, "-", *BASE_FRAMEWORK, "-", *IMAGE_TYPE, "-", "neuronx"]
    repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]

context:
  inference_context: &INFERENCE_CONTEXT
    neuron-monitor:
      source: ../../build_artifacts/inference/neuron-monitor.sh
      target: neuron-monitor.sh
    neuron-entrypoint:
      source: ../../build_artifacts/inference/neuron-entrypoint.py
      target: neuron-entrypoint.py
    config:
      source: ../../build_artifacts/inference/config.properties
      target: config.properties

images:
  BuildNeuronXHFPytorchPy310InferencefDockerImage:
    <<: *INFERENCE_REPOSITORY
    build: &HUGGINGFACE_PYTORCH_CPU_INFERENCE_PY3 false
    image_size_baseline: 14000
    device_type: &DEVICE_TYPE neuronx
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py310
    neuron_sdk_version: &NEURON_SDK_VERSION sdk2.15.0
    os_version: &OS_VERSION ubuntu20.04
    transformers_version: &TRANSFORMERS_VERSION 4.34.1
    tag: !join [ *VERSION, '-', 'transformers', *TRANSFORMERS_VERSION, '-', *DEVICE_TYPE, '-', *TAG_PYTHON_VERSION,"-", *NEURON_SDK_VERSION, '-', *OS_VERSION ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *NEURON_SDK_VERSION, /Dockerfile., *DEVICE_TYPE ]
    context:
      <<: *INFERENCE_CONTEXT
