account_id: &ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>
region: &REGION <set-$REGION-in-environment>
base_framework: &BASE_FRAMEWORK pytorch
framework: &FRAMEWORK !join [ "stabilityai_", *BASE_FRAMEWORK]
version: &VERSION 2.0.1
short_version: &SHORT_VERSION "2.0"
arch_type: x86

repository_info:
  inference_repository: &INFERENCE_REPOSITORY
    image_type: &INFERENCE_IMAGE_TYPE inference
    root: !join [ "stabilityai/", *BASE_FRAMEWORK, "/", *INFERENCE_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", "stabilityai", "-", *BASE_FRAMEWORK, "-", *INFERENCE_IMAGE_TYPE]
    repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]

context:
  inference_context: &INFERENCE_CONTEXT
    torchserve-entrypoint:
      source: docker/build_artifacts/torchserve-stabilityai-entrypoint.py
      target: torchserve-entrypoint.py

images:
  BuildStabilityaiPytorchGpuPy310InferenceDockerImage:
    <<: *INFERENCE_REPOSITORY
    build: &STABILITYAI_PYTORCH_GPU_INFERENCE_PY3 false
    image_size_baseline: 14000
    device_type: &DEVICE_TYPE gpu
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py310
    cuda_version: &CUDA_VERSION cu118
    os_version: &OS_VERSION ubuntu20.04
    sgm_version: &SGM_VERSION 0.1.0
    tag: !join [ *VERSION, "-", 'sgm',*SGM_VERSION, '-', *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *CUDA_VERSION, "-", *OS_VERSION, "-sagemaker" ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *CUDA_VERSION, /Dockerfile.,
                         *DEVICE_TYPE ]
    context:
          <<: *INFERENCE_CONTEXT                         
