image:
  name: "ray-sagemaker-gpu"
  description: "Ray for SageMaker (GPU)"

metadata:
  framework: "ray"
  framework_version: "2.55.1"
  os_version: "amzn2023"
  customer_type: "sagemaker"
  platform: "sagemaker"
  arch_type: "x86"
  device_type: "gpu"
  job_type: "inference"
  container_type: "serve-ml"
  prod_image: "ray:serve-ml-sagemaker-cuda"

build:
  dockerfile: "docker/ray/Dockerfile.cuda"
  target: "ray-sagemaker-gpu"
  python_version: "3.13.12"
  cuda_version: "12.9.1"
  dlc_major_version: "1"
  dlc_minor_version: "0"

release:
  release: true
  force_release: false
  public_registry: true
  private_registry: true
  enable_soci: true
  environment: "production"
