apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-west-2

nodeGroups:
  - name: nodegroup-1
    instanceType: m5.large
    minSize: 0
    maxSize: 10
    ssh:
      publicKeyName: MyKeyPair
    labels:
      processor: gpu
    taints:
      k8s: "true:NoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/processor: gpu
      k8s.io/cluster-autoscaler/node-template/taint/k8s: "true:NoSchedule"
    iam:
      withAddonPolicies:
        autoScaler: true
  - name: nodegroup-2
    instanceType: m5.large
    minSize: 1
    maxSize: 1
    ssh:
      publicKeyName: MyKeyPair