apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-west-2

nodeGroups:
  - name: nodegroup-static
    instanceType: m5.large
    minSize: 1
    maxSize: 1
    ssh:
      publicKeyName: MyKeyPair 
  - name: nodegroup-gpu
    instanceType: p3.16xlarge
    ami: ami-061798711b2adafb4
    volumeSize: 80
    minSize: 0
    maxSize: 100
    ssh:
      publicKeyName: MyKeyPair
    labels:
      test_type: gpu
    tags:
      k8s.io/cluster-autoscaler/node-template/label/test_type: gpu
    iam:
      withAddonPolicies:
        autoScaler: true
  - name: nodegroup-neuron
    instanceType: inf1.xlarge
    #Neuron AMI used (private image)
    #ami: ami-092059396c7e51f52
    ami: ami-061798711b2adafb4
    volumeSize: 500
    minSize: 0
    maxSize: 100
    ssh:
      publicKeyName: MyKeyPair
    labels:
      test_type: neuron
    tags:
      k8s.io/cluster-autoscaler/node-template/label/test_type: neuron
    iam:
      withAddonPolicies:
        autoScaler: true
