#### First image: sha256:c9a14a9d1dc6ea2f5fd2eae9418542ef5e648bc8b2870bfbd85e475fd3124a31 ####
#### Patch contents for patch-1: sha256:20face9a8373fca83c40278f0da436604ef39506f96974c353f430044f8cfa3d ####
echo N/A
apt-get update && apt-get install -y --only-upgrade imagemagick-6-common libmagickcore-6.q16-6 libmagickwand-6.q16-6
#### Patch contents for patch-2: sha256:6b1aa67580c8f6269db587c5a889cd6d7138a8e4f58e916adcf1548fa6e894c9 ####
echo N/A
apt-get update && apt-get install -y --only-upgrade imagemagick-6-common libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 python3.8-minimal python3.8
#### Patch contents for patch-3: sha256:c0df9d65bf20aa9e4af03ff6134bbd4a34b594f4a48d6a90f55cf5628bb330c0 ####
echo N/A
apt-get update && apt-get install -y --only-upgrade curl imagemagick-6-common libcurl3-gnutls libcurl4-openssl-dev libcurl4 libgssapi-krb5-2 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 linux-libc-dev python3.8-minimal python3.8
#### Patch contents for patch-4: sha256:783345578a44dec714d85bbeab95040afc5052e1400ff0fc735f132f706e16c5 ####
echo N/A
apt-get update && apt-get install -y --only-upgrade curl imagemagick-6-common libcurl3-gnutls libcurl4-openssl-dev libcurl4 libgssapi-krb5-2 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 linux-libc-dev python3.8-minimal python3.8
#### Patch contents for patch-5: sha256:6b38dfbeeb0f677894f20f72cb095737d86b5ed4abc47bd14bfc3c723ff69e42 ####
echo N/A
apt-get update && apt-get install -y --only-upgrade curl imagemagick-6-common libcurl3-gnutls libcurl4-openssl-dev libcurl4 libgssapi-krb5-2 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 linux-libc-dev python3.8-minimal python3.8
#### Patch contents for patch-6: sha256:168859e6a3f676c349e3449d22434bd623e8d52ac003726168c3f07461debb16 ####
echo N/A
apt-get update && apt-get install -y --only-upgrade curl imagemagick-6-common libcurl3-gnutls libcurl4-openssl-dev libcurl4 libgssapi-krb5-2 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 linux-libc-dev python3.8-minimal python3.8
#### Patch contents for patch-7: sha256:8896cc4a79f388171ed5f5c037c9c52eae715a5ff4fb34029afb87b4e824561c ####
echo N/A
apt-get update && apt-get install -y --only-upgrade curl imagemagick-6-common libcurl3-gnutls libcurl4-openssl-dev libcurl4 libgssapi-krb5-2 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 linux-libc-dev python3.8-minimal python3.8
#### Current Patch contents ####
echo N/A
apt-get update && apt-get install -y --only-upgrade curl imagemagick-6-common libcurl3-gnutls libcurl4-openssl-dev libcurl4 libgssapi-krb5-2 libk5crypto3 libkrb5-3 libkrb5support0 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libpython3.8-minimal libpython3.8-stdlib libpython3.8 libssl1.1 linux-libc-dev python3.8-minimal python3.8
