#### First image: sha256:a3d03c99be5f56281e409581d12cfd40c053c6ddf4871fb186e2a07de3491040 ####
#### Patch contents for patch-1: sha256:1e9b25e408fb4af5bbf71b4ce20f114b2c532c1bff66c8c9904a5153d160885e ####
echo N/A
apt-get update && apt-get install -y --only-upgrade linux-libc-dev
#### Patch contents for patch-2: sha256:8769a107bfec548ae5365d49853ae22788473de47bd7fa108f3b97501023ee63 ####
echo N/A
apt-get update && apt-get install -y --only-upgrade linux-libc-dev vim-common vim-runtime vim xxd
#### Patch contents for patch-3: sha256:08047ffa3be5f9833f2e844bddbf5092037ef530be42136ef16f4d28bc5a5926 ####
pip install pillow==10.3.0
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk libblkid1 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libmount1 libsmartcols1 libuuid1 linux-libc-dev mount util-linux vim-common vim-runtime vim xxd
#### Patch contents for patch-4: sha256:adfe870a60f2110d19517d4fb83ad6221cddb1bbd5b312f7507f1e0ce05049e5 ####
pip install pillow==10.3.0
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk libblkid1 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libmount1 libsmartcols1 libuuid1 mount util-linux vim-common vim-runtime vim xxd
#### Patch contents for patch-5: sha256:b0613a2ea97d98d92c2af1dbb5b372c74a6871a55aacab362b435a8f874d67df ####
pip install idna==3.7 pillow==10.3.0 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk libblkid1 libc6 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgnutls30 libmount1 libnss3 libsmartcols1 libuuid1 mount util-linux vim-common vim-runtime vim xxd
#### Patch contents for patch-6: sha256:88663263b1ec9206fdf6532e33891f3df081f1febb903ec8cccb2cd65680f43e ####
pip install idna==3.7 pillow==10.3.0 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk libblkid1 libc6 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgnutls30 libmount1 libnghttp2-14 libnss3 libsmartcols1 libuuid1 linux-libc-dev mount util-linux vim-common vim-runtime vim xxd
#### Patch contents for patch-7: sha256:28da5e4778f0212381e7accd6f8f181245d49683e4fdeea8a818fcefaceb0001 ####
pip install idna==3.7 pillow==10.3.0 tqdm==4.66.4 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libgnutls30 libmount1 libnghttp2-14 libnss3 libsmartcols1 libuuid1 linux-libc-dev mount util-linux vim-common vim-runtime vim xxd
#### Patch contents for patch-8: sha256:240abb9076c0f2f04259be8200f0321ad90ad132d4e6b0d5e4125985090e33ca ####
pip install idna==3.7 pillow==10.3.0 tqdm==4.66.4 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libnss3 libsmartcols1 libuuid1 linux-libc-dev mount util-linux vim-common vim-runtime vim xxd
#### Current Patch contents ####
pip install idna==3.7 pillow==10.3.0 tqdm==4.66.4 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade bsdutils curl fdisk libblkid1 libc-bin libc-dev-bin libc6-dev libc6 libcurl3-gnutls libcurl4-openssl-dev libcurl4 libfdisk1 libglib2.0-0 libgnutls30 libmount1 libnghttp2-14 libnss3 libsmartcols1 libuuid1 linux-libc-dev mount util-linux vim-common vim-runtime vim xxd
