nav:
  - Home: index.md
  - Getting Started:
    - get_started/index.md
    - Installation: get_started/installation.md
    - Quick Start: get_started/quickstart.md
  - Tutorials: tutorials
# nav:
#   - Training:
#     - EKS Training: tutorials/content/training/eks/README.md
#   - Inference:
#     - vLLM on SageMaker: tutorials/content/vllm-samples/sagemaker/README.md
#     - DeepSeek on EKS: tutorials/content/vllm-samples/deepseek/eks/README.md
#     - Fraud Detection Demo: tutorials/content/vllm-samples/deepseek/eks/fraud-detection-demo/README.md
#   - Integrations:
#     - MLflow: tutorials/content/mlflow/dlc-with-mlflow/README.md
#     - SOCI: tutorials/content/SOCI/README.md
  - Reference:
    - Available Images: reference/available_images.md
    - Support Policy: reference/support_policy.md
