nav:
  - Home: index.md
  - Getting Started:
    - get_started/index.md
  - Tutorials: tutorials
  - Reference:
    - Available Images: reference/available_images.md
    - Support Policy: reference/support_policy.md
