name: ECR Authentication
description: Login to ECR, if image_uri is provided pull the image onto host runner.

inputs:
  aws-account-id:
    description: AWS Account ID for docker image registry
    required: true
  aws-region:
    description: AWS Region for docker image repository
    required: true
  image-uri:
    description: Docker image URI to pull from ECR
    required: false

runs:
  using: composite
  steps:

    - name: ECR login
      shell: bash
      run: |
        aws ecr get-login-password --region ${{ inputs.aws_region }} | docker login --username AWS --password-stdin ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com

    - name: Pull image
      if: inputs.image_uri != ''
      shell: bash
      run: |
        docker pull ${{ inputs.image_uri }}
