account_id: &ACCOUNT_ID <set-$ACCOUNT_ID-in-environment>
region: &REGION <set-$REGION-in-environment>
framework: &FRAMEWORK pytorch
version: &VERSION 1.11.0
os_version: &OS_VERSION ubuntu20.04
short_version: &SHORT_VERSION "1.11"
arch_type: x86

repository_info:
  training_repository: &TRAINING_REPOSITORY
    image_type: &TRAINING_IMAGE_TYPE training
    root: !join [ *FRAMEWORK, "/", *TRAINING_IMAGE_TYPE ]
    repository_name: &REPOSITORY_NAME !join [pr, "-", *FRAMEWORK, "-", *TRAINING_IMAGE_TYPE, "-", neuron]
    repository: &REPOSITORY !join [ *ACCOUNT_ID, .dkr.ecr., *REGION, .amazonaws.com/, *REPOSITORY_NAME ]

context:
  training_context: &TRAINING_CONTEXT
    changehostname:
      source: docker/build_artifacts/changehostname.c
      target: changehostname.c
    start_with_right_hostname:
      source: docker/build_artifacts/start_with_right_hostname.sh
      target: start_with_right_hostname.sh
    deep_learning_container:
      source: ../../src/deep_learning_container.py
      target: deep_learning_container.py

images:
  BuildNeuronPTTrainingPy3DockerImage:
    <<: *TRAINING_REPOSITORY
    build: &PYTORCH_INF_TRAINING_PY3 false
    image_size_baseline: 10000
    device_type: &DEVICE_TYPE neuron
    python_version: &DOCKER_PYTHON_VERSION py3
    tag_python_version: &TAG_PYTHON_VERSION py38
    neuron_sdk_version: &NEURON_SDK_VERSION sdk2.4.0
    os_version: &OS_VERSION ubuntu20.04
    tag: !join [ *VERSION, "-", *DEVICE_TYPE, "-", *TAG_PYTHON_VERSION, "-", *NEURON_SDK_VERSION, "-", *OS_VERSION ]
    docker_file: !join [ docker/, *SHORT_VERSION, /, *DOCKER_PYTHON_VERSION, /, *NEURON_SDK_VERSION, /Dockerfile., neuron ]
    context:
      <<: *TRAINING_CONTEXT