name: "Auto Release - SGLang SageMaker"

on:
  schedule:
    - cron: '00 20 * * 2,4'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline-sglang.yml
    with:
      config-file: .github/config/image/sglang/sagemaker-amzn2023.yml
      tag-suffix: ${{ github.run_id }}
      release: true
    secrets: inherit
