name: dlc-format-check

on: [pull_request]

jobs:
  python-formatting:
    runs-on: ubuntulatest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@25.1.0
        with:
          options: "--check --verbose -l 100"
