name: dlc-format-check

on: [pull_request]

jobs:
  python-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@23.12.1
        with:
          options: "--check --verbose -l 100"
