name: GHA

on:
  push:
    branches:
      - gha
  pull_request:
    branches:
      - gha

permissions:
  contents: read

jobs:  
  gatekeeper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pr-permission-gate
  
  job1:
    needs: [gatekeeper]
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      - run: .github/scripts/runner_setup.sh
  
  job2:
    needs: [job1]
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-build-runner
    steps:
      - uses: actions/checkout@v4
      - run: .github/scripts/runner_setup.sh
      - run: |
          cat README.md
  
  job3:
    needs: [job2]
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-g6xl-runner
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pr-permission-gate 
        with:
          required-level: admin
      - run: .github/scripts/runner_setup.sh
      - run: |
          nvidia-smi
