name: noop
on: [push]
jobs:
  noop:
    runs-on:
      - codebuild-test1-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: checkout github code
        uses: actions/checkout@v4
      - name: check github files
        shell: bash
        run: |
          cat README.md
