name: "PR - PyTorch SageMaker CPU"

on:
  # TEMP: Enable after all frameworks are refactored
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
    paths:
      - ".github/config/image/pytorch/*-sagemaker-cpu.yml"
      - ".github/workflows/pytorch.pipeline.yml"
      - ".github/workflows/pytorch.pr-sagemaker-cpu.yml"
      - "docker/pytorch/*/Dockerfile.cpu"
      - "scripts/docker/common/**"
      - "scripts/docker/pytorch/**"
      - "test/pytorch/**"
      - "test/sanity/**"
      - "test/telemetry/**"
      - "!docs/**"

permissions:
  contents: read
  pull-requests: read

jobs:
  gatekeeper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          fetch-depth: 1
      - uses: ./.github/actions/pr-permission-gate

  check-changes:
    needs: [gatekeeper]
    runs-on: ubuntu-latest
    outputs:
      build-change: ${{ steps.changes.outputs.build-change }}
      sanity-test-change: ${{ steps.changes.outputs.sanity-test-change }}
      telemetry-test-change: ${{ steps.changes.outputs.telemetry-test-change }}
      unit-test-change: ${{ steps.changes.outputs.unit-test-change }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            build-change:
              - ".github/config/image/pytorch/*-sagemaker-cpu.yml"
              - "docker/pytorch/*/Dockerfile.cpu"
              - "scripts/docker/common/**"
              - "scripts/docker/pytorch/**"
            sanity-test-change:
              - "test/sanity/**"
            telemetry-test-change:
              - "test/telemetry/**"
            unit-test-change:
              - "test/pytorch/unit/**"

  pipeline:
    needs: [check-changes]
    uses: ./.github/workflows/pytorch.pipeline.yml
    with:
      config-file: .github/config/image/pytorch/2.11-sagemaker-cpu.yml
      tag-suffix: pr-${{ github.event.pull_request.number }}
      build: ${{ needs.check-changes.outputs.build-change == 'true' }}
      run-efa-test: false
      run-multi-gpu-test: false
      run-multi-node-test: false
      run-sanity-test: ${{ needs.check-changes.outputs.build-change == 'true' || needs.check-changes.outputs.sanity-test-change == 'true' }}
      run-security-test: ${{ needs.check-changes.outputs.build-change == 'true' }}
      run-single-gpu-test: false
      run-telemetry-test: ${{ needs.check-changes.outputs.build-change == 'true' || needs.check-changes.outputs.telemetry-test-change == 'true' }}
      run-unit-test: ${{ needs.check-changes.outputs.build-change == 'true' || needs.check-changes.outputs.unit-test-change == 'true' }}
      release: false
    secrets: inherit
