name: Release - XGBoost SageMaker

on:
  push:
    branches: [main]
    paths:
      - "docker/xgboost/**"
      - "test/xgboost/**"
      - ".github/config/sagemaker-xgboost.yml"
      - ".github/workflows/release-sagemaker-xgboost.yml"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

env:
  FORCE_COLOR: "1"
  CONFIG_FILE: ".github/config/sagemaker-xgboost.yml"
  XGBOOST_CONTAINER_REPO: "https://github.com/aws/sagemaker-xgboost-container.git"

jobs:
  load-config:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-load-config-${{ github.run_id }}
      cancel-in-progress: true
    outputs:
      config: ${{ steps.load.outputs.config }}
      framework: ${{ steps.parse.outputs.framework }}
      framework-version: ${{ steps.parse.outputs.framework-version }}
      python-version: ${{ steps.parse.outputs.python-version }}
      cuda-version: ${{ steps.parse.outputs.cuda-version }}
      os-version: ${{ steps.parse.outputs.os-version }}
      container-type: ${{ steps.parse.outputs.container-type }}
      device-type: ${{ steps.parse.outputs.device-type }}
      arch-type: ${{ steps.parse.outputs.arch-type }}
      contributor: ${{ steps.parse.outputs.contributor }}
      customer-type: ${{ steps.parse.outputs.customer-type }}
      prod-image: ${{ steps.parse.outputs.prod-image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Load configuration
        id: load
        uses: ./.github/actions/load-config
        with:
          config-file: ${{ env.CONFIG_FILE }}

      - name: Parse configuration
        id: parse
        run: |
          echo '${{ steps.load.outputs.config }}' > config.json
          echo "framework=$(jq -r '.common.framework' config.json)" >> $GITHUB_OUTPUT
          echo "framework-version=$(jq -r '.common.framework_version' config.json)" >> $GITHUB_OUTPUT
          echo "python-version=$(jq -r '.common.python_version' config.json)" >> $GITHUB_OUTPUT
          echo "cuda-version=$(jq -r '.common.cuda_version' config.json)" >> $GITHUB_OUTPUT
          echo "os-version=$(jq -r '.common.os_version' config.json)" >> $GITHUB_OUTPUT
          echo "container-type=$(jq -r '.common.job_type' config.json)" >> $GITHUB_OUTPUT
          echo "device-type=$(jq -r '.common.device_type // "cpu"' config.json)" >> $GITHUB_OUTPUT
          echo "arch-type=$(jq -r '.common.arch_type // "x86"' config.json)" >> $GITHUB_OUTPUT
          echo "contributor=$(jq -r '.common.contributor // "None"' config.json)" >> $GITHUB_OUTPUT
          echo "customer-type=$(jq -r '.common.customer_type // ""' config.json)" >> $GITHUB_OUTPUT
          echo "prod-image=$(jq -r '.common.prod_image' config.json)" >> $GITHUB_OUTPUT

  build-image:
    needs: [load-config]
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-build-runner
        buildspec-override:true
    concurrency:
      group: ${{ github.workflow }}-build-image-${{ github.run_id }}
      cancel-in-progress: true
    outputs:
      ci-image: ${{ steps.build.outputs.image-uri }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build image
        id: build
        uses: ./.github/actions/build-image
        with:
          framework: ${{ needs.load-config.outputs.framework }}
          target: xgboost-sagemaker
          base-image: nvidia/cuda:12.6.3-base-ubuntu20.04
          framework-version: ${{ needs.load-config.outputs.framework-version }}
          container-type: ${{ needs.load-config.outputs.container-type }}
          aws-account-id: ${{ vars.CI_AWS_ACCOUNT_ID }}
          aws-region: ${{ vars.AWS_REGION }}
          tag-pr: ${{ needs.load-config.outputs.framework }}-${{ needs.load-config.outputs.framework-version }}-${{ needs.load-config.outputs.device-type }}-${{ needs.load-config.outputs.python-version }}-${{ needs.load-config.outputs.cuda-version }}-${{ needs.load-config.outputs.os-version }}-sagemaker-${{ github.run_id }}
          dockerfile-path: docker/xgboost/Dockerfile
          arch-type: ${{ needs.load-config.outputs.arch-type }}
          device-type: ${{ needs.load-config.outputs.device-type }}
          cuda-version: ${{ needs.load-config.outputs.cuda-version }}
          python-version: ${{ needs.load-config.outputs.python-version }}
          os-version: ${{ needs.load-config.outputs.os-version }}
          contributor: ${{ needs.load-config.outputs.contributor }}
          customer-type: ${{ needs.load-config.outputs.customer-type }}

  unit-test:
    needs: [build-image, load-config]
    if: success()
    timeout-minutes: 15
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:default-runner
        buildspec-override:true
    concurrency:
      group: ${{ github.workflow }}-unit-test-${{ github.run_id }}
      cancel-in-progress: true
    steps:
      - name: Checkout DLC source
        uses: actions/checkout@v5

      - name: Clone sagemaker-xgboost-container
        run: rm -rf /tmp/xgboost-unit && git clone --depth 1 ${{ env.XGBOOST_CONTAINER_REPO }} /tmp/xgboost-unit

      - name: ECR login
        uses: ./.github/actions/ecr-authenticate
        with:
          aws-account-id: ${{ vars.CI_AWS_ACCOUNT_ID }}
          aws-region: ${{ vars.AWS_REGION }}
          image-uri: ${{ needs.build-image.outputs.ci-image }}

      - name: Build test image
        run: |
          CI_IMAGE_URI="${{ needs.build-image.outputs.ci-image }}"
          cd /tmp/xgboost-unit
          printf "FROM ${CI_IMAGE_URI}\nADD . /app\nWORKDIR /app\nRUN python3 -m pip install .[test]" > Dockerfile.test
          docker build -t test-xgboost -f Dockerfile.test .

      - name: Run unit tests
        run: |
          docker run --rm test-xgboost sh -c \
            'python3 -m pytest --cov=sagemaker_xgboost_container --cov-fail-under=60 test/unit'

      - name: Run flake8
        run: |
          docker run --rm test-xgboost sh -c 'python3 -m flake8 setup.py src test'

  security-test:
    needs: [build-image, load-config]
    if: success()
    concurrency:
      group: ${{ github.workflow }}-security-test-${{ github.run_id }}
      cancel-in-progress: true
    uses: ./.github/workflows/reusable-security-tests.yml
    with:
      image-uri: ${{ needs.build-image.outputs.ci-image }}
      aws-account-id: ${{ vars.CI_AWS_ACCOUNT_ID }}
      aws-region: ${{ vars.AWS_REGION }}
      framework: ${{ needs.load-config.outputs.framework }}
      framework-version: ${{ needs.load-config.outputs.framework-version }}

  container-test-training:
    needs: [build-image, load-config]
    if: success()
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        test-case:
          - test_single_file_libsvm
          - test_single_file_libsvm_weights
          - test_single_file_libsvm_hpo_param
          - test_single_file_libsvm_multiclass_hpo
          - test_single_file_libsvm_iterate_objectives
          - test_single_file_libsvm_threshold_eval_metric
          - test_single_file_libsvm_verbosity
          - test_multi_files_libsvm
          - test_single_file_csv
          - test_single_file_csv_weights
          - test_multi_file_csv
          - test_single_file_csv_space_separated
          - test_single_file_csv_sci_notation
          - test_single_file_csv_empty_cells
          - test_checkpoint_and_reload
          - test_no_training_data
          - test_no_validation_data
          - test_invalid_data_csv_content_type
          - test_csv_alpha_with_csv_content_type
          - test_csv_data_with_libsvm_content_type
          - test_invalid_data_with_libsvm_content_type
          - test_invalid_hyperparameter
          - test_missing_num_round
          - test_multiclass_without_num_class
          - test_pipe_mode_rejected
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:default-runner
        buildspec-override:true
    concurrency:
      group: ${{ github.workflow }}-container-training-${{ matrix.test-case }}-${{ github.run_id }}
      cancel-in-progress: true
    steps:
      - name: Checkout DLC source
        uses: actions/checkout@v5

      - name: ECR login
        uses: ./.github/actions/ecr-authenticate
        with:
          aws-account-id: ${{ vars.CI_AWS_ACCOUNT_ID }}
          aws-region: ${{ vars.AWS_REGION }}
          image-uri: ${{ needs.build-image.outputs.ci-image }}

      - name: Pull image
        run: docker pull ${{ needs.build-image.outputs.ci-image }}

      - name: Install test dependencies
        run: |
          uv venv --python 3.12
          source .venv/bin/activate
          uv pip install -r test/requirements.txt docker pytest boto3

      - name: Run ${{ matrix.test-case }}
        run: |
          source .venv/bin/activate
          cd test/
          python3 -m pytest -vs -rA \
            --image ${{ needs.build-image.outputs.ci-image }} \
            -k "${{ matrix.test-case }}" \
            xgboost/container/test_training.py

  container-test-scoring:
    needs: [build-image, load-config]
    if: success()
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        test-case:
          - test_execution_parameters
          - test_csv_inference
          - test_libsvm_inference
          - test_recordio_protobuf_inference
          - test_binary_classification
          - test_csv_20mb_payload
          - test_unsupported_content_type
          - test_empty_payload
          - test_invalid_feature_dimension
          - test_libsvm_payload_with_csv_content_type
          - test_invalid_payload_with_csv_content_type
          - test_csv_payload_with_libsvm_content_type
          - test_invalid_payload_with_libsvm_content_type
          - test_invalid_accept_selectable_inference
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:default-runner
        buildspec-override:true
    concurrency:
      group: ${{ github.workflow }}-container-scoring-${{ matrix.test-case }}-${{ github.run_id }}
      cancel-in-progress: true
    steps:
      - name: Checkout DLC source
        uses: actions/checkout@v5

      - name: ECR login
        uses: ./.github/actions/ecr-authenticate
        with:
          aws-account-id: ${{ vars.CI_AWS_ACCOUNT_ID }}
          aws-region: ${{ vars.AWS_REGION }}
          image-uri: ${{ needs.build-image.outputs.ci-image }}

      - name: Pull image
        run: docker pull ${{ needs.build-image.outputs.ci-image }}

      - name: Install test dependencies
        run: |
          uv venv --python 3.12
          source .venv/bin/activate
          uv pip install -r test/requirements.txt docker pytest boto3 requests

      - name: Run ${{ matrix.test-case }}
        run: |
          source .venv/bin/activate
          cd test/
          python3 -m pytest -vs -rA \
            --image ${{ needs.build-image.outputs.ci-image }} \
            -k "${{ matrix.test-case }}" \
            xgboost/container/test_scoring.py

  container-test-batch-transform:
    needs: [build-image, load-config]
    if: success()
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        test-case:
          - test_libsvm_batch
          - test_recordio_protobuf_batch
          - test_csv_batch
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:default-runner
        buildspec-override:true
    concurrency:
      group: ${{ github.workflow }}-container-batch-${{ matrix.test-case }}-${{ github.run_id }}
      cancel-in-progress: true
    steps:
      - name: Checkout DLC source
        uses: actions/checkout@v5

      - name: ECR login
        uses: ./.github/actions/ecr-authenticate
        with:
          aws-account-id: ${{ vars.CI_AWS_ACCOUNT_ID }}
          aws-region: ${{ vars.AWS_REGION }}
          image-uri: ${{ needs.build-image.outputs.ci-image }}

      - name: Pull image
        run: docker pull ${{ needs.build-image.outputs.ci-image }}

      - name: Install test dependencies
        run: |
          uv venv --python 3.12
          source .venv/bin/activate
          uv pip install -r test/requirements.txt docker pytest boto3 requests

      - name: Run ${{ matrix.test-case }}
        run: |
          source .venv/bin/activate
          cd test/
          python3 -m pytest -vs -rA \
            --image ${{ needs.build-image.outputs.ci-image }} \
            -k "${{ matrix.test-case }}" \
            xgboost/container/test_batch_transform.py

  # benchmark-test:
  #   needs: [build-image, load-config]
  #   if: success()
  #   timeout-minutes: 150
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       test-module:
  #         - test_training_objective
  #         - test_training_tree_method
  #         - test_training_max_depth
  #         - test_training_num_round
  #         - test_training_data_size
  #         - test_training_instance_type
  #         - test_training_content_type
  #   runs-on:
  #     - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
  #       fleet:default-runner
  #       buildspec-override:true
  #   concurrency:
  #     group: ${{ github.workflow }}-benchmark-${{ matrix.test-module }}-${{ github.run_id }}
  #     cancel-in-progress: true
  #   steps:
  #     - name: Checkout DLC source
  #       uses: actions/checkout@v5
  #
  #     - name: Install test dependencies
  #       run: |
  #         uv venv --python 3.12
  #         source .venv/bin/activate
  #         uv pip install -r test/requirements.txt
  #         uv pip install -r test/xgboost/requirements.txt
  #
  #     - name: Run ${{ matrix.test-module }}
  #       run: |
  #         source .venv/bin/activate
  #         cd test/
  #         python3 -m pytest -vs -rA \
  #           --image-uri ${{ needs.build-image.outputs.ci-image }} \
  #           xgboost/benchmarks/${{ matrix.test-module }}.py

  # TODO: Add integration-test job once integ tests are implemented
  # TODO: Add generate-release-spec and release-image jobs when release is ready
