name: "Auto Release - SGLang EC2 AL2023"

on:
  schedule:
    - cron: '00 19 * * 2,4'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  pipeline:
    uses: ./.github/workflows/sglang.pipeline.yml
    with:
      config-file: .github/config/image/sglang/ec2-amzn2023.yml
      tag-suffix: ${{ github.run_id }}
      release: true
    secrets: inherit
