name: Mark and Remove Stale PRs
on:
  schedule:
  - cron: '0 19 * * 0'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: PR Check
      uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This PR has been marked stale as a result of being open for 30 days without activity or updates. Please remove the stale label or comment in order to keep this open, otherwise the PR will be closed in 5 days.'
        close-pr-message: 'This PR has had no activity or updates in the last 5 days since being marked stale. Closing this PR as a result.'
        stale-pr-label: 'no-pr-activity'
        days-before-pr-stale: 30
        days-before-pr-close: 5
        days-before-issue-stale: -1
        days-before-issue-close: -1
        operations-per-run: 200
