name: "PR - TEI 1.9.3"

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
    paths:
      - ".github/config/image/tei/**"
      - ".github/workflows/tei.pipeline.yml"
      - ".github/workflows/tei.pr-1.9.3.yml"
      - ".github/workflows/tei.tests-sagemaker.yml"
      - "docker/tei/1.9.3/**"
      - "scripts/ci/build/tei/**"
      - "test/tei/**"
      - "test/sanity/**"
      - "test/security/data/ecr_scan_allowlist/tei/**"
      - "!docs/**"

permissions:
  contents: read
  pull-requests: read

jobs:
  gatekeeper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          fetch-depth: 1
      - uses: ./.github/actions/pr-permission-gate

  check-changes:
    needs: [gatekeeper]
    runs-on: ubuntu-latest
    outputs:
      build-change: ${{ steps.changes.outputs.build-change }}
      sagemaker-test-change: ${{ steps.changes.outputs.sagemaker-test-change }}
      sanity-test-change: ${{ steps.changes.outputs.sanity-test-change }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            build-change:
              - ".github/config/image/tei/**"
              - "docker/tei/1.9.3/**"
              - "scripts/ci/build/tei/**"
              - "test/security/data/ecr_scan_allowlist/tei/**"
            sagemaker-test-change:
              - "test/tei/**"
              - ".github/workflows/tei.tests-sagemaker.yml"
            sanity-test-change:
              - "test/sanity/**"

  discover:
    needs: [gatekeeper]
    runs-on: ubuntu-latest
    outputs:
      configs: ${{ steps.discover.outputs.configs }}
    steps:
      - uses: actions/checkout@v6
      - id: discover
        uses: ./.github/actions/discover-configs
        with:
          pattern: ".github/config/image/tei/sagemaker-1.9.3-*.yml"

  pipeline:
    needs: [check-changes, discover]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.discover.outputs.configs) }}
    uses: ./.github/workflows/tei.pipeline.yml
    with:
      config-file: ${{ matrix.config_file }}
      tag-suffix: pr-${{ github.event.pull_request.number }}
      build: ${{ needs.check-changes.outputs.build-change == 'true' }}
      run-sanity-test: ${{ needs.check-changes.outputs.build-change == 'true' || needs.check-changes.outputs.sanity-test-change == 'true' }}
      run-security-test: ${{ needs.check-changes.outputs.build-change == 'true' }}
      run-sagemaker-test: ${{ needs.check-changes.outputs.build-change == 'true' || needs.check-changes.outputs.sagemaker-test-change == 'true' }}
      release: false
    secrets: inherit
