name: "Auto Release - vLLM-Omni SageMaker"

on:
  schedule:
    - cron: '00 21 * * 2,4'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  pipeline:
    uses: ./.github/workflows/vllm-omni.pipeline.yml
    with:
      config-file: .github/config/image/vllm-omni/sagemaker-amzn2023.yml
      tag-suffix: ${{ github.run_id }}
      release: true
    secrets: inherit
