name: "Auto Release - vLLM SageMaker Ubuntu"

on:
  schedule:
    - cron: '00 20 * * 1,3'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  pipeline:
    uses: ./.github/workflows/vllm.pipeline.yml
    with:
      config-file: .github/config/image/vllm/sagemaker-ubuntu.yml
      tag-suffix: ${{ github.run_id }}
      release: true
    secrets: inherit
