#### First image: sha256:b28bb8fe67e314ed3b6302d0a71c41a9c5d732e1d3791c85884901e747b7261e ####
#### Current Patch contents ####
echo N/A 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade binutils-common binutils-x86-64-linux-gnu binutils bsdutils curl fdisk libbinutils libblkid1 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4 libfdisk1 libmount1 libsmartcols1 libssl-dev libssl1.1 libuuid1 libxml2 mount openssl util-linux uuid-dev vim-common vim-runtime vim xxd
