version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - bash eks_infrastructure/env_setup.sh
  build:
    commands:
      - bash eks_infrastructure/build.sh
